/*
 RequireJS 0.22.0 Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.4
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Thu Nov 11 19:04:53 2010 -0500
*/
var require,define;
(function(){function R(y){return Qa.call(y)==="[object Function]"}function I(y){return Qa.call(y)==="[object Array]"}function Fa(y,D,K){for(var L in D)if(!(L in pa)&&(!(L in y)||K))y[L]=D[L];return F}function xa(y,D,K){var L,aa,P;for(L=0;P=D[L];L++){P=typeof P==="string"?{name:P}:P;aa=P.location;if(K&&(!aa||aa.indexOf("/")!==0&&aa.indexOf(":")===-1))P.location=K+"/"+(P.location||P.name);P.location=P.location||P.name;P.lib=P.lib||"lib";P.main=(P.main||"lib/main").replace(ab,"");y[P.name]=P}}function Ra(y){function D(k){var o,
s;for(o=0;s=k[o];o++)if(s==="."){k.splice(o,1);o-=1}else if(s==="..")if(o===1&&(k[2]===".."||k[0]===".."))break;else if(o>0){k.splice(o-1,2);o-=2}}function K(k,o){var s;if(k.charAt(0)===".")if(o){if(da.packages[o])o=[o];else{o=o.split("/");o=o.slice(0,o.length-1)}k=o.concat(k.split("/"));D(k);s=da.packages[o=k[0]];k=k.join("/");if(s&&k===o+"/"+s.main)k=o}return k}function L(k,o){var s=k?k.indexOf("!"):-1,x=null,E=o?o.name:null,Q=k,M,V;if(s!==-1){x=k.substring(0,s);k=k.substring(s+1,k.length)}if(x){x=
K(x,E);x=Sa[x]||x}if(k){if(x)M=(s=Y[x])?s.normalize?s.normalize(k,function(ba){return K(ba,E)}):K(k,E):"__$p"+E+"@"+k;else M=K(k,E);V=Ta[M];if(!V){V=F.toModuleUrl?F.toModuleUrl(J,k,o):J.nameToUrl(k,null,o);Ta[M]=V}}return{prefix:x,name:M,parentMap:o,url:V,originalName:Q,fullName:x?x+"!"+M:M}}function aa(){var k=true,o=da.priorityWait,s,x;if(o){for(x=0;s=o[x];x++)if(!ia[s]){k=false;break}k&&delete da.priorityWait}return k}function P(k){return function(o){k.exports=o}}function Ga(k,o,s){return function(){var x=
[].concat(bb.call(arguments,0)),E;if(s&&R(E=x[x.length-1]))E.__requireJsBuild=true;x.push(o);return k.apply(null,x)}}function cb(k,o){o=Ga(J.require,k,o);Fa(o,{nameToUrl:Ga(J.nameToUrl,k),toUrl:Ga(J.toUrl,k),isDefined:Ga(J.isDefined,k),ready:F.ready,isBrowser:F.isBrowser});if(F.paths)o.paths=F.paths;return o}function lb(k){var o,s,x,E,Q,M,V,ba=Ha[k];if(ba)for(E=0;s=ba[E];E++){o=s.fullName;s=L(s.originalName,s.parentMap);s=s.fullName;x=ea[o];if(s!==o){ea[s]=x;delete ea[o];for(Q=0;Q<x.length;Q++){V=
x[Q].depArray;for(M=0;M<V.length;M++)if(V[M]===o)V[M]=s}}}delete Ha[k]}function db(k){var o=k.prefix,s=k.fullName;if(!(Ba[s]||s in Y)){if(o&&!ta[o]){ta[o]=undefined;(Ha[o]||(Ha[o]=[])).push(k);(ea[o]||(ea[o]=[])).push({onDep:function(x){x===o&&lb(o)}});db(L(o))}J.paused.push(k)}}function Ia(k){var o,s,x;o=k.callback;var E=k.fullName;x=[];var Q=k.depArray;if(o&&R(o)){if(Q)for(o=0;o<Q.length;o++)x.push(k.deps[Q[o]]);s=F.execCb(E,k.callback,x);if(E)if(k.usingExports&&s===undefined&&(!k.cjsModule||!("exports"in
k.cjsModule)))s=Y[E];else if(k.cjsModule&&"exports"in k.cjsModule)s=Y[E]=k.cjsModule.exports;else{if(E in Y&&!k.usingExports)return F.onError(new Error(E+" has already been defined"));Y[E]=s}}else if(E)s=Y[E]=o;if(E)if(x=ea[E]){for(o=0;o<x.length;o++)x[o].onDep(E,s);delete ea[E]}if(ua[k.waitId]){delete ua[k.waitId];k.isDone=true;J.waitCount-=1;if(J.waitCount===0)Ua=[]}}function Ca(k,o,s,x){k=L(k,x);var E=k.name,Q=k.fullName,M={waitId:E||eb+mb++,depCount:0,depMax:0,prefix:k.prefix,name:E,fullName:Q,
deps:{},depArray:o,callback:s,onDep:function(fb,nb){if(!(fb in M.deps)){M.deps[fb]=nb;M.depCount+=1;M.depCount===M.depMax&&Ia(M)}}},V,ba;if(Q){if(Q in Y||ia[Q]===true)return;Ba[Q]=true;ia[Q]=true;J.jQueryDef=Q==="jquery"}for(s=0;s<o.length;s++)if(V=o[s]){V=L(V,E?k:x);ba=V.fullName;o[s]=ba;if(ba==="require")M.deps[ba]=cb(k);else if(ba==="exports"){M.deps[ba]=Y[Q]={};M.usingExports=true}else if(ba==="module"){M.cjsModule=V=M.deps[ba]={id:E,uri:E?J.nameToUrl(E,null,x):undefined};V.setExports=P(V)}else if(ba in
Y&&!(ba in ua))M.deps[ba]=Y[ba];else{M.depMax+=1;db(V);(ea[ba]||(ea[ba]=[])).push(M)}}if(M.depCount===M.depMax)Ia(M);else{ua[M.waitId]=M;Ua.push(M);J.waitCount+=1}}function ya(k){Ca.apply(null,k);ia[k[0]]=true}function Va(k){if(!J.jQuery)if((k=k||(typeof jQuery!=="undefined"?jQuery:null))&&"readyWait"in k){J.jQuery=k;ya(["jquery",[],function(){return jQuery}]);if(J.scriptCount){k.readyWait+=1;J.jQueryIncremented=true}}}function gb(k,o){if(!k.isDone){var s=k.fullName,x=k.depArray,E,Q;if(s){if(o[s])return Y[s];
o[s]=true}for(Q=0;Q<x.length;Q++)(E=x[Q])&&!k.deps[E]&&ua[E]&&k.onDep(E,gb(ua[E],o));return s?Y[s]:undefined}}function Wa(){var k=da.waitSeconds*1E3,o=k&&J.startTime+k<(new Date).getTime();k="";var s=false,x=false,E;if(da.priorityWait)if(aa())ca();else return;for(E in ia)if(!(E in pa)){s=true;if(!ia[E])if(o)k+=E+" ";else{x=true;break}}if(s||J.waitCount){if(o&&k){E=new Error("require.js load timeout for modules: "+k);E.requireType="timeout";E.requireModules=k;return F.onError(E)}if(x||J.scriptCount){if(na||
Ja)setTimeout(Wa,50)}else if(J.waitCount){for(va=0;k=Ua[va];va++)gb(k,{});Wa()}else F.checkReadyState()}}function Xa(k,o){var s=o.name,x=o.fullName;if(!(x in Y)){ta[k]||(ta[k]=Y[k]);ia[x]||(ia[x]=false);ta[k].load(s,cb(o.parentMap,true),function(E){require.onPluginLoad&&require.onPluginLoad(J,k,s,E);Ia({prefix:o.prefix,name:o.name,fullName:o.fullName,callback:E});ia[x]=true},da)}}function hb(k){if(k.prefix&&k.name.indexOf("__$p")===0&&Y[k.prefix])k=L(k.originalName,k.parentMap);var o=k.prefix,s=k.fullName;
if(!(Ba[s]||s in Y)){Ba[s]=true;if(o)if(Y[o])Xa(o,k);else{if(!qa[o]){qa[o]=[];(ea[o]||(ea[o]=[])).push({onDep:function(x){if(x===o){var E,Q=qa[o];for(x=0;x<Q.length;x++){E=Q[x];Xa(o,L(E.originalName,E.parentMap))}delete qa[o]}}})}qa[o].push(k)}else F.load(J,s,k.url)}}var J,ca,da={waitSeconds:7,baseUrl:W.baseUrl||"./",paths:{},packages:{}},Da=[],Ba={require:true,exports:true,module:true},Ta={},Y={},ia={},ua={},Ua=[],mb=0,ea={},ta={},qa={},Ha={};ca=function(){var k,o,s;if(J.scriptCount<=0)J.scriptCount=
0;for(;Da.length;){k=Da.shift();if(k[0]===null)return F.onError(new Error("Mismatched anonymous require.def modules"));else ya(k)}if(!(da.priorityWait&&!aa())){for(;J.paused.length;){s=J.paused;J.paused=[];for(o=0;k=s[o];o++)hb(k);J.startTime=(new Date).getTime()}Wa()}};J={contextName:y,config:da,defQueue:Da,waiting:ua,waitCount:0,specified:Ba,loaded:ia,urlMap:Ta,scriptCount:0,urlFetched:{},defined:Y,paused:[],plugins:ta,managerCallbacks:ea,makeModuleMap:L,normalize:K,configure:function(k){var o,
s,x;if(k.baseUrl)if(k.baseUrl.charAt(k.baseUrl.length-1)!=="/")k.baseUrl+="/";o=da.paths;s=da.packages;Fa(da,k,true);if(k.paths){for(x in k.paths)x in pa||(o[x]=k.paths[x]);da.paths=o}if((o=k.packagePaths)||k.packages){if(o)for(x in o)x in pa||xa(s,o[x],x);k.packages&&xa(s,k.packages);da.packages=s}if(k.priority){s=J.requireWait;J.requireWait=false;J.require(k.priority);J.requireWait=s;da.priorityWait=k.priority}if(k.deps||k.callback)J.require(k.deps||[],k.callback);k.ready&&F.ready(k.ready)},isDefined:function(k,
o){return L(k,o).fullName in Y},require:function(k,o,s){if(typeof k==="string"){if(F.get)return F.get(J,k,o);s=o;o=L(k,s);k=Y[o.fullName];if(k===undefined)return F.onError(new Error("require: module name '"+o.fullName+"' has not been loaded yet for context: "+y));return k}Ca(null,k,o,s);if(!J.requireWait)for(;!J.scriptCount&&J.paused.length;)ca()},takeGlobalQueue:function(){if(c.length){ob.apply(J.defQueue,[J.defQueue.length-1,0].concat(c));c=[]}},completeLoad:function(k){var o;for(J.takeGlobalQueue();Da.length;){o=
Da.shift();if(o[0]===null){o[0]=k;break}else if(o[0]===k)break;else{ya(o);o=null}}o?ya(o):ya([k,[],k==="jquery"&&typeof jQuery!=="undefined"?function(){return jQuery}:null]);ia[k]=true;Va();if(F.isAsync)J.scriptCount-=1;ca();F.isAsync||(J.scriptCount-=1)},toUrl:function(k,o){var s=k.lastIndexOf("."),x=null;if(s!==-1){x=k.substring(s,k.length);k=k.substring(0,s)}return J.nameToUrl(k,x,o)},nameToUrl:function(k,o,s){var x,E,Q,M,V=J.config;if(k.indexOf("./")===0||k.indexOf("../")===0){s=s&&s.url?s.url.split("/"):
[];s.length&&s.pop();s=s.concat(k.split("/"));D(s);o=s.join("/")+(o?o:F.jsExtRegExp.test(k)?"":".js")}else{k=K(k,s);if(F.jsExtRegExp.test(k))o=k+(o?o:"");else{x=V.paths;E=V.packages;s=k.split("/");for(M=s.length;M>0;M--){Q=s.slice(0,M).join("/");if(x[Q]){s.splice(0,M,x[Q]);break}else if(Q=E[Q]){k=k===Q.name?Q.location+"/"+Q.main:Q.location+"/"+Q.lib;s.splice(0,M,k);break}}o=s.join("/")+(o||".js");o=(o.charAt(0)==="/"||o.match(/^\w+:/)?"":V.baseUrl)+o}}return V.urlArgs?o+((o.indexOf("?")===-1?"?":
"&")+V.urlArgs):o}};J.jQueryCheck=Va;J.resume=ca;return J}function ib(){var y,D,K;if(za&&za.readyState==="interactive")return za;y=document.getElementsByTagName("script");for(D=y.length-1;D>-1&&(K=y[D]);D--)if(K.readyState==="interactive")return za=K;return null}var pb=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,Ka=/require\(["']([^'"\s]+)["']\)/g,ab=/^\.\//,Qa=Object.prototype.toString,fa=Array.prototype,bb=fa.slice,ob=fa.splice,na=!!(typeof window!=="undefined"&&navigator&&document),Ja=!na&&typeof importScripts!==
"undefined",Aa=na&&navigator.platform==="PLAYSTATION 3"?/^complete$/:/^(complete|loaded)$/,eb="_r@@",pa={},w={},c=[],za=null,qb=false,Ya=false,Sa={text:"require/text",i18n:"require/i18n",order:"require/order"},F;fa={};var Za,W,wa,La,Ma,ra,Na,oa,jb,Oa,va,Pa,$a,sa;if(typeof require!=="undefined")if(R(require))return;else fa=require;F=require=function(y,D,K){var L="_",aa;if(!I(y)&&typeof y!=="string"){aa=y;if(I(D)){y=D;D=K}else y=[]}if(aa&&aa.context)L=aa.context;K=w[L]||(w[L]=Ra(L));aa&&K.configure(aa);
return K.require(y,D)};F.version="0.22.0";F.isArray=I;F.isFunction=R;F.mixin=Fa;F.jsExtRegExp=/^\/|:|\?|\.js$/;W=F.s={contexts:w,skipAsync:{},isPageLoaded:!na,readyCalls:[]};if(F.isAsync=F.isBrowser=na){wa=W.head=document.getElementsByTagName("head")[0];if(La=document.getElementsByTagName("base")[0])wa=W.head=La.parentNode}F.onError=function(y){throw y;};F.load=function(y,D,K){var L=y.contextName,aa=y.urlFetched,P=y.loaded;qb=false;P[D]||(P[D]=false);if(!aa[K]){y.scriptCount+=1;F.attach(K,L,D);aa[K]=
true;if(y.jQuery&&!y.jQueryIncremented){y.jQuery.readyWait+=1;y.jQueryIncremented=true}}};define=F.def=function(y,D,K){var L;if(typeof y!=="string"){K=D;D=y;y=null}if(!F.isArray(D)){K=D;D=[]}if(!y&&!D.length&&F.isFunction(K))if(K.length){K.toString().replace(pb,"").replace(Ka,function(aa,P){D.push(P)});D=["require","exports","module"].concat(D)}if(Ya){L=Za||ib();if(!L)return F.onError(new Error("ERROR: No matching script interactive for "+K));y||(y=L.getAttribute("data-requiremodule"));L=w[L.getAttribute("data-requirecontext")]}(L?
L.defQueue:c).push([y,D,K])};F.execCb=function(y,D,K){return D.apply(null,K)};F.onScriptLoad=function(y){var D=y.currentTarget||y.srcElement,K;if(y.type==="load"||Aa.test(D.readyState)){za=null;y=D.getAttribute("data-requirecontext");K=D.getAttribute("data-requiremodule");w[y].completeLoad(K);D.removeEventListener?D.removeEventListener("load",F.onScriptLoad,false):D.detachEvent("onreadystatechange",F.onScriptLoad)}};F.attach=function(y,D,K,L,aa){var P;if(na){L=L||F.onScriptLoad;P=document.createElement("script");
P.type=aa||"text/javascript";P.charset="utf-8";P.async=!W.skipAsync[y];P.setAttribute("data-requirecontext",D);P.setAttribute("data-requiremodule",K);if(P.addEventListener)P.addEventListener("load",L,false);else{Ya=true;P.attachEvent("onreadystatechange",L)}P.src=y;Za=P;La?wa.insertBefore(P,La):wa.appendChild(P);Za=null;return P}else if(Ja){L=w[D];D=L.loaded;D[K]=false;importScripts(y);L.completeLoad(K)}return null};W.baseUrl=fa.baseUrl;if(na&&(!W.baseUrl||!wa)){Ma=document.getElementsByTagName("script");
Na=fa.baseUrlMatch?fa.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(va=Ma.length-1;va>-1&&(ra=Ma[va]);va--){if(!wa)wa=ra.parentNode;if(!Oa&&(Oa=ra.getAttribute("data-main"))){fa.deps=fa.deps?fa.deps.concat(Oa):[Oa];if(!fa.baseUrl&&(oa=ra.src)){oa=oa.split("/");oa.pop();W.baseUrl=fa.baseUrl=oa.length?oa.join("/"):"./"}}if(!W.baseUrl&&(oa=ra.src))if(jb=oa.match(Na)){W.baseUrl=oa.substring(0,jb.index);break}}}F.pageLoaded=function(){if(!W.isPageLoaded){W.isPageLoaded=
true;Pa&&clearInterval(Pa);if($a)document.readyState="complete";F.callReady()}};F.checkReadyState=function(){var y=W.contexts,D;for(D in y)if(!(D in pa))if(y[D].waitCount)return;W.isDone=true;F.callReady()};F.callReady=function(){var y=W.readyCalls,D,K,L;if(W.isPageLoaded&&W.isDone){if(y.length){W.readyCalls=[];for(D=0;K=y[D];D++)K()}y=W.contexts;for(L in y)if(!(L in pa)){D=y[L];if(D.jQueryIncremented){D.jQuery.readyWait-=1;D.jQueryIncremented=false}}}};F.ready=function(y){W.isPageLoaded&&W.isDone?
y():W.readyCalls.push(y);return F};if(na){if(document.addEventListener){document.addEventListener("DOMContentLoaded",F.pageLoaded,false);window.addEventListener("load",F.pageLoaded,false);if(!document.readyState){$a=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",F.pageLoaded);if(self===self.top)Pa=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");F.pageLoaded()}}catch(y){}},30)}document.readyState==="complete"&&F.pageLoaded()}F(fa);
if(typeof setTimeout!=="undefined"){sa=W.contexts[fa.context||"_"];sa.requireWait=true;setTimeout(function(){sa.requireWait=false;sa.takeGlobalQueue();sa.jQueryCheck();sa.scriptCount||sa.resume();F.checkReadyState()},0)}})();
(function(R,I){function Fa(a,b,d){if(d===I&&a.nodeType===1){d=a.getAttribute("data-"+b);if(typeof d==="string"){try{d=d==="true"?true:d==="false"?false:d==="null"?null:!c.isNaN(d)?parseFloat(d):qb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=I}return d}function xa(){return false}function Ra(){return true}function ib(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function pb(a){var b,d,e,f,h,m,l,p,A,v,G,O=[];f=[];h=c.data(this,this.nodeType?"events":"__events__");if(typeof h==="function")h=
h.events;if(!(a.liveFired===this||!h||!h.live||a.button&&a.type==="click")){if(a.namespace)G=new RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)");a.liveFired=this;var Z=h.live.slice(0);for(l=0;l<Z.length;l++){h=Z[l];h.origType.replace(ra,"")===a.type?f.push(h.selector):Z.splice(l--,1)}f=c(a.target).closest(f,a.currentTarget);p=0;for(A=f.length;p<A;p++){v=f[p];for(l=0;l<Z.length;l++){h=Z[l];if(v.selector===h.selector&&(!G||G.test(h.namespace))){m=v.elem;e=null;if(h.preType===
"mouseenter"||h.preType==="mouseleave"){a.type=h.preType;e=c(a.relatedTarget).closest(h.selector)[0]}if(!e||e!==m)O.push({elem:m,handleObj:h,level:v.level})}}}p=0;for(A=O.length;p<A;p++){f=O[p];if(d&&f.level>d)break;a.currentTarget=f.elem;a.data=f.handleObj.data;a.handleObj=f.handleObj;G=f.handleObj.origHandler.apply(f.elem,arguments);if(G===false||a.isPropagationStopped()){d=f.level;if(G===false)b=false;if(a.isImmediatePropagationStopped())break}}return b}}function Ka(a,b){return(a&&a!=="*"?a+".":
"")+b.replace(oa,"`").replace(jb,"&")}function ab(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function Qa(a,b,d){if(c.isFunction(b))return c.grep(a,function(f,h){return!!b.call(f,h,f)===d});else if(b.nodeType)return c.grep(a,function(f){return f===b===d});else if(typeof b==="string"){var e=c.grep(a,function(f){return f.nodeType===1});if(cb.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(f){return c.inArray(f,b)>=0===d})}function fa(a){return c.nodeName(a,"table")?
a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function bb(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var e=c.data(a[d++]),f=c.data(this,e);if(e=e&&e.events){delete f.handle;f.events={};for(var h in e)for(var m in e[h])c.event.add(this,h,e[h][m],e[h][m].data)}}})}function ob(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}
function na(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?Ua:mb,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);if(d==="margin")e+=parseFloat(c.css(a,"margin"+this))||0;else e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function Ja(a,b,d,e){if(c.isArray(b)&&b.length)c.each(b,function(f,h){d||Q.test(a)?e(a,h):Ja(a+"["+(typeof h==="object"||c.isArray(h)?f:"")+"]",h,d,e)});else if(!d&&b!=null&&typeof b==="object")c.isEmptyObject(b)?
e(a,""):c.each(b,function(f,h){Ja(a+"["+f+"]",h,d,e)});else e(a,b)}function Aa(a,b){var d={};c.each(tb.concat.apply([],tb.slice(0,b)),function(){d[this]=a});return d}function eb(a){if(!rb[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d==="")d="block";rb[a]=d}return rb[a]}function pa(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var w=R.document,c=function(){function a(){if(!b.isReady){try{w.documentElement.doScroll("left")}catch(j){setTimeout(a,
1);return}b.ready()}}var b=function(j,t){return new b.fn.init(j,t)},d=R.jQuery,e=R.$,f,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,m=/\S/,l=/^\s+/,p=/\s+$/,A=/\W/,v=/\d/,G=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,O=/^[\],:{}\s]*$/,Z=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,B=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,X=/(?:^|:|,)(?:\s*\[)+/g,ja=/(webkit)[ \/]([\w.]+)/,g=/(opera)(?:.*version)?[ \/]([\w.]+)/,i=/(msie) ([\w.]+)/,n=/(mozilla)(?:.*? rv:([\w.]+))?/,q=navigator.userAgent,r=false,
u=[],C,H=Object.prototype.toString,T=Object.prototype.hasOwnProperty,ha=Array.prototype.push,ka=Array.prototype.slice,la=String.prototype.trim,S=Array.prototype.indexOf,Ea={};b.fn=b.prototype={init:function(j,t){var z,N;if(!j)return this;if(j.nodeType){this.context=this[0]=j;this.length=1;return this}if(j==="body"&&!t&&w.body){this.context=w;this[0]=w.body;this.selector="body";this.length=1;return this}if(typeof j==="string")if((z=h.exec(j))&&(z[1]||!t))if(z[1]){N=t?t.ownerDocument||t:w;if(j=G.exec(j))if(b.isPlainObject(t)){j=
[w.createElement(j[1])];b.fn.attr.call(j,t,true)}else j=[N.createElement(j[1])];else{j=b.buildFragment([z[1]],[N]);j=(j.cacheable?j.fragment.cloneNode(true):j.fragment).childNodes}return b.merge(this,j)}else{if((t=w.getElementById(z[2]))&&t.parentNode){if(t.id!==z[2])return f.find(j);this.length=1;this[0]=t}this.context=w;this.selector=j;return this}else if(!t&&!A.test(j)){this.selector=j;this.context=w;j=w.getElementsByTagName(j);return b.merge(this,j)}else return!t||t.jquery?(t||f).find(j):b(t).find(j);
else if(b.isFunction(j))return f.ready(j);if(j.selector!==I){this.selector=j.selector;this.context=j.context}return b.makeArray(j,this)},selector:"",jquery:"1.4.4",length:0,size:function(){return this.length},toArray:function(){return ka.call(this,0)},get:function(j){return j==null?this.toArray():j<0?this.slice(j)[0]:this[j]},pushStack:function(j,t,z){var N=b();b.isArray(j)?ha.apply(N,j):b.merge(N,j);N.prevObject=this;N.context=this.context;if(t==="find")N.selector=this.selector+(this.selector?" ":
"")+z;else if(t)N.selector=this.selector+"."+t+"("+z+")";return N},each:function(j,t){return b.each(this,j,t)},ready:function(j){b.bindReady();if(b.isReady)j.call(w,b);else u&&u.push(j);return this},eq:function(j){return j===-1?this.slice(j):this.slice(j,+j+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ka.apply(this,arguments),"slice",ka.call(arguments).join(","))},map:function(j){return this.pushStack(b.map(this,function(t,z){return j.call(t,
z,t)}))},end:function(){return this.prevObject||b(null)},push:ha,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var j,t,z,N,$,U=arguments[0]||{},ga=1,ma=arguments.length,sb=false;if(typeof U==="boolean"){sb=U;U=arguments[1]||{};ga=2}if(typeof U!=="object"&&!b.isFunction(U))U={};if(ma===ga){U=this;--ga}for(;ga<ma;ga++)if((j=arguments[ga])!=null)for(t in j){z=U[t];N=j[t];if(U!==N)if(sb&&N&&(b.isPlainObject(N)||($=b.isArray(N)))){if($){$=false;z=z&&b.isArray(z)?
z:[]}else z=z&&b.isPlainObject(z)?z:{};U[t]=b.extend(sb,z,N)}else if(N!==I)U[t]=N}return U};b.extend({noConflict:function(j){R.$=e;if(j)R.jQuery=d;return b},isReady:false,readyWait:1,ready:function(j){j===true&&b.readyWait--;if(!b.readyWait||j!==true&&!b.isReady){if(!w.body)return setTimeout(b.ready,1);b.isReady=true;if(!(j!==true&&--b.readyWait>0))if(u){var t=0,z=u;for(u=null;j=z[t++];)j.call(w,b);b.fn.trigger&&b(w).trigger("ready").unbind("ready")}}},bindReady:function(){if(!r){r=true;if(w.readyState===
"complete")return setTimeout(b.ready,1);if(w.addEventListener){w.addEventListener("DOMContentLoaded",C,false);R.addEventListener("load",b.ready,false)}else if(w.attachEvent){w.attachEvent("onreadystatechange",C);R.attachEvent("onload",b.ready);var j=false;try{j=R.frameElement==null}catch(t){}w.documentElement.doScroll&&j&&a()}}},isFunction:function(j){return b.type(j)==="function"},isArray:Array.isArray||function(j){return b.type(j)==="array"},isWindow:function(j){return j&&typeof j==="object"&&"setInterval"in
j},isNaN:function(j){return j==null||!v.test(j)||isNaN(j)},type:function(j){return j==null?String(j):Ea[H.call(j)]||"object"},isPlainObject:function(j){if(!j||b.type(j)!=="object"||j.nodeType||b.isWindow(j))return false;if(j.constructor&&!T.call(j,"constructor")&&!T.call(j.constructor.prototype,"isPrototypeOf"))return false;var t;for(t in j);return t===I||T.call(j,t)},isEmptyObject:function(j){for(var t in j)return false;return true},error:function(j){throw j;},parseJSON:function(j){if(typeof j!==
"string"||!j)return null;j=b.trim(j);if(O.test(j.replace(Z,"@").replace(B,"]").replace(X,"")))return R.JSON&&R.JSON.parse?R.JSON.parse(j):(new Function("return "+j))();else b.error("Invalid JSON: "+j)},noop:function(){},globalEval:function(j){if(j&&m.test(j)){var t=w.getElementsByTagName("head")[0]||w.documentElement,z=w.createElement("script");z.type="text/javascript";if(b.support.scriptEval)z.appendChild(w.createTextNode(j));else z.text=j;t.insertBefore(z,t.firstChild);t.removeChild(z)}},nodeName:function(j,
t){return j.nodeName&&j.nodeName.toUpperCase()===t.toUpperCase()},each:function(j,t,z){var N,$=0,U=j.length,ga=U===I||b.isFunction(j);if(z)if(ga)for(N in j){if(t.apply(j[N],z)===false)break}else for(;$<U;){if(t.apply(j[$++],z)===false)break}else if(ga)for(N in j){if(t.call(j[N],N,j[N])===false)break}else for(z=j[0];$<U&&t.call(z,$,z)!==false;z=j[++$]);return j},trim:la?function(j){return j==null?"":la.call(j)}:function(j){return j==null?"":j.toString().replace(l,"").replace(p,"")},makeArray:function(j,
t){t=t||[];if(j!=null){var z=b.type(j);j.length==null||z==="string"||z==="function"||z==="regexp"||b.isWindow(j)?ha.call(t,j):b.merge(t,j)}return t},inArray:function(j,t){if(t.indexOf)return t.indexOf(j);for(var z=0,N=t.length;z<N;z++)if(t[z]===j)return z;return-1},merge:function(j,t){var z=j.length,N=0;if(typeof t.length==="number")for(var $=t.length;N<$;N++)j[z++]=t[N];else for(;t[N]!==I;)j[z++]=t[N++];j.length=z;return j},grep:function(j,t,z){var N=[],$;z=!!z;for(var U=0,ga=j.length;U<ga;U++){$=
!!t(j[U],U);z!==$&&N.push(j[U])}return N},map:function(j,t,z){for(var N=[],$,U=0,ga=j.length;U<ga;U++){$=t(j[U],U,z);if($!=null)N[N.length]=$}return N.concat.apply([],N)},guid:1,proxy:function(j,t,z){if(arguments.length===2)if(typeof t==="string"){z=j;j=z[t];t=I}else if(t&&!b.isFunction(t)){z=t;t=I}if(!t&&j)t=function(){return j.apply(z||this,arguments)};if(j)t.guid=j.guid=j.guid||t.guid||b.guid++;return t},access:function(j,t,z,N,$,U){var ga=j.length;if(typeof t==="object"){for(var ma in t)b.access(j,
ma,t[ma],N,$,z);return j}if(z!==I){N=!U&&N&&b.isFunction(z);for(ma=0;ma<ga;ma++)$(j[ma],t,N?z.call(j[ma],ma,$(j[ma],t)):z,U);return j}return ga?$(j[0],t):I},now:function(){return(new Date).getTime()},uaMatch:function(j){j=j.toLowerCase();j=ja.exec(j)||g.exec(j)||i.exec(j)||j.indexOf("compatible")<0&&n.exec(j)||[];return{browser:j[1]||"",version:j[2]||"0"}},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(j,t){Ea["[object "+t+"]"]=t.toLowerCase()});
q=b.uaMatch(q);if(q.browser){b.browser[q.browser]=true;b.browser.version=q.version}if(b.browser.webkit)b.browser.safari=true;if(S)b.inArray=function(j,t){return S.call(t,j)};if(!/\s/.test("\u00a0")){l=/^[\s\xA0]+/;p=/[\s\xA0]+$/}f=b(w);if(w.addEventListener)C=function(){w.removeEventListener("DOMContentLoaded",C,false);b.ready()};else if(w.attachEvent)C=function(){if(w.readyState==="complete"){w.detachEvent("onreadystatechange",C);b.ready()}};return R.jQuery=R.$=b}();(function(){c.support={};var a=
w.documentElement,b=w.createElement("script"),d=w.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var f=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],m=w.createElement("select"),l=m.appendChild(w.createElement("option"));if(!(!f||!f.length||!h)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,
htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:h.getAttribute("href")==="/a",opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:l.selected,deleteExpando:true,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};m.disabled=true;c.support.optDisabled=
!l.disabled;b.type="text/javascript";try{b.appendChild(w.createTextNode("window."+e+"=1;"))}catch(p){}a.insertBefore(b,a.firstChild);if(R[e]){c.support.scriptEval=true;delete R[e]}try{delete b.test}catch(A){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function v(){c.support.noCloneEvent=false;d.detachEvent("onclick",v)});d.cloneNode(true).fireEvent("onclick")}d=w.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
a=w.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var v=w.createElement("div");v.style.width=v.style.paddingLeft="1px";w.body.appendChild(v);c.boxModel=c.support.boxModel=v.offsetWidth===2;if("zoom"in v.style){v.style.display="inline";v.style.zoom=1;c.support.inlineBlockNeedsLayout=v.offsetWidth===2;v.style.display="";v.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=v.offsetWidth!==
2}v.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var G=v.getElementsByTagName("td");c.support.reliableHiddenOffsets=G[0].offsetHeight===0;G[0].style.display="";G[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&G[0].offsetHeight===0;v.innerHTML="";w.body.removeChild(v).style.display="none"});a=function(v){var G=w.createElement("div");v="on"+v;var O=v in G;if(!O){G.setAttribute(v,"return;");O=typeof G[v]==="function"}return O};
c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=f=h=null}})();var za={},qb=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},data:function(a,b,d){if(c.acceptData(a)){a=a==R?za:a;var e=a.nodeType,f=e?a[c.expando]:null,h=c.cache;if(!(e&&!f&&typeof b==="string"&&d===I)){if(e)f||(a[c.expando]=f=++c.uuid);else h=a;if(typeof b==="object")if(e)h[f]=c.extend(h[f],b);else c.extend(h,
b);else if(e&&!h[f])h[f]={};a=e?h[f]:h;if(d!==I)a[b]=d;return typeof b==="string"?a[b]:a}}},removeData:function(a,b){if(c.acceptData(a)){a=a==R?za:a;var d=a.nodeType,e=d?a[c.expando]:a,f=c.cache,h=d?f[e]:e;if(b){if(h){delete h[b];d&&c.isEmptyObject(h)&&c.removeData(a)}}else if(d&&c.support.deleteExpando)delete a[c.expando];else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete f[e];else for(var m in a)delete a[m]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];
if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){var d=null;if(typeof a==="undefined"){if(this.length){var e=this[0].attributes,f;d=c.data(this[0]);for(var h=0,m=e.length;h<m;h++){f=e[h].name;if(f.indexOf("data-")===0){f=f.substr(5);Fa(this[0],f,d[f])}}}return d}else if(typeof a==="object")return this.each(function(){c.data(this,a)});var l=a.split(".");l[1]=l[1]?"."+l[1]:"";if(b===I){d=this.triggerHandler("getData"+l[1]+"!",[l[0]]);if(d===I&&this.length){d=
c.data(this[0],a);d=Fa(this[0],a,d)}return d===I&&l[1]?this.data(l[0]):d}else return this.each(function(){var p=c(this),A=[l[0],b];p.triggerHandler("setData"+l[1]+"!",A);c.data(this,a,b);p.triggerHandler("changeData"+l[1]+"!",A)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c.data(a,b);if(!d)return e||[];if(!e||c.isArray(d))e=c.data(a,b,c.makeArray(d));else e.push(d);return e}},dequeue:function(a,b){b=
b||"fx";var d=c.queue(a,b),e=d.shift();if(e==="inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");e.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===I)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,
function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var Ya=/[\n\t]/g,Sa=/\s+/,F=/\r/g,Za=/^(?:href|src|style)$/,W=/^(?:button|input)$/i,wa=/^(?:button|input|object|select|textarea)$/i,La=/^a(?:rea)?$/i,Ma=/^(?:radio|checkbox)$/i;c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};
c.fn.extend({attr:function(a,b){return c.access(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(A){var v=c(this);v.addClass(a.call(this,A,v.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(Sa),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1)if(f.className){for(var h=" "+f.className+" ",m=f.className,l=0,p=b.length;l<
p;l++)if(h.indexOf(" "+b[l]+" ")<0)m+=" "+b[l];f.className=c.trim(m)}else f.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(p){var A=c(this);A.removeClass(a.call(this,p,A.attr("class")))});if(a&&typeof a==="string"||a===I)for(var b=(a||"").split(Sa),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1&&f.className)if(a){for(var h=(" "+f.className+" ").replace(Ya," "),m=0,l=b.length;m<l;m++)h=h.replace(" "+b[m]+" "," ");f.className=c.trim(h)}else f.className=
""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(f){var h=c(this);h.toggleClass(a.call(this,f,h.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var f,h=0,m=c(this),l=b,p=a.split(Sa);f=p[h++];){l=e?l:!m.hasClass(f);m[l?"addClass":"removeClass"](f)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,
"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ya," ").indexOf(a)>-1)return true;return false},val:function(a){if(!arguments.length){var b=this[0];if(b){if(c.nodeName(b,"option")){var d=b.attributes.value;return!d||d.specified?b.value:b.text}if(c.nodeName(b,"select")){var e=b.selectedIndex;d=[];var f=b.options;b=b.type==="select-one";if(e<0)return null;var h=b?e:0;for(e=b?e+1:f.length;h<e;h++){var m=f[h];if(m.selected&&
(c.support.optDisabled?!m.disabled:m.getAttribute("disabled")===null)&&(!m.parentNode.disabled||!c.nodeName(m.parentNode,"optgroup"))){a=c(m).val();if(b)return a;d.push(a)}}return d}if(Ma.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(F,"")}return I}var l=c.isFunction(a);return this.each(function(p){var A=c(this),v=a;if(this.nodeType===1){if(l)v=a.call(this,p,A.val());if(v==null)v="";else if(typeof v==="number")v+="";else if(c.isArray(v))v=
c.map(v,function(O){return O==null?"":O+""});if(c.isArray(v)&&Ma.test(this.type))this.checked=c.inArray(A.val(),v)>=0;else if(c.nodeName(this,"select")){var G=c.makeArray(v);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),G)>=0});if(!G.length)this.selectedIndex=-1}else this.value=v}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,e){if(!a||a.nodeType===3||a.nodeType===8)return I;if(e&&b in c.attrFn)return c(a)[b](d);
e=a.nodeType!==1||!c.isXMLDoc(a);var f=d!==I;b=e&&c.props[b]||b;var h=Za.test(b);if((b in a||a[b]!==I)&&e&&!h){if(f){b==="type"&&W.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");if(d===null)a.nodeType===1&&a.removeAttribute(b);else a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:wa.test(a.nodeName)||La.test(a.nodeName)&&a.href?0:I;return a[b]}if(!c.support.style&&
e&&b==="style"){if(f)a.style.cssText=""+d;return a.style.cssText}f&&a.setAttribute(b,""+d);if(!a.attributes[b]&&a.hasAttribute&&!a.hasAttribute(b))return I;a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b);return a===null?I:a}});var ra=/\.(.*)$/,Na=/^(?:textarea|input|select)$/i,oa=/\./g,jb=/ /g,Oa=/[^\w\s.|`]/g,va=function(a){return a.replace(Oa,"\\$&")},Pa={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(c.isWindow(a)&&a!==R&&!a.frameElement)a=
R;if(d===false)d=xa;else if(!d)return;var f,h;if(d.handler){f=d;d=f.handler}if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var m=a.nodeType?"events":"__events__",l=h[m],p=h.handle;if(typeof l==="function"){p=l.handle;l=l.events}else if(!l){a.nodeType||(h[m]=h=function(){});h.events=l={}}if(!p)h.handle=p=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(p.elem,arguments):I};p.elem=a;b=b.split(" ");for(var A=0,v;m=b[A++];){h=f?c.extend({},f):{handler:d,data:e};if(m.indexOf(".")>
-1){v=m.split(".");m=v.shift();h.namespace=v.slice(0).sort().join(".")}else{v=[];h.namespace=""}h.type=m;if(!h.guid)h.guid=d.guid;var G=l[m],O=c.event.special[m]||{};if(!G){G=l[m]=[];if(!O.setup||O.setup.call(a,e,v,p)===false)if(a.addEventListener)a.addEventListener(m,p,false);else a.attachEvent&&a.attachEvent("on"+m,p)}if(O.add){O.add.call(a,h);if(!h.handler.guid)h.handler.guid=d.guid}G.push(h);c.event.global[m]=true}a=null}}},global:{},remove:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===
8)){if(d===false)d=xa;var f,h,m=0,l,p,A,v,G,O,Z=a.nodeType?"events":"__events__",B=c.data(a),X=B&&B[Z];if(B&&X){if(typeof X==="function"){B=X;X=X.events}if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(f in X)c.event.remove(a,f+b)}else{for(b=b.split(" ");f=b[m++];){v=f;l=f.indexOf(".")<0;p=[];if(!l){p=f.split(".");f=p.shift();A=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),va).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(G=X[f])if(d){v=c.event.special[f]||{};for(h=
e||0;h<G.length;h++){O=G[h];if(d.guid===O.guid){if(l||A.test(O.namespace)){e==null&&G.splice(h--,1);v.remove&&v.remove.call(a,O)}if(e!=null)break}}if(G.length===0||e!=null&&G.length===1){if(!v.teardown||v.teardown.call(a,p)===false)c.removeEvent(a,f,B.handle);delete X[f]}}else for(h=0;h<G.length;h++){O=G[h];if(l||A.test(O.namespace)){c.event.remove(a,v,O.handler,h);G.splice(h--,1)}}}if(c.isEmptyObject(X)){if(b=B.handle)b.elem=null;delete B.events;delete B.handle;if(typeof B==="function")c.removeData(a,
Z);else c.isEmptyObject(B)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var f=a.type||a;if(!e){a=typeof a==="object"?a[c.expando]?a:c.extend(c.Event(f),a):c.Event(f);if(f.indexOf("!")>=0){a.type=f=f.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[f]&&c.each(c.cache,function(){this.events&&this.events[f]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return I;a.result=I;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(e=d.nodeType?
c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+f]&&d["on"+f].apply(d,b)===false){a.result=false;a.preventDefault()}}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,true);else if(!a.isDefaultPrevented()){var m;e=a.target;var l=f.replace(ra,""),p=c.nodeName(e,"a")&&l==="click",A=c.event.special[l]||{};if((!A._default||A._default.call(d,a)===false)&&!p&&!(e&&e.nodeName&&
c.noData[e.nodeName.toLowerCase()])){try{if(e[l]){if(m=e["on"+l])e["on"+l]=null;c.event.triggered=true;e[l]()}}catch(v){}if(m)e["on"+l]=m;c.event.triggered=false}}},handle:function(a){var b,d,e,f;d=[];var h=c.makeArray(arguments);a=h[0]=c.event.fix(a||R.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){e=a.type.split(".");a.type=e.shift();d=e.slice(0).sort();e=new RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)")}a.namespace=a.namespace||d.join(".");f=c.data(this,this.nodeType?
"events":"__events__");if(typeof f==="function")f=f.events;d=(f||{})[a.type];if(f&&d){d=d.slice(0);f=0;for(var m=d.length;f<m;f++){var l=d[f];if(b||e.test(l.namespace)){a.handler=l.handler;a.data=l.data;a.handleObj=l;l=l.handler.apply(this,h);if(l!==I){a.result=l;if(l===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;var b=a;a=c.Event(b);for(var d=this.props.length,e;d;){e=this.props[--d];a[e]=b[e]}if(!a.target)a.target=a.srcElement||w;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=w.documentElement;d=w.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==I)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,Ka(a.origType,a.selector),c.extend({},a,{handler:pb,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
Ka(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=w.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=a;this.timeStamp=
c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=Ra;var a=this.originalEvent;if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=Ra;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=Ra;this.stopPropagation()},isDefaultPrevented:xa,isPropagationStopped:xa,isImmediatePropagationStopped:xa};
var $a=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},sa=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?sa:$a,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?sa:$a)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length){a.liveFired=I;return ib("submit",this,arguments)}});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13){a.liveFired=I;return ib("submit",this,arguments)}})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var y,
D=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(e){return e.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},K=function(a,b){var d=a.target,e,f;if(!(!Na.test(d.nodeName)||d.readOnly)){e=c.data(d,"_change_data");f=D(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",f);if(!(e===I||f===e))if(e!=null||f){a.type="change";a.liveFired=
I;return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:K,beforedeactivate:K,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return K.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return K.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",D(a))}},setup:function(){if(this.type===
"file")return false;for(var a in y)c.event.add(this,a+".specialChange",y[a]);return Na.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return Na.test(this.nodeName)}};y=c.event.special.change.filters;y.focus=y.beforeactivate}w.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.trigger(e,null,e.target)}c.event.special[b]={setup:function(){Pa[b]++===0&&w.addEventListener(a,d,true)},teardown:function(){--Pa[b]===
0&&w.removeEventListener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,e,f){if(typeof d==="object"){for(var h in d)this[b](h,e,d[h],f);return this}if(c.isFunction(e)||e===false){f=e;e=I}var m=b==="one"?c.proxy(f,function(p){c(this).unbind(p,m);return f.apply(this,arguments)}):f;if(d==="unload"&&b!=="one")this.one(d,e,f);else{h=0;for(var l=this.length;h<l;h++)c.event.add(this[h],d,m,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,
a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,e){return this.live(b,d,e,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<
b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var f=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,f+1);e.preventDefault();return b[f].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var L={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,e,f,h){var m,l=0,p,A,v=h||this.selector;h=h?this:c(this.context);if(typeof d==="object"&&
!d.preventDefault){for(m in d)h[b](m,e,d[m],v);return this}if(c.isFunction(e)){f=e;e=I}for(d=(d||"").split(" ");(m=d[l++])!=null;){p=ra.exec(m);A="";if(p){A=p[0];m=m.replace(ra,"")}if(m==="hover")d.push("mouseenter"+A,"mouseleave"+A);else{p=m;if(m==="focus"||m==="blur"){d.push(L[m]+A);m+=A}else m=(L[m]||m)+A;if(b==="live"){A=0;for(var G=h.length;A<G;A++)c.event.add(h[A],"live."+Ka(m,v),{data:e,selector:v,handler:f,origType:m,origHandler:f,preType:p})}else h.unbind("live."+Ka(m,v),f)}}return this}});
c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(d,e){if(e==null){e=d;d=null}return arguments.length>0?this.bind(b,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});R.attachEvent&&!R.addEventListener&&c(R).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});
(function(){function a(g,i,n,q,r,u){r=0;for(var C=q.length;r<C;r++){var H=q[r];if(H){var T=false;for(H=H[g];H;){if(H.sizcache===n){T=q[H.sizset];break}if(H.nodeType===1&&!u){H.sizcache=n;H.sizset=r}if(H.nodeName.toLowerCase()===i){T=H;break}H=H[g]}q[r]=T}}}function b(g,i,n,q,r,u){r=0;for(var C=q.length;r<C;r++){var H=q[r];if(H){var T=false;for(H=H[g];H;){if(H.sizcache===n){T=q[H.sizset];break}if(H.nodeType===1){if(!u){H.sizcache=n;H.sizset=r}if(typeof i!=="string"){if(H===i){T=true;break}}else if(l.filter(i,
[H]).length>0){T=H;break}}H=H[g]}q[r]=T}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,f=Object.prototype.toString,h=false,m=true;[0,0].sort(function(){m=false;return 0});var l=function(g,i,n,q){n=n||[];var r=i=i||w;if(i.nodeType!==1&&i.nodeType!==9)return[];if(!g||typeof g!=="string")return n;var u,C,H,T,ha,ka=true,la=l.isXML(i),S=[],Ea=g;do{d.exec("");if(u=d.exec(Ea)){Ea=u[3];S.push(u[1]);if(u[2]){T=
u[3];break}}}while(u);if(S.length>1&&A.exec(g))if(S.length===2&&p.relative[S[0]])C=ja(S[0]+S[1],i);else for(C=p.relative[S[0]]?[i]:l(S.shift(),i);S.length;){g=S.shift();if(p.relative[g])g+=S.shift();C=ja(g,C)}else{if(!q&&S.length>1&&i.nodeType===9&&!la&&p.match.ID.test(S[0])&&!p.match.ID.test(S[S.length-1])){u=l.find(S.shift(),i,la);i=u.expr?l.filter(u.expr,u.set)[0]:u.set[0]}if(i){u=q?{expr:S.pop(),set:O(q)}:l.find(S.pop(),S.length===1&&(S[0]==="~"||S[0]==="+")&&i.parentNode?i.parentNode:i,la);C=
u.expr?l.filter(u.expr,u.set):u.set;if(S.length>0)H=O(C);else ka=false;for(;S.length;){u=ha=S.pop();if(p.relative[ha])u=S.pop();else ha="";if(u==null)u=i;p.relative[ha](H,u,la)}}else H=[]}H||(H=C);H||l.error(ha||g);if(f.call(H)==="[object Array]")if(ka)if(i&&i.nodeType===1)for(g=0;H[g]!=null;g++){if(H[g]&&(H[g]===true||H[g].nodeType===1&&l.contains(i,H[g])))n.push(C[g])}else for(g=0;H[g]!=null;g++)H[g]&&H[g].nodeType===1&&n.push(C[g]);else n.push.apply(n,H);else O(H,n);if(T){l(T,r,n,q);l.uniqueSort(n)}return n};
l.uniqueSort=function(g){if(B){h=m;g.sort(B);if(h)for(var i=1;i<g.length;i++)g[i]===g[i-1]&&g.splice(i--,1)}return g};l.matches=function(g,i){return l(g,null,null,i)};l.matchesSelector=function(g,i){return l(i,null,null,[g]).length>0};l.find=function(g,i,n){var q;if(!g)return[];for(var r=0,u=p.order.length;r<u;r++){var C,H=p.order[r];if(C=p.leftMatch[H].exec(g)){var T=C[1];C.splice(1,1);if(T.substr(T.length-1)!=="\\"){C[1]=(C[1]||"").replace(/\\/g,"");q=p.find[H](C,i,n);if(q!=null){g=g.replace(p.match[H],
"");break}}}}q||(q=i.getElementsByTagName("*"));return{set:q,expr:g}};l.filter=function(g,i,n,q){for(var r,u,C=g,H=[],T=i,ha=i&&i[0]&&l.isXML(i[0]);g&&i.length;){for(var ka in p.filter)if((r=p.leftMatch[ka].exec(g))!=null&&r[2]){var la,S,Ea=p.filter[ka];S=r[1];u=false;r.splice(1,1);if(S.substr(S.length-1)!=="\\"){if(T===H)H=[];if(p.preFilter[ka])if(r=p.preFilter[ka](r,T,n,H,q,ha)){if(r===true)continue}else u=la=true;if(r)for(var j=0;(S=T[j])!=null;j++)if(S){la=Ea(S,r,j,T);var t=q^!!la;if(n&&la!=null)if(t)u=
true;else T[j]=false;else if(t){H.push(S);u=true}}if(la!==I){n||(T=H);g=g.replace(p.match[ka],"");if(!u)return[];break}}}if(g===C)if(u==null)l.error(g);else break;C=g}return T};l.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var p=l.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,i){var n=typeof i==="string",q=n&&!/\W/.test(i);n=n&&!q;if(q)i=i.toLowerCase();q=0;for(var r=g.length,
u;q<r;q++)if(u=g[q]){for(;(u=u.previousSibling)&&u.nodeType!==1;);g[q]=n||u&&u.nodeName.toLowerCase()===i?u||false:u===i}n&&l.filter(i,g,true)},">":function(g,i){var n,q=typeof i==="string",r=0,u=g.length;if(q&&!/\W/.test(i))for(i=i.toLowerCase();r<u;r++){if(n=g[r]){n=n.parentNode;g[r]=n.nodeName.toLowerCase()===i?n:false}}else{for(;r<u;r++)if(n=g[r])g[r]=q?n.parentNode:n.parentNode===i;q&&l.filter(i,g,true)}},"":function(g,i,n){var q,r=e++,u=b;if(typeof i==="string"&&!/\W/.test(i)){q=i=i.toLowerCase();
u=a}u("parentNode",i,r,g,q,n)},"~":function(g,i,n){var q,r=e++,u=b;if(typeof i==="string"&&!/\W/.test(i)){q=i=i.toLowerCase();u=a}u("previousSibling",i,r,g,q,n)}},find:{ID:function(g,i,n){if(typeof i.getElementById!=="undefined"&&!n)return(g=i.getElementById(g[1]))&&g.parentNode?[g]:[]},NAME:function(g,i){if(typeof i.getElementsByName!=="undefined"){var n=[];i=i.getElementsByName(g[1]);for(var q=0,r=i.length;q<r;q++)i[q].getAttribute("name")===g[1]&&n.push(i[q]);return n.length===0?null:n}},TAG:function(g,
i){return i.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,i,n,q,r,u){g=" "+g[1].replace(/\\/g,"")+" ";if(u)return g;u=0;for(var C;(C=i[u])!=null;u++)if(C)if(r^(C.className&&(" "+C.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))n||q.push(C);else if(n)i[u]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var i=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&
"0n+"+g[2]||g[2]);g[2]=i[1]+(i[2]||1)-0;g[3]=i[3]-0}g[0]=e++;return g},ATTR:function(g,i,n,q,r,u){i=g[1].replace(/\\/g,"");if(!u&&p.attrMap[i])g[1]=p.attrMap[i];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,i,n,q,r){if(g[1]==="not")if((d.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=l(g[3],null,null,i);else{g=l.filter(g[3],i,n,true^r);n||q.push.apply(q,g);return false}else if(p.match.POS.test(g[0])||p.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},
filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},has:function(g,i,n){return!!l(n[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===
g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,i){return i===0},last:function(g,i,n,q){return i===q.length-1},even:function(g,i){return i%2===
0},odd:function(g,i){return i%2===1},lt:function(g,i,n){return i<n[3]-0},gt:function(g,i,n){return i>n[3]-0},nth:function(g,i,n){return n[3]-0===i},eq:function(g,i,n){return n[3]-0===i}},filter:{PSEUDO:function(g,i,n,q){var r=i[1],u=p.filters[r];if(u)return u(g,n,i,q);else if(r==="contains")return(g.textContent||g.innerText||l.getText([g])||"").indexOf(i[3])>=0;else if(r==="not"){i=i[3];n=0;for(q=i.length;n<q;n++)if(i[n]===g)return false;return true}else l.error("Syntax error, unrecognized expression: "+
r)},CHILD:function(g,i){var n=i[1],q=g;switch(n){case "only":case "first":for(;q=q.previousSibling;)if(q.nodeType===1)return false;if(n==="first")return true;q=g;case "last":for(;q=q.nextSibling;)if(q.nodeType===1)return false;return true;case "nth":n=i[2];var r=i[3];if(n===1&&r===0)return true;i=i[0];var u=g.parentNode;if(u&&(u.sizcache!==i||!g.nodeIndex)){var C=0;for(q=u.firstChild;q;q=q.nextSibling)if(q.nodeType===1)q.nodeIndex=++C;u.sizcache=i}g=g.nodeIndex-r;return n===0?g===0:g%n===0&&g/n>=
0}},ID:function(g,i){return g.nodeType===1&&g.getAttribute("id")===i},TAG:function(g,i){return i==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===i},CLASS:function(g,i){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(i)>-1},ATTR:function(g,i){var n=i[1];g=p.attrHandle[n]?p.attrHandle[n](g):g[n]!=null?g[n]:g.getAttribute(n);n=g+"";var q=i[2];i=i[4];return g==null?q==="!=":q==="="?n===i:q==="*="?n.indexOf(i)>=0:q==="~="?(" "+n+" ").indexOf(i)>=0:!i?n&&g!==false:q==="!="?n!==i:q==="^="?
n.indexOf(i)===0:q==="$="?n.substr(n.length-i.length)===i:q==="|="?n===i||n.substr(0,i.length+1)===i+"-":false},POS:function(g,i,n,q){var r=p.setFilters[i[2]];if(r)return r(g,n,i,q)}}},A=p.match.POS,v=function(g,i){return"\\"+(i-0+1)};for(var G in p.match){p.match[G]=new RegExp(p.match[G].source+/(?![^\[]*\])(?![^\(]*\))/.source);p.leftMatch[G]=new RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[G].source.replace(/\\(\d+)/g,v))}var O=function(g,i){g=Array.prototype.slice.call(g,0);if(i){i.push.apply(i,g);
return i}return g};try{Array.prototype.slice.call(w.documentElement.childNodes,0)}catch(Z){O=function(g,i){var n=0;i=i||[];if(f.call(g)==="[object Array]")Array.prototype.push.apply(i,g);else if(typeof g.length==="number")for(var q=g.length;n<q;n++)i.push(g[n]);else for(;g[n];n++)i.push(g[n]);return i}}var B,X;if(w.documentElement.compareDocumentPosition)B=function(g,i){if(g===i){h=true;return 0}if(!g.compareDocumentPosition||!i.compareDocumentPosition)return g.compareDocumentPosition?-1:1;return g.compareDocumentPosition(i)&
4?-1:1};else{B=function(g,i){var n,q,r=[],u=[];n=g.parentNode;q=i.parentNode;var C=n;if(g===i){h=true;return 0}else if(n===q)return X(g,i);else if(n){if(!q)return 1}else return-1;for(;C;){r.unshift(C);C=C.parentNode}for(C=q;C;){u.unshift(C);C=C.parentNode}n=r.length;q=u.length;for(C=0;C<n&&C<q;C++)if(r[C]!==u[C])return X(r[C],u[C]);return C===n?X(g,u[C],-1):X(r[C],i,1)};X=function(g,i,n){if(g===i)return n;for(g=g.nextSibling;g;){if(g===i)return-1;g=g.nextSibling}return 1}}l.getText=function(g){for(var i=
"",n,q=0;g[q];q++){n=g[q];if(n.nodeType===3||n.nodeType===4)i+=n.nodeValue;else if(n.nodeType!==8)i+=l.getText(n.childNodes)}return i};(function(){var g=w.createElement("div"),i="script"+(new Date).getTime(),n=w.documentElement;g.innerHTML="<a name='"+i+"'/>";n.insertBefore(g,n.firstChild);if(w.getElementById(i)){p.find.ID=function(q,r,u){if(typeof r.getElementById!=="undefined"&&!u)return(r=r.getElementById(q[1]))?r.id===q[1]||typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id").nodeValue===
q[1]?[r]:I:[]};p.filter.ID=function(q,r){var u=typeof q.getAttributeNode!=="undefined"&&q.getAttributeNode("id");return q.nodeType===1&&u&&u.nodeValue===r}}n.removeChild(g);n=g=null})();(function(){var g=w.createElement("div");g.appendChild(w.createComment(""));if(g.getElementsByTagName("*").length>0)p.find.TAG=function(i,n){n=n.getElementsByTagName(i[1]);if(i[1]==="*"){i=[];for(var q=0;n[q];q++)n[q].nodeType===1&&i.push(n[q]);n=i}return n};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!==
"undefined"&&g.firstChild.getAttribute("href")!=="#")p.attrHandle.href=function(i){return i.getAttribute("href",2)};g=null})();w.querySelectorAll&&function(){var g=l,i=w.createElement("div");i.innerHTML="<p class='TEST'></p>";if(!(i.querySelectorAll&&i.querySelectorAll(".TEST").length===0)){l=function(q,r,u,C){r=r||w;q=q.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!C&&!l.isXML(r))if(r.nodeType===9)try{return O(r.querySelectorAll(q),u)}catch(H){}else if(r.nodeType===1&&r.nodeName.toLowerCase()!==
"object"){var T=r.getAttribute("id"),ha=T||"__sizzle__";T||r.setAttribute("id",ha);try{return O(r.querySelectorAll("#"+ha+" "+q),u)}catch(ka){}finally{T||r.removeAttribute("id")}}return g(q,r,u,C)};for(var n in g)l[n]=g[n];i=null}}();(function(){var g=w.documentElement,i=g.matchesSelector||g.mozMatchesSelector||g.webkitMatchesSelector||g.msMatchesSelector,n=false;try{i.call(w.documentElement,"[test!='']:sizzle")}catch(q){n=true}if(i)l.matchesSelector=function(r,u){u=u.replace(/\=\s*([^'"\]]*)\s*\]/g,
"='$1']");if(!l.isXML(r))try{if(n||!p.match.PSEUDO.test(u)&&!/!=/.test(u))return i.call(r,u)}catch(C){}return l(u,null,null,[r]).length>0}})();(function(){var g=w.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){p.order.splice(1,0,"CLASS");p.find.CLASS=function(i,n,q){if(typeof n.getElementsByClassName!=="undefined"&&
!q)return n.getElementsByClassName(i[1])};g=null}}})();l.contains=w.documentElement.contains?function(g,i){return g!==i&&(g.contains?g.contains(i):true)}:w.documentElement.compareDocumentPosition?function(g,i){return!!(g.compareDocumentPosition(i)&16)}:function(){return false};l.isXML=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false};var ja=function(g,i){var n,q=[],r="";for(i=i.nodeType?[i]:i;n=p.match.PSEUDO.exec(g);){r+=n[0];g=g.replace(p.match.PSEUDO,"")}g=
p.relative[g]?g+"*":g;n=0;for(var u=i.length;n<u;n++)l(g,i[n],q);return l.filter(r,q)};c.find=l;c.expr=l.selectors;c.expr[":"]=c.expr.filters;c.unique=l.uniqueSort;c.text=l.getText;c.isXMLDoc=l.isXML;c.contains=l.contains})();var aa=/Until$/,P=/^(?:parents|prevUntil|prevAll)/,Ga=/,/,cb=/^.[^:#\[\.,]*$/,lb=Array.prototype.slice,db=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=this.pushStack("","find",a),d=0,e=0,f=this.length;e<f;e++){d=b.length;c.find(a,this[e],b);if(e>0)for(var h=d;h<b.length;h++)for(var m=
0;m<d;m++)if(b[m]===b[h]){b.splice(h--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Qa(this,a,false),"not",a)},filter:function(a){return this.pushStack(Qa(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,b){var d=[],e,f,h=this[0];if(c.isArray(a)){var m,l={},p=1;if(h&&a.length){e=0;for(f=a.length;e<f;e++){m=a[e];
l[m]||(l[m]=c.expr.match.POS.test(m)?c(m,b||this.context):m)}for(;h&&h.ownerDocument&&h!==b;){for(m in l){a=l[m];if(a.jquery?a.index(h)>-1:c(h).is(a))d.push({selector:m,elem:h,level:p})}h=h.parentNode;p++}}return d}m=db.test(a)?c(a,b||this.context):null;e=0;for(f=this.length;e<f;e++)for(h=this[e];h;)if(m?m.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===b)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a||
typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(ab(a[0])||ab(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",
d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?
a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);aa.test(a)||(e=d);if(e&&typeof e==="string")f=c.filter(e,f);f=this.length>1?c.unique(f):f;if((this.length>1||Ga.test(e))&&P.test(a))f=f.reverse();return this.pushStack(f,a,lb.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=
a[b];a&&a.nodeType!==9&&(d===I||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Ia=/ jQuery\d+="(?:\d+|null)"/g,Ca=/^\s+/,ya=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Va=/<([\w:]+)/,gb=/<tbody/i,Wa=/<|&#?\w+;/,Xa=/<(?:script|object|embed|option|style)/i,
hb=/checked\s*(?:[^=]|=\s*.checked.)/i,J=/\=([^="'>\s]+\/)>/g,ca={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};ca.optgroup=ca.option;ca.tbody=ca.tfoot=ca.colgroup=ca.caption=ca.thead;ca.th=ca.td;if(!c.support.htmlSerialize)ca._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==I)return this.empty().append((this[0]&&this[0].ownerDocument||w).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===1){c.cleanData(e.getElementsByTagName("*"));c.cleanData([e])}e.parentNode&&e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,e=this.ownerDocument;if(!d){d=e.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Ia,"").replace(J,'="$1">').replace(Ca,"")],e)[0]}else return this.cloneNode(true)});if(a===true){bb(this,b);bb(this.find("*"),b.find("*"))}return b},html:function(a){if(a===I)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Ia,""):null;
else if(typeof a==="string"&&!Xa.test(a)&&(c.support.leadingWhitespace||!Ca.test(a))&&!ca[(Va.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(ya,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(e){this.empty().append(a)}}else c.isFunction(a)?this.each(function(f){var h=c(this);h.html(a.call(this,f,h.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=
c(this),e=d.html();d.replaceWith(a.call(this,b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){var e,f,h,m=a[0],l=[];if(!c.support.checkClone&&arguments.length===3&&typeof m==="string"&&hb.test(m))return this.each(function(){c(this).domManip(a,
b,d,true)});if(c.isFunction(m))return this.each(function(v){var G=c(this);a[0]=m.call(this,v,b?G.html():I);G.domManip(a,b,d)});if(this[0]){e=m&&m.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,l);h=e.fragment;if(f=h.childNodes.length===1?(h=h.firstChild):h.firstChild){b=b&&c.nodeName(f,"tr");for(var p=0,A=this.length;p<A;p++)d.call(b?fa(this[p],f):this[p],p>0||e.cacheable||this.length>1?h.cloneNode(true):h)}l.length&&c.each(l,
ob)}return this}});c.buildFragment=function(a,b,d){var e,f,h;b=b&&b[0]?b[0].ownerDocument||b[0]:w;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===w&&!Xa.test(a[0])&&(c.support.checkClone||!hb.test(a[0]))){f=true;if(h=c.fragments[a[0]])if(h!==1)e=h}if(!e){e=b.createDocumentFragment();c.clean(a,b,e,d)}if(f)c.fragments[a[0]]=h?e:1;return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},
function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{f=0;for(var h=d.length;f<h;f++){var m=(f>0?this.clone(true):this).get();c(d[f])[b](m);e=e.concat(m)}return this.pushStack(e,a,d.selector)}}});c.extend({clean:function(a,b,d,e){b=b||w;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||w;for(var f=[],h=0,m;(m=a[h])!=null;h++){if(typeof m===
"number")m+="";if(m){if(typeof m==="string"&&!Wa.test(m))m=b.createTextNode(m);else if(typeof m==="string"){m=m.replace(ya,"<$1></$2>");var l=(Va.exec(m)||["",""])[1].toLowerCase(),p=ca[l]||ca._default,A=p[0],v=b.createElement("div");for(v.innerHTML=p[1]+m+p[2];A--;)v=v.lastChild;if(!c.support.tbody){A=gb.test(m);l=l==="table"&&!A?v.firstChild&&v.firstChild.childNodes:p[1]==="<table>"&&!A?v.childNodes:[];for(p=l.length-1;p>=0;--p)c.nodeName(l[p],"tbody")&&!l[p].childNodes.length&&l[p].parentNode.removeChild(l[p])}!c.support.leadingWhitespace&&
Ca.test(m)&&v.insertBefore(b.createTextNode(Ca.exec(m)[0]),v.firstChild);m=v.childNodes}if(m.nodeType)f.push(m);else f=c.merge(f,m)}}if(d)for(h=0;f[h];h++)if(e&&c.nodeName(f[h],"script")&&(!f[h].type||f[h].type.toLowerCase()==="text/javascript"))e.push(f[h].parentNode?f[h].parentNode.removeChild(f[h]):f[h]);else{f[h].nodeType===1&&f.splice.apply(f,[h+1,0].concat(c.makeArray(f[h].getElementsByTagName("script"))));d.appendChild(f[h])}return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,
h=c.support.deleteExpando,m=0,l;(l=a[m])!=null;m++)if(!(l.nodeName&&c.noData[l.nodeName.toLowerCase()]))if(d=l[c.expando]){if((b=e[d])&&b.events)for(var p in b.events)f[p]?c.event.remove(l,p):c.removeEvent(l,p,b.handle);if(h)delete l[c.expando];else l.removeAttribute&&l.removeAttribute(c.expando);delete e[d]}}});var da=/alpha\([^)]*\)/i,Da=/opacity=([^)]*)/,Ba=/-([a-z])/ig,Ta=/([A-Z])/g,Y=/^-?\d+(?:px)?$/i,ia=/^-?\d/,ua={position:"absolute",visibility:"hidden",display:"block"},Ua=["Left","Right"],
mb=["Top","Bottom"],ea,ta,qa,Ha=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===I)return this;return c.access(this,a,b,true,function(d,e,f){return f!==I?c.style(d,e,f):c.css(d,e)})};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){a=ea(a,"opacity","opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,
b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var f,h=c.camelCase(b),m=a.style,l=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==I){if(!(typeof d==="number"&&isNaN(d)||d==null)){if(typeof d==="number"&&!c.cssNumber[h])d+="px";if(!l||!("set"in l)||(d=l.set(a,d))!==I)try{m[b]=d}catch(p){}}}else{if(l&&"get"in l&&(f=l.get(a,false,e))!==I)return f;return m[b]}}},css:function(a,b,d){var e,f=c.camelCase(b),h=c.cssHooks[f];b=c.cssProps[f]||f;if(h&&"get"in h&&(e=h.get(a,true,d))!==I)return e;else if(ea)return ea(a,
b,f)},swap:function(a,b,d){var e={};for(var f in b){e[f]=a.style[f];a.style[f]=b[f]}d.call(a);for(f in b)a.style[f]=e[f]},camelCase:function(a){return a.replace(Ba,Ha)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){var h;if(e){if(d.offsetWidth!==0)h=na(d,b,f);else c.swap(d,ua,function(){h=na(d,b,f)});if(h<=0){h=ea(d,b,b);if(h==="0px"&&qa)h=qa(d,b,b);if(h!=null)return h===""||h==="auto"?"0px":h}if(h<0||h==null){h=d.style[b];return h===""||h==="auto"?"0px":
h}return typeof h==="string"?h:h+"px"}},set:function(d,e){if(Y.test(e)){e=parseFloat(e);if(e>=0)return e+"px"}else return e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return Da.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){a=a.style;a.zoom=1;b=c.isNaN(b)?"":"alpha(opacity="+b*100+")";var d=a.filter||"";a.filter=da.test(d)?d.replace(da,b):a.filter+" "+b}};if(w.defaultView&&w.defaultView.getComputedStyle)ta=
function(a,b,d){var e;d=d.replace(Ta,"-$1").toLowerCase();if(!(b=a.ownerDocument.defaultView))return I;if(b=b.getComputedStyle(a,null)){e=b.getPropertyValue(d);if(e===""&&!c.contains(a.ownerDocument.documentElement,a))e=c.style(a,d)}return e};if(w.documentElement.currentStyle)qa=function(a,b){var d,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;if(!Y.test(f)&&ia.test(f)){d=h.left;e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=b==="fontSize"?"1em":f||0;f=h.pixelLeft+"px";h.left=
d;a.runtimeStyle.left=e}return f===""?"auto":f};ea=ta||qa;if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var k=c.now(),o=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,s=/^(?:select|textarea)/i,x=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
E=/^(?:GET|HEAD)$/,Q=/\[\]$/,M=/\=\?(&|$)/,V=/\?/,ba=/([?&])_=[^&]*/,fb=/^(\w+:)?\/\/([^\/?#]+)/,nb=/%20/g,wb=/#.*$/,ub=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&ub)return ub.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var f=a.slice(e,a.length);a=a.slice(0,e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",data:b,
complete:function(m,l){if(l==="success"||l==="notmodified")h.html(f?c("<div>").append(m.responseText.replace(o,"")).find(f):m.responseText);d&&h.each(d,[m.responseText,l,m])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||s.test(this.nodeName)||x.test(this.type))}).map(function(a,b){a=c(this).val();
return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,e){if(c.isFunction(b)){e=e||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,
b,d,e){if(c.isFunction(b)){e=e||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:function(){return new R.XMLHttpRequest},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},
ajax:function(a){var b=c.extend(true,{},c.ajaxSettings,a),d,e,f,h=b.type.toUpperCase(),m=E.test(h);b.url=b.url.replace(wb,"");b.context=a&&a.context!=null?a.context:b;if(b.data&&b.processData&&typeof b.data!=="string")b.data=c.param(b.data,b.traditional);if(b.dataType==="jsonp"){if(h==="GET")M.test(b.url)||(b.url+=(V.test(b.url)?"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!M.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if(b.dataType==="json"&&(b.data&&
M.test(b.data)||M.test(b.url))){d=b.jsonpCallback||"jsonp"+k++;if(b.data)b.data=(b.data+"").replace(M,"="+d+"$1");b.url=b.url.replace(M,"="+d+"$1");b.dataType="script";var l=R[d];R[d]=function(q){if(c.isFunction(l))l(q);else{R[d]=I;try{delete R[d]}catch(r){}}f=q;c.handleSuccess(b,B,e,f);c.handleComplete(b,B,e,f);v&&v.removeChild(G)}}if(b.dataType==="script"&&b.cache===null)b.cache=false;if(b.cache===false&&m){var p=c.now(),A=b.url.replace(ba,"$1_="+p);b.url=A+(A===b.url?(V.test(b.url)?"&":"?")+"_="+
p:"")}if(b.data&&m)b.url+=(V.test(b.url)?"&":"?")+b.data;b.global&&c.active++===0&&c.event.trigger("ajaxStart");p=(p=fb.exec(b.url))&&(p[1]&&p[1].toLowerCase()!==location.protocol||p[2].toLowerCase()!==location.host);if(b.dataType==="script"&&h==="GET"&&p){var v=w.getElementsByTagName("head")[0]||w.documentElement,G=w.createElement("script");if(b.scriptCharset)G.charset=b.scriptCharset;G.src=b.url;if(!d){var O=false;G.onload=G.onreadystatechange=function(){if(!O&&(!this.readyState||this.readyState===
"loaded"||this.readyState==="complete")){O=true;c.handleSuccess(b,B,e,f);c.handleComplete(b,B,e,f);G.onload=G.onreadystatechange=null;v&&G.parentNode&&v.removeChild(G)}}}v.insertBefore(G,v.firstChild);return I}var Z=false,B=b.xhr();if(B){b.username?B.open(h,b.url,b.async,b.username,b.password):B.open(h,b.url,b.async);try{if(b.data!=null&&!m||a&&a.contentType)B.setRequestHeader("Content-Type",b.contentType);if(b.ifModified){c.lastModified[b.url]&&B.setRequestHeader("If-Modified-Since",c.lastModified[b.url]);
c.etag[b.url]&&B.setRequestHeader("If-None-Match",c.etag[b.url])}p||B.setRequestHeader("X-Requested-With","XMLHttpRequest");B.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(X){}if(b.beforeSend&&b.beforeSend.call(b.context,B,b)===false){b.global&&c.active--===1&&c.event.trigger("ajaxStop");B.abort();return false}b.global&&c.triggerGlobal(b,"ajaxSend",[B,b]);var ja=B.onreadystatechange=function(q){if(!B||B.readyState===0||
q==="abort"){Z||c.handleComplete(b,B,e,f);Z=true;if(B)B.onreadystatechange=c.noop}else if(!Z&&B&&(B.readyState===4||q==="timeout")){Z=true;B.onreadystatechange=c.noop;e=q==="timeout"?"timeout":!c.httpSuccess(B)?"error":b.ifModified&&c.httpNotModified(B,b.url)?"notmodified":"success";var r;if(e==="success")try{f=c.httpData(B,b.dataType,b)}catch(u){e="parsererror";r=u}if(e==="success"||e==="notmodified")d||c.handleSuccess(b,B,e,f);else c.handleError(b,B,e,r);d||c.handleComplete(b,B,e,f);q==="timeout"&&
B.abort();if(b.async)B=null}};try{var g=B.abort;B.abort=function(){B&&Function.prototype.call.call(g,B);ja("abort")}}catch(i){}b.async&&b.timeout>0&&setTimeout(function(){B&&!Z&&ja("timeout")},b.timeout);try{B.send(m||b.data==null?null:b.data)}catch(n){c.handleError(b,B,null,n);c.handleComplete(b,B,e,f)}b.async||ja();return B}},param:function(a,b){var d=[],e=function(h,m){m=c.isFunction(m)?m():m;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(m)};if(b===I)b=c.ajaxSettings.traditional;if(c.isArray(a)||
a.jquery)c.each(a,function(){e(this.name,this.value)});else for(var f in a)Ja(f,a[f],b,e);return d.join("&").replace(nb,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,b,d);a.global&&c.triggerGlobal(a,
"ajaxComplete",[b,a]);a.global&&c.active--===1&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&a.context.url==null?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(e)c.etag[b]=e;return a.status===304},
httpData:function(a,b,d){var e=a.getResponseHeader("content-type")||"",f=b==="xml"||!b&&e.indexOf("xml")>=0;a=f?a.responseXML:a.responseText;f&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&e.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&e.indexOf("javascript")>=0)c.globalEval(a);return a}});if(R.ActiveXObject)c.ajaxSettings.xhr=function(){if(R.location.protocol!=="file:")try{return new R.XMLHttpRequest}catch(a){}try{return new R.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};
c.support.ajax=!!c.ajaxSettings.xhr();var rb={},xb=/^(?:toggle|show|hide)$/,yb=/^([+\-]=)?([\d+.\-]+)(.*)$/,kb,tb=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(Aa("show",3),a,b,d);else{d=0;for(var e=this.length;d<e;d++){a=this[d];b=a.style.display;if(!c.data(a,"olddisplay")&&b==="none")b=a.style.display="";b===""&&c.css(a,"display")===
"none"&&c.data(a,"olddisplay",eb(a.nodeName))}for(d=0;d<e;d++){a=this[d];b=a.style.display;if(b===""||b==="none")a.style.display=c.data(a,"olddisplay")||""}return this}},hide:function(a,b,d){if(a||a===0)return this.animate(Aa("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){d=c.css(this[a],"display");d!=="none"&&c.data(this[a],"olddisplay",d)}for(a=0;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,
arguments);else a==null||e?this.each(function(){var f=e?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(Aa("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var f=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(f.complete);return this[f.queue===false?"each":"queue"](function(){var h=c.extend({},f),m,l=this.nodeType===1,p=l&&c(this).is(":hidden"),A=this;for(m in a){var v=
c.camelCase(m);if(m!==v){a[v]=a[m];delete a[m];m=v}if(a[m]==="hide"&&p||a[m]==="show"&&!p)return h.complete.call(this);if(l&&(m==="height"||m==="width")){h.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(c.support.inlineBlockNeedsLayout)if(eb(this.nodeName)==="inline")this.style.display="inline-block";else{this.style.display="inline";this.style.zoom=1}else this.style.display="inline-block"}if(c.isArray(a[m])){(h.specialEasing=
h.specialEasing||{})[m]=a[m][1];a[m]=a[m][0]}}if(h.overflow!=null)this.style.overflow="hidden";h.curAnim=c.extend({},a);c.each(a,function(G,O){var Z=new c.fx(A,h,G);if(xb.test(O))Z[O==="toggle"?p?"show":"hide":O](a);else{var B=yb.exec(O),X=Z.cur()||0;if(B){O=parseFloat(B[2]);var ja=B[3]||"px";if(ja!=="px"){c.style(A,G,(O||1)+ja);X=(O||1)/Z.cur()*X;c.style(A,G,X+ja)}if(B[1])O=(B[1]==="-="?-1:1)*O+X;Z.custom(X,O,ja)}else Z.custom(X,O,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var e=d.length-1;e>=0;e--)if(d[e].elem===this){b&&d[e](true);d.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:Aa("show",1),slideUp:Aa("hide",1),slideToggle:Aa("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(d,e,f){return this.animate(b,d,e,f)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&
b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){e.queue!==false&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,d,e){return d+e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype=
{update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&a>-10000?a:0},custom:function(a,b,d){function e(m){return f.step(m)}var f=this,h=c.fx;this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=
this.state=0;e.elem=this.elem;if(e()&&c.timers.push(e)&&!kb)kb=setInterval(h.tick,h.interval)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var e in this.options.curAnim)if(this.options.curAnim[e]!==true)d=false;if(d){if(this.options.overflow!=null&&!c.support.shrinkWrapBlocks){var f=this.elem,h=this.options;c.each(["","X","Y"],function(l,p){f.style["overflow"+p]=h.overflow[l]})}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var m in this.options.curAnim)c.style(this.elem,m,this.options.orig[m]);this.options.complete.call(this.elem)}return false}else{a=
b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(kb);kb=null},speeds:{slow:600,
fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var zb=/^t(?:able|d|h)$/i,vb=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in w.documentElement?function(a){var b=
this[0],d;if(a)return this.each(function(m){c.offset.setOffset(this,a,m)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,h=f.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=f.body;f=pa(f);return{top:d.top+(f.pageYOffset||c.support.boxModel&&h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(f.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-
(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(v){c.offset.setOffset(this,a,v)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d,e=b.offsetParent,f=b,h=b.ownerDocument,m=h.documentElement,l=h.body;d=(h=h.defaultView)?h.getComputedStyle(b,null):b.currentStyle;for(var p=b.offsetTop,A=b.offsetLeft;(b=b.parentNode)&&b!==l&&b!==m;){if(c.offset.supportsFixedPosition&&d.position==="fixed")break;
d=h?h.getComputedStyle(b,null):b.currentStyle;p-=b.scrollTop;A-=b.scrollLeft;if(b===e){p+=b.offsetTop;A+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&zb.test(b.nodeName))){p+=parseFloat(d.borderTopWidth)||0;A+=parseFloat(d.borderLeftWidth)||0}f=e;e=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&d.overflow!=="visible"){p+=parseFloat(d.borderTopWidth)||0;A+=parseFloat(d.borderLeftWidth)||0}d=d}if(d.position==="relative"||d.position==="static"){p+=
l.offsetTop;A+=l.offsetLeft}if(c.offset.supportsFixedPosition&&d.position==="fixed"){p+=Math.max(m.scrollTop,l.scrollTop);A+=Math.max(m.scrollLeft,l.scrollLeft)}return{top:p,left:A}};c.offset={initialize:function(){var a=w.body,b=w.createElement("div"),d,e,f,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;f=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==5;this.doesAddBorderForTableAndCells=f.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),h=f.offset(),m=c.css(a,"top"),l=c.css(a,"left"),p=e==="absolute"&&c.inArray("auto",[m,l])>-1;e={};var A={};if(p)A=f.position();m=p?A.top:parseInt(m,
10)||0;l=p?A.left:parseInt(l,10)||0;if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=null)e.top=b.top-h.top+m;if(b.left!=null)e.left=b.left-h.left+l;"using"in b?b.using.call(a,e):f.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=vb.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],
"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||w.body;a&&!vb.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var f=this[0],h;if(!f)return null;if(e!==I)return this.each(function(){if(h=pa(this))h.scrollTo(!a?e:c(h).scrollLeft(),a?e:c(h).scrollTop());else this[d]=e});else return(h=pa(f))?"pageXOffset"in
h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:f[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(e){return this[0]?parseFloat(c.css(this[0],d,e?"margin":"border")):null};c.fn[d]=function(e){var f=this[0];if(!f)return e==null?null:this;if(c.isFunction(e))return this.each(function(m){var l=c(this);l[d](e.call(this,
m,l[d]()))});if(c.isWindow(f))return f.document.compatMode==="CSS1Compat"&&f.document.documentElement["client"+b]||f.document.body["client"+b];else if(f.nodeType===9)return Math.max(f.documentElement["client"+b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]);else if(e===I){f=c.css(f,d);var h=parseFloat(f);return c.isNaN(h)?f:h}else return this.css(d,typeof e==="string"?e:e+"px")}});typeof define!=="undefined"&&define("jquery",[],function(){return c})})(window);
