/*
 RequireJS 0.22.0 Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS i18n Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS text Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS order Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.4
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Thu Nov 11 19:04:53 2010 -0500
*/
var require,define;
(function(){function R(y){return ja.call(y)==="[object Function]"}function B(y){return ja.call(y)==="[object Array]"}function Aa(y,E,L){for(var M in E)if(!(M in ra)&&(!(M in y)||L))y[M]=E[M];return G}function $(y,E,L){var M,ha,S;for(M=0;S=E[M];M++){S=typeof S==="string"?{name:S}:S;ha=S.location;if(L&&(!ha||ha.indexOf("/")!==0&&ha.indexOf(":")===-1))S.location=L+"/"+(S.location||S.name);S.location=S.location||S.name;S.lib=S.lib||"lib";S.main=(S.main||"lib/main").replace(W,"");y[S.name]=S}}function J(y){function E(k){var o,
s;for(o=0;s=k[o];o++)if(s==="."){k.splice(o,1);o-=1}else if(s==="..")if(o===1&&(k[2]===".."||k[0]===".."))break;else if(o>0){k.splice(o-1,2);o-=2}}function L(k,o){var s;if(k.charAt(0)===".")if(o){if(ma.packages[o])o=[o];else{o=o.split("/");o=o.slice(0,o.length-1)}k=o.concat(k.split("/"));E(k);s=ma.packages[o=k[0]];k=k.join("/");if(s&&k===o+"/"+s.main)k=o}return k}function M(k,o){var s=k?k.indexOf("!"):-1,x=null,F=o?o.name:null,T=k,N,aa;if(s!==-1){x=k.substring(0,s);k=k.substring(s+1,k.length)}if(x){x=
L(x,F);x=Ya[x]||x}if(k){if(x)N=(s=ea[x])?s.normalize?s.normalize(k,function(ia){return L(ia,F)}):L(k,F):"__$p"+F+"@"+k;else N=L(k,F);aa=Za[N];if(!aa){aa=G.toModuleUrl?G.toModuleUrl(K,k,o):K.nameToUrl(k,null,o);Za[N]=aa}}return{prefix:x,name:N,parentMap:o,url:aa,originalName:T,fullName:x?x+"!"+N:N}}function ha(){var k=true,o=ma.priorityWait,s,x;if(o){for(x=0;s=o[x];x++)if(!va[s]){k=false;break}k&&delete ma.priorityWait}return k}function S(k){return function(o){k.exports=o}}function Qa(k,o,s){return function(){var x=
[].concat(ka.call(arguments,0)),F;if(s&&R(F=x[x.length-1]))F.__requireJsBuild=true;x.push(o);return k.apply(null,x)}}function gb(k,o){o=Qa(K.require,k,o);Aa(o,{nameToUrl:Qa(K.nameToUrl,k),toUrl:Qa(K.toUrl,k),isDefined:Qa(K.isDefined,k),ready:G.ready,isBrowser:G.isBrowser});if(G.paths)o.paths=G.paths;return o}function nb(k){var o,s,x,F,T,N,aa,ia=Ra[k];if(ia)for(F=0;s=ia[F];F++){o=s.fullName;s=M(s.originalName,s.parentMap);s=s.fullName;x=na[o];if(s!==o){na[s]=x;delete na[o];for(T=0;T<x.length;T++){aa=
x[T].depArray;for(N=0;N<aa.length;N++)if(aa[N]===o)aa[N]=s}}}delete Ra[k]}function hb(k){var o=k.prefix,s=k.fullName;if(!(Ma[s]||s in ea)){if(o&&!Ha[o]){Ha[o]=undefined;(Ra[o]||(Ra[o]=[])).push(k);(na[o]||(na[o]=[])).push({onDep:function(x){x===o&&nb(o)}});hb(M(o))}K.paused.push(k)}}function Sa(k){var o,s,x;o=k.callback;var F=k.fullName;x=[];var T=k.depArray;if(o&&R(o)){if(T)for(o=0;o<T.length;o++)x.push(k.deps[T[o]]);s=G.execCb(F,k.callback,x);if(F)if(k.usingExports&&s===undefined&&(!k.cjsModule||
!("exports"in k.cjsModule)))s=ea[F];else if(k.cjsModule&&"exports"in k.cjsModule)s=ea[F]=k.cjsModule.exports;else{if(F in ea&&!k.usingExports)return G.onError(new Error(F+" has already been defined"));ea[F]=s}}else if(F)s=ea[F]=o;if(F)if(x=na[F]){for(o=0;o<x.length;o++)x[o].onDep(F,s);delete na[F]}if(Ia[k.waitId]){delete Ia[k.waitId];k.isDone=true;K.waitCount-=1;if(K.waitCount===0)$a=[]}}function Na(k,o,s,x){k=M(k,x);var F=k.name,T=k.fullName,N={waitId:F||Ca+ob++,depCount:0,depMax:0,prefix:k.prefix,
name:F,fullName:T,deps:{},depArray:o,callback:s,onDep:function(ib,pb){if(!(ib in N.deps)){N.deps[ib]=pb;N.depCount+=1;N.depCount===N.depMax&&Sa(N)}}},aa,ia;if(T){if(T in ea||va[T]===true)return;Ma[T]=true;va[T]=true;K.jQueryDef=T==="jquery"}for(s=0;s<o.length;s++)if(aa=o[s]){aa=M(aa,F?k:x);ia=aa.fullName;o[s]=ia;if(ia==="require")N.deps[ia]=gb(k);else if(ia==="exports"){N.deps[ia]=ea[T]={};N.usingExports=true}else if(ia==="module"){N.cjsModule=aa=N.deps[ia]={id:F,uri:F?K.nameToUrl(F,null,x):undefined};
aa.setExports=S(aa)}else if(ia in ea&&!(ia in Ia))N.deps[ia]=ea[ia];else{N.depMax+=1;hb(aa);(na[ia]||(na[ia]=[])).push(N)}}if(N.depCount===N.depMax)Sa(N);else{Ia[N.waitId]=N;$a.push(N);K.waitCount+=1}}function La(k){Na.apply(null,k);va[k[0]]=true}function ab(k){if(!K.jQuery)if((k=k||(typeof jQuery!=="undefined"?jQuery:null))&&"readyWait"in k){K.jQuery=k;La(["jquery",[],function(){return jQuery}]);if(K.scriptCount){k.readyWait+=1;K.jQueryIncremented=true}}}function jb(k,o){if(!k.isDone){var s=k.fullName,
x=k.depArray,F,T;if(s){if(o[s])return ea[s];o[s]=true}for(T=0;T<x.length;T++)(F=x[T])&&!k.deps[F]&&Ia[F]&&k.onDep(F,jb(Ia[F],o));return s?ea[s]:undefined}}function bb(){var k=ma.waitSeconds*1E3,o=k&&K.startTime+k<(new Date).getTime();k="";var s=false,x=false,F;if(ma.priorityWait)if(ha())la();else return;for(F in va)if(!(F in ra)){s=true;if(!va[F])if(o)k+=F+" ";else{x=true;break}}if(s||K.waitCount){if(o&&k){F=new Error("require.js load timeout for modules: "+k);F.requireType="timeout";F.requireModules=
k;return G.onError(F)}if(x||K.scriptCount){if(sa||wa)setTimeout(bb,50)}else if(K.waitCount){for(Ja=0;k=$a[Ja];Ja++)jb(k,{});bb()}else G.checkReadyState()}}function cb(k,o){var s=o.name,x=o.fullName;if(!(x in ea)){Ha[k]||(Ha[k]=ea[k]);va[x]||(va[x]=false);Ha[k].load(s,gb(o.parentMap,true),function(F){require.onPluginLoad&&require.onPluginLoad(K,k,s,F);Sa({prefix:o.prefix,name:o.name,fullName:o.fullName,callback:F});va[x]=true},ma)}}function kb(k){if(k.prefix&&k.name.indexOf("__$p")===0&&ea[k.prefix])k=
M(k.originalName,k.parentMap);var o=k.prefix,s=k.fullName;if(!(Ma[s]||s in ea)){Ma[s]=true;if(o)if(ea[o])cb(o,k);else{if(!Ea[o]){Ea[o]=[];(na[o]||(na[o]=[])).push({onDep:function(x){if(x===o){var F,T=Ea[o];for(x=0;x<T.length;x++){F=T[x];cb(o,M(F.originalName,F.parentMap))}delete Ea[o]}}})}Ea[o].push(k)}else G.load(K,s,k.url)}}var K,la,ma={waitSeconds:7,baseUrl:ca.baseUrl||"./",paths:{},packages:{}},Oa=[],Ma={require:true,exports:true,module:true},Za={},ea={},va={},Ia={},$a=[],ob=0,na={},Ha={},Ea=
{},Ra={};la=function(){var k,o,s;if(K.scriptCount<=0)K.scriptCount=0;for(;Oa.length;){k=Oa.shift();if(k[0]===null)return G.onError(new Error("Mismatched anonymous require.def modules"));else La(k)}if(!(ma.priorityWait&&!ha())){for(;K.paused.length;){s=K.paused;K.paused=[];for(o=0;k=s[o];o++)kb(k);K.startTime=(new Date).getTime()}bb()}};K={contextName:y,config:ma,defQueue:Oa,waiting:Ia,waitCount:0,specified:Ma,loaded:va,urlMap:Za,scriptCount:0,urlFetched:{},defined:ea,paused:[],plugins:Ha,managerCallbacks:na,
makeModuleMap:M,normalize:L,configure:function(k){var o,s,x;if(k.baseUrl)if(k.baseUrl.charAt(k.baseUrl.length-1)!=="/")k.baseUrl+="/";o=ma.paths;s=ma.packages;Aa(ma,k,true);if(k.paths){for(x in k.paths)x in ra||(o[x]=k.paths[x]);ma.paths=o}if((o=k.packagePaths)||k.packages){if(o)for(x in o)x in ra||$(s,o[x],x);k.packages&&$(s,k.packages);ma.packages=s}if(k.priority){s=K.requireWait;K.requireWait=false;K.require(k.priority);K.requireWait=s;ma.priorityWait=k.priority}if(k.deps||k.callback)K.require(k.deps||
[],k.callback);k.ready&&G.ready(k.ready)},isDefined:function(k,o){return M(k,o).fullName in ea},require:function(k,o,s){if(typeof k==="string"){if(G.get)return G.get(K,k,o);s=o;o=M(k,s);k=ea[o.fullName];if(k===undefined)return G.onError(new Error("require: module name '"+o.fullName+"' has not been loaded yet for context: "+y));return k}Na(null,k,o,s);if(!K.requireWait)for(;!K.scriptCount&&K.paused.length;)la()},takeGlobalQueue:function(){if(c.length){oa.apply(K.defQueue,[K.defQueue.length-1,0].concat(c));
c=[]}},completeLoad:function(k){var o;for(K.takeGlobalQueue();Oa.length;){o=Oa.shift();if(o[0]===null){o[0]=k;break}else if(o[0]===k)break;else{La(o);o=null}}o?La(o):La([k,[],k==="jquery"&&typeof jQuery!=="undefined"?function(){return jQuery}:null]);va[k]=true;ab();if(G.isAsync)K.scriptCount-=1;la();G.isAsync||(K.scriptCount-=1)},toUrl:function(k,o){var s=k.lastIndexOf("."),x=null;if(s!==-1){x=k.substring(s,k.length);k=k.substring(0,s)}return K.nameToUrl(k,x,o)},nameToUrl:function(k,o,s){var x,F,
T,N,aa=K.config;if(k.indexOf("./")===0||k.indexOf("../")===0){s=s&&s.url?s.url.split("/"):[];s.length&&s.pop();s=s.concat(k.split("/"));E(s);o=s.join("/")+(o?o:G.jsExtRegExp.test(k)?"":".js")}else{k=L(k,s);if(G.jsExtRegExp.test(k))o=k+(o?o:"");else{x=aa.paths;F=aa.packages;s=k.split("/");for(N=s.length;N>0;N--){T=s.slice(0,N).join("/");if(x[T]){s.splice(0,N,x[T]);break}else if(T=F[T]){k=k===T.name?T.location+"/"+T.main:T.location+"/"+T.lib;s.splice(0,N,k);break}}o=s.join("/")+(o||".js");o=(o.charAt(0)===
"/"||o.match(/^\w+:/)?"":aa.baseUrl)+o}}return aa.urlArgs?o+((o.indexOf("?")===-1?"?":"&")+aa.urlArgs):o}};K.jQueryCheck=ab;K.resume=la;return K}function X(){var y,E,L;if(ta&&ta.readyState==="interactive")return ta;y=document.getElementsByTagName("script");for(E=y.length-1;E>-1&&(L=y[E]);E--)if(L.readyState==="interactive")return ta=L;return null}var O=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,U=/require\(["']([^'"\s]+)["']\)/g,W=/^\.\//,ja=Object.prototype.toString,ba=Array.prototype,ka=ba.slice,oa=ba.splice,
sa=!!(typeof window!=="undefined"&&navigator&&document),wa=!sa&&typeof importScripts!=="undefined",pa=sa&&navigator.platform==="PLAYSTATION 3"?/^complete$/:/^(complete|loaded)$/,Ca="_r@@",ra={},w={},c=[],ta=null,qb=false,db=false,Ya={text:"require/text",i18n:"require/i18n",order:"require/order"},G;ba={};var eb,ca,Ka,Ta,Ua,Fa,Va,Da,lb,Wa,Ja,Xa,fb,Ga;if(typeof require!=="undefined")if(R(require))return;else ba=require;G=require=function(y,E,L){var M="_",ha;if(!B(y)&&typeof y!=="string"){ha=y;if(B(E)){y=
E;E=L}else y=[]}if(ha&&ha.context)M=ha.context;L=w[M]||(w[M]=J(M));ha&&L.configure(ha);return L.require(y,E)};G.version="0.22.0";G.isArray=B;G.isFunction=R;G.mixin=Aa;G.jsExtRegExp=/^\/|:|\?|\.js$/;ca=G.s={contexts:w,skipAsync:{},isPageLoaded:!sa,readyCalls:[]};if(G.isAsync=G.isBrowser=sa){Ka=ca.head=document.getElementsByTagName("head")[0];if(Ta=document.getElementsByTagName("base")[0])Ka=ca.head=Ta.parentNode}G.onError=function(y){throw y;};G.load=function(y,E,L){var M=y.contextName,ha=y.urlFetched,
S=y.loaded;qb=false;S[E]||(S[E]=false);if(!ha[L]){y.scriptCount+=1;G.attach(L,M,E);ha[L]=true;if(y.jQuery&&!y.jQueryIncremented){y.jQuery.readyWait+=1;y.jQueryIncremented=true}}};define=G.def=function(y,E,L){var M;if(typeof y!=="string"){L=E;E=y;y=null}if(!G.isArray(E)){L=E;E=[]}if(!y&&!E.length&&G.isFunction(L))if(L.length){L.toString().replace(O,"").replace(U,function(ha,S){E.push(S)});E=["require","exports","module"].concat(E)}if(db){M=eb||X();if(!M)return G.onError(new Error("ERROR: No matching script interactive for "+
L));y||(y=M.getAttribute("data-requiremodule"));M=w[M.getAttribute("data-requirecontext")]}(M?M.defQueue:c).push([y,E,L])};G.execCb=function(y,E,L){return E.apply(null,L)};G.onScriptLoad=function(y){var E=y.currentTarget||y.srcElement,L;if(y.type==="load"||pa.test(E.readyState)){ta=null;y=E.getAttribute("data-requirecontext");L=E.getAttribute("data-requiremodule");w[y].completeLoad(L);E.removeEventListener?E.removeEventListener("load",G.onScriptLoad,false):E.detachEvent("onreadystatechange",G.onScriptLoad)}};
G.attach=function(y,E,L,M,ha){var S;if(sa){M=M||G.onScriptLoad;S=document.createElement("script");S.type=ha||"text/javascript";S.charset="utf-8";S.async=!ca.skipAsync[y];S.setAttribute("data-requirecontext",E);S.setAttribute("data-requiremodule",L);if(S.addEventListener)S.addEventListener("load",M,false);else{db=true;S.attachEvent("onreadystatechange",M)}S.src=y;eb=S;Ta?Ka.insertBefore(S,Ta):Ka.appendChild(S);eb=null;return S}else if(wa){M=w[E];E=M.loaded;E[L]=false;importScripts(y);M.completeLoad(L)}return null};
ca.baseUrl=ba.baseUrl;if(sa&&(!ca.baseUrl||!Ka)){Ua=document.getElementsByTagName("script");Va=ba.baseUrlMatch?ba.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(Ja=Ua.length-1;Ja>-1&&(Fa=Ua[Ja]);Ja--){if(!Ka)Ka=Fa.parentNode;if(!Wa&&(Wa=Fa.getAttribute("data-main"))){ba.deps=ba.deps?ba.deps.concat(Wa):[Wa];if(!ba.baseUrl&&(Da=Fa.src)){Da=Da.split("/");Da.pop();ca.baseUrl=ba.baseUrl=Da.length?Da.join("/"):"./"}}if(!ca.baseUrl&&(Da=Fa.src))if(lb=Da.match(Va)){ca.baseUrl=
Da.substring(0,lb.index);break}}}G.pageLoaded=function(){if(!ca.isPageLoaded){ca.isPageLoaded=true;Xa&&clearInterval(Xa);if(fb)document.readyState="complete";G.callReady()}};G.checkReadyState=function(){var y=ca.contexts,E;for(E in y)if(!(E in ra))if(y[E].waitCount)return;ca.isDone=true;G.callReady()};G.callReady=function(){var y=ca.readyCalls,E,L,M;if(ca.isPageLoaded&&ca.isDone){if(y.length){ca.readyCalls=[];for(E=0;L=y[E];E++)L()}y=ca.contexts;for(M in y)if(!(M in ra)){E=y[M];if(E.jQueryIncremented){E.jQuery.readyWait-=
1;E.jQueryIncremented=false}}}};G.ready=function(y){ca.isPageLoaded&&ca.isDone?y():ca.readyCalls.push(y);return G};if(sa){if(document.addEventListener){document.addEventListener("DOMContentLoaded",G.pageLoaded,false);window.addEventListener("load",G.pageLoaded,false);if(!document.readyState){fb=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",G.pageLoaded);if(self===self.top)Xa=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");
G.pageLoaded()}}catch(y){}},30)}document.readyState==="complete"&&G.pageLoaded()}G(ba);if(typeof setTimeout!=="undefined"){Ga=ca.contexts[ba.context||"_"];Ga.requireWait=true;setTimeout(function(){Ga.requireWait=false;Ga.takeGlobalQueue();Ga.jQueryCheck();Ga.scriptCount||Ga.resume();G.checkReadyState()},0)}})();
(function(){function R($,J,X,O,U,W){if(J[$]){X.push($);if(J[$]===true||J[$]===1)O.push(U+$+"/"+W)}}function B($,J,X,O,U){J=O+J+"/"+U;require._fileExists($.nameToUrl(J,null))&&X.push(J)}var Aa=/(^.*(^|\/)nls(\/|$))([^\/]*)\/?([^\/]*)/;define("require/i18n",{load:function($,J,X,O){O=O||{};var U=Aa.exec($),W=U[1],ja=U[4],ba=U[5],ka=ja.split("-"),oa=[],sa={},wa,pa,Ca="";if(U[5]){W=U[1];$=W+ba}else{$=$;ba=U[4];ja=O.locale||(O.locale=typeof navigator==="undefined"?"root":(navigator.language||navigator.userLanguage||
"root").toLowerCase());ka=ja.split("-")}if(O.isBuild){oa.push($);B(J,"root",oa,W,ba);for(wa=0;pa=ka[wa];wa++){Ca+=(Ca?"-":"")+pa;B(J,Ca,oa,W,ba)}J(oa);X()}else J([$],function(ra){var w=[];R("root",ra,w,oa,W,ba);for(wa=0;pa=ka[wa];wa++){Ca+=(Ca?"-":"")+pa;R(Ca,ra,w,oa,W,ba)}J(oa,function(){var c,ta;for(c=w.length-1;c>-1&&(pa=w[c]);c--){ta=ra[pa];if(ta===true||ta===1)ta=J(W+pa+"/"+ba);require.mixin(sa,ta)}X(sa)})})}})})();
(function(){var R=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],B=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,Aa=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im,$=[];if(!require.textStrip)require.textStrip=function(J){if(J){J=J.replace(B,"");var X=J.match(Aa);if(X)J=X[1]}else J="";return J};if(!require.jsEscape)require.jsEscape=function(J){return J.replace(/(['\\])/g,"\\$1").replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,
"\\r")};if(!require.getXhr)require.getXhr=function(){var J,X,O;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(X=0;X<3;X++){O=R[X];try{J=new ActiveXObject(O)}catch(U){}if(J){R=[O];break}}if(!J)throw new Error("require.getXhr(): XMLHttpRequest not available");return J};if(!require.fetchText)require.fetchText=function(J,X){var O=require.getXhr();O.open("GET",J,true);O.onreadystatechange=function(){O.readyState===4&&X(O.responseText)};O.send(null)};define("require/text",{load:function(J,
X,O,U){var W=false,ja=J.indexOf("."),ba=J.substring(0,ja),ka=J.substring(ja+1,J.length);ja=ka.indexOf("!");if(ja!==-1){W=ka.substring(ja+1,ka.length);W=W==="strip";ka=ka.substring(0,ja)}X=X.nameToUrl(ba,"."+ka);require.fetchText(X,function(oa){oa=W?require.textStrip(oa):oa;if(U.isBuild&&U.inlineText)$[J]=oa;O(oa)})},write:function(J,X,O){if(X in $){var U=require.jsEscape($[X]);O("define('"+J+"!"+X+"', function () { return '"+U+"';});\n")}}})})();
(function(){function R(O,U,W){U([O],function(ja){W(function(){return ja})})}function B(O){var U=O.currentTarget||O.srcElement,W;if(O.type==="load"||$.test(U.readyState)){O=U.getAttribute("data-requiremodule");X[O]=true;for(O=0;W=J[O];O++)if(X[W.name])R(W.name,W.req,W.onLoad);else break;O>0&&J.splice(0,O);setTimeout(function(){U.parentNode.removeChild(U)},15)}}var Aa=typeof document!=="undefined"&&typeof window!=="undefined"&&(document.createElement("script").async||window.opera&&Object.prototype.toString.call(window.opera)===
"[object Opera]"||"MozAppearance"in document.documentElement.style),$=/^(complete|loaded)$/,J=[],X={};define("require/order",{load:function(O,U,W,ja){var ba=U.nameToUrl(O,null);if(ja.isBuild)R(O,U,W);else{require.s.skipAsync[ba]=true;if(Aa)U([O],function(ka){W(function(){return ka})});else if(U.isDefined(O))U([O],function(ka){W(function(){return ka})});else{J.push({name:O,req:U,onLoad:W});require.attach(ba,"",O,B,"script/cache")}}}})})();
(function(R,B){function Aa(a,b,d){if(d===B&&a.nodeType===1){d=a.getAttribute("data-"+b);if(typeof d==="string"){try{d=d==="true"?true:d==="false"?false:d==="null"?null:!c.isNaN(d)?parseFloat(d):qb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=B}return d}function $(){return false}function J(){return true}function X(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function O(a){var b,d,e,f,h,m,l,p,A,v,H,Q=[];f=[];h=c.data(this,this.nodeType?"events":"__events__");if(typeof h==="function")h=
h.events;if(!(a.liveFired===this||!h||!h.live||a.button&&a.type==="click")){if(a.namespace)H=new RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)");a.liveFired=this;var fa=h.live.slice(0);for(l=0;l<fa.length;l++){h=fa[l];h.origType.replace(Fa,"")===a.type?f.push(h.selector):fa.splice(l--,1)}f=c(a.target).closest(f,a.currentTarget);p=0;for(A=f.length;p<A;p++){v=f[p];for(l=0;l<fa.length;l++){h=fa[l];if(v.selector===h.selector&&(!H||H.test(h.namespace))){m=v.elem;e=null;if(h.preType===
"mouseenter"||h.preType==="mouseleave"){a.type=h.preType;e=c(a.relatedTarget).closest(h.selector)[0]}if(!e||e!==m)Q.push({elem:m,handleObj:h,level:v.level})}}}p=0;for(A=Q.length;p<A;p++){f=Q[p];if(d&&f.level>d)break;a.currentTarget=f.elem;a.data=f.handleObj.data;a.handleObj=f.handleObj;H=f.handleObj.origHandler.apply(f.elem,arguments);if(H===false||a.isPropagationStopped()){d=f.level;if(H===false)b=false;if(a.isImmediatePropagationStopped())break}}return b}}function U(a,b){return(a&&a!=="*"?a+".":
"")+b.replace(Da,"`").replace(lb,"&")}function W(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function ja(a,b,d){if(c.isFunction(b))return c.grep(a,function(f,h){return!!b.call(f,h,f)===d});else if(b.nodeType)return c.grep(a,function(f){return f===b===d});else if(typeof b==="string"){var e=c.grep(a,function(f){return f.nodeType===1});if(gb.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(f){return c.inArray(f,b)>=0===d})}function ba(a){return c.nodeName(a,"table")?
a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function ka(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var e=c.data(a[d++]),f=c.data(this,e);if(e=e&&e.events){delete f.handle;f.events={};for(var h in e)for(var m in e[h])c.event.add(this,h,e[h][m],e[h][m].data)}}})}function oa(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}
function sa(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?$a:ob,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);if(d==="margin")e+=parseFloat(c.css(a,"margin"+this))||0;else e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function wa(a,b,d,e){if(c.isArray(b)&&b.length)c.each(b,function(f,h){d||T.test(a)?e(a,h):wa(a+"["+(typeof h==="object"||c.isArray(h)?f:"")+"]",h,d,e)});else if(!d&&b!=null&&typeof b==="object")c.isEmptyObject(b)?
e(a,""):c.each(b,function(f,h){wa(a+"["+f+"]",h,d,e)});else e(a,b)}function pa(a,b){var d={};c.each(tb.concat.apply([],tb.slice(0,b)),function(){d[this]=a});return d}function Ca(a){if(!rb[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d==="")d="block";rb[a]=d}return rb[a]}function ra(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var w=R.document,c=function(){function a(){if(!b.isReady){try{w.documentElement.doScroll("left")}catch(j){setTimeout(a,
1);return}b.ready()}}var b=function(j,t){return new b.fn.init(j,t)},d=R.jQuery,e=R.$,f,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,m=/\S/,l=/^\s+/,p=/\s+$/,A=/\W/,v=/\d/,H=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,Q=/^[\],:{}\s]*$/,fa=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,C=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,da=/(?:^|:|,)(?:\s*\[)+/g,xa=/(webkit)[ \/]([\w.]+)/,g=/(opera)(?:.*version)?[ \/]([\w.]+)/,i=/(msie) ([\w.]+)/,n=/(mozilla)(?:.*? rv:([\w.]+))?/,q=navigator.userAgent,r=false,
u=[],D,I=Object.prototype.toString,Y=Object.prototype.hasOwnProperty,ua=Array.prototype.push,ya=Array.prototype.slice,za=String.prototype.trim,V=Array.prototype.indexOf,Pa={};b.fn=b.prototype={init:function(j,t){var z,P;if(!j)return this;if(j.nodeType){this.context=this[0]=j;this.length=1;return this}if(j==="body"&&!t&&w.body){this.context=w;this[0]=w.body;this.selector="body";this.length=1;return this}if(typeof j==="string")if((z=h.exec(j))&&(z[1]||!t))if(z[1]){P=t?t.ownerDocument||t:w;if(j=H.exec(j))if(b.isPlainObject(t)){j=
[w.createElement(j[1])];b.fn.attr.call(j,t,true)}else j=[P.createElement(j[1])];else{j=b.buildFragment([z[1]],[P]);j=(j.cacheable?j.fragment.cloneNode(true):j.fragment).childNodes}return b.merge(this,j)}else{if((t=w.getElementById(z[2]))&&t.parentNode){if(t.id!==z[2])return f.find(j);this.length=1;this[0]=t}this.context=w;this.selector=j;return this}else if(!t&&!A.test(j)){this.selector=j;this.context=w;j=w.getElementsByTagName(j);return b.merge(this,j)}else return!t||t.jquery?(t||f).find(j):b(t).find(j);
else if(b.isFunction(j))return f.ready(j);if(j.selector!==B){this.selector=j.selector;this.context=j.context}return b.makeArray(j,this)},selector:"",jquery:"1.4.4",length:0,size:function(){return this.length},toArray:function(){return ya.call(this,0)},get:function(j){return j==null?this.toArray():j<0?this.slice(j)[0]:this[j]},pushStack:function(j,t,z){var P=b();b.isArray(j)?ua.apply(P,j):b.merge(P,j);P.prevObject=this;P.context=this.context;if(t==="find")P.selector=this.selector+(this.selector?" ":
"")+z;else if(t)P.selector=this.selector+"."+t+"("+z+")";return P},each:function(j,t){return b.each(this,j,t)},ready:function(j){b.bindReady();if(b.isReady)j.call(w,b);else u&&u.push(j);return this},eq:function(j){return j===-1?this.slice(j):this.slice(j,+j+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ya.apply(this,arguments),"slice",ya.call(arguments).join(","))},map:function(j){return this.pushStack(b.map(this,function(t,z){return j.call(t,
z,t)}))},end:function(){return this.prevObject||b(null)},push:ua,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var j,t,z,P,ga,Z=arguments[0]||{},qa=1,Ba=arguments.length,sb=false;if(typeof Z==="boolean"){sb=Z;Z=arguments[1]||{};qa=2}if(typeof Z!=="object"&&!b.isFunction(Z))Z={};if(Ba===qa){Z=this;--qa}for(;qa<Ba;qa++)if((j=arguments[qa])!=null)for(t in j){z=Z[t];P=j[t];if(Z!==P)if(sb&&P&&(b.isPlainObject(P)||(ga=b.isArray(P)))){if(ga){ga=false;z=z&&b.isArray(z)?
z:[]}else z=z&&b.isPlainObject(z)?z:{};Z[t]=b.extend(sb,z,P)}else if(P!==B)Z[t]=P}return Z};b.extend({noConflict:function(j){R.$=e;if(j)R.jQuery=d;return b},isReady:false,readyWait:1,ready:function(j){j===true&&b.readyWait--;if(!b.readyWait||j!==true&&!b.isReady){if(!w.body)return setTimeout(b.ready,1);b.isReady=true;if(!(j!==true&&--b.readyWait>0))if(u){var t=0,z=u;for(u=null;j=z[t++];)j.call(w,b);b.fn.trigger&&b(w).trigger("ready").unbind("ready")}}},bindReady:function(){if(!r){r=true;if(w.readyState===
"complete")return setTimeout(b.ready,1);if(w.addEventListener){w.addEventListener("DOMContentLoaded",D,false);R.addEventListener("load",b.ready,false)}else if(w.attachEvent){w.attachEvent("onreadystatechange",D);R.attachEvent("onload",b.ready);var j=false;try{j=R.frameElement==null}catch(t){}w.documentElement.doScroll&&j&&a()}}},isFunction:function(j){return b.type(j)==="function"},isArray:Array.isArray||function(j){return b.type(j)==="array"},isWindow:function(j){return j&&typeof j==="object"&&"setInterval"in
j},isNaN:function(j){return j==null||!v.test(j)||isNaN(j)},type:function(j){return j==null?String(j):Pa[I.call(j)]||"object"},isPlainObject:function(j){if(!j||b.type(j)!=="object"||j.nodeType||b.isWindow(j))return false;if(j.constructor&&!Y.call(j,"constructor")&&!Y.call(j.constructor.prototype,"isPrototypeOf"))return false;var t;for(t in j);return t===B||Y.call(j,t)},isEmptyObject:function(j){for(var t in j)return false;return true},error:function(j){throw j;},parseJSON:function(j){if(typeof j!==
"string"||!j)return null;j=b.trim(j);if(Q.test(j.replace(fa,"@").replace(C,"]").replace(da,"")))return R.JSON&&R.JSON.parse?R.JSON.parse(j):(new Function("return "+j))();else b.error("Invalid JSON: "+j)},noop:function(){},globalEval:function(j){if(j&&m.test(j)){var t=w.getElementsByTagName("head")[0]||w.documentElement,z=w.createElement("script");z.type="text/javascript";if(b.support.scriptEval)z.appendChild(w.createTextNode(j));else z.text=j;t.insertBefore(z,t.firstChild);t.removeChild(z)}},nodeName:function(j,
t){return j.nodeName&&j.nodeName.toUpperCase()===t.toUpperCase()},each:function(j,t,z){var P,ga=0,Z=j.length,qa=Z===B||b.isFunction(j);if(z)if(qa)for(P in j){if(t.apply(j[P],z)===false)break}else for(;ga<Z;){if(t.apply(j[ga++],z)===false)break}else if(qa)for(P in j){if(t.call(j[P],P,j[P])===false)break}else for(z=j[0];ga<Z&&t.call(z,ga,z)!==false;z=j[++ga]);return j},trim:za?function(j){return j==null?"":za.call(j)}:function(j){return j==null?"":j.toString().replace(l,"").replace(p,"")},makeArray:function(j,
t){t=t||[];if(j!=null){var z=b.type(j);j.length==null||z==="string"||z==="function"||z==="regexp"||b.isWindow(j)?ua.call(t,j):b.merge(t,j)}return t},inArray:function(j,t){if(t.indexOf)return t.indexOf(j);for(var z=0,P=t.length;z<P;z++)if(t[z]===j)return z;return-1},merge:function(j,t){var z=j.length,P=0;if(typeof t.length==="number")for(var ga=t.length;P<ga;P++)j[z++]=t[P];else for(;t[P]!==B;)j[z++]=t[P++];j.length=z;return j},grep:function(j,t,z){var P=[],ga;z=!!z;for(var Z=0,qa=j.length;Z<qa;Z++){ga=
!!t(j[Z],Z);z!==ga&&P.push(j[Z])}return P},map:function(j,t,z){for(var P=[],ga,Z=0,qa=j.length;Z<qa;Z++){ga=t(j[Z],Z,z);if(ga!=null)P[P.length]=ga}return P.concat.apply([],P)},guid:1,proxy:function(j,t,z){if(arguments.length===2)if(typeof t==="string"){z=j;j=z[t];t=B}else if(t&&!b.isFunction(t)){z=t;t=B}if(!t&&j)t=function(){return j.apply(z||this,arguments)};if(j)t.guid=j.guid=j.guid||t.guid||b.guid++;return t},access:function(j,t,z,P,ga,Z){var qa=j.length;if(typeof t==="object"){for(var Ba in t)b.access(j,
Ba,t[Ba],P,ga,z);return j}if(z!==B){P=!Z&&P&&b.isFunction(z);for(Ba=0;Ba<qa;Ba++)ga(j[Ba],t,P?z.call(j[Ba],Ba,ga(j[Ba],t)):z,Z);return j}return qa?ga(j[0],t):B},now:function(){return(new Date).getTime()},uaMatch:function(j){j=j.toLowerCase();j=xa.exec(j)||g.exec(j)||i.exec(j)||j.indexOf("compatible")<0&&n.exec(j)||[];return{browser:j[1]||"",version:j[2]||"0"}},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(j,t){Pa["[object "+t+"]"]=t.toLowerCase()});
q=b.uaMatch(q);if(q.browser){b.browser[q.browser]=true;b.browser.version=q.version}if(b.browser.webkit)b.browser.safari=true;if(V)b.inArray=function(j,t){return V.call(t,j)};if(!/\s/.test("\u00a0")){l=/^[\s\xA0]+/;p=/[\s\xA0]+$/}f=b(w);if(w.addEventListener)D=function(){w.removeEventListener("DOMContentLoaded",D,false);b.ready()};else if(w.attachEvent)D=function(){if(w.readyState==="complete"){w.detachEvent("onreadystatechange",D);b.ready()}};return R.jQuery=R.$=b}();(function(){c.support={};var a=
w.documentElement,b=w.createElement("script"),d=w.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var f=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],m=w.createElement("select"),l=m.appendChild(w.createElement("option"));if(!(!f||!f.length||!h)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,
htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:h.getAttribute("href")==="/a",opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:l.selected,deleteExpando:true,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};m.disabled=true;c.support.optDisabled=
!l.disabled;b.type="text/javascript";try{b.appendChild(w.createTextNode("window."+e+"=1;"))}catch(p){}a.insertBefore(b,a.firstChild);if(R[e]){c.support.scriptEval=true;delete R[e]}try{delete b.test}catch(A){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function v(){c.support.noCloneEvent=false;d.detachEvent("onclick",v)});d.cloneNode(true).fireEvent("onclick")}d=w.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
a=w.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var v=w.createElement("div");v.style.width=v.style.paddingLeft="1px";w.body.appendChild(v);c.boxModel=c.support.boxModel=v.offsetWidth===2;if("zoom"in v.style){v.style.display="inline";v.style.zoom=1;c.support.inlineBlockNeedsLayout=v.offsetWidth===2;v.style.display="";v.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=v.offsetWidth!==
2}v.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var H=v.getElementsByTagName("td");c.support.reliableHiddenOffsets=H[0].offsetHeight===0;H[0].style.display="";H[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&H[0].offsetHeight===0;v.innerHTML="";w.body.removeChild(v).style.display="none"});a=function(v){var H=w.createElement("div");v="on"+v;var Q=v in H;if(!Q){H.setAttribute(v,"return;");Q=typeof H[v]==="function"}return Q};
c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=f=h=null}})();var ta={},qb=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},data:function(a,b,d){if(c.acceptData(a)){a=a==R?ta:a;var e=a.nodeType,f=e?a[c.expando]:null,h=c.cache;if(!(e&&!f&&typeof b==="string"&&d===B)){if(e)f||(a[c.expando]=f=++c.uuid);else h=a;if(typeof b==="object")if(e)h[f]=c.extend(h[f],b);else c.extend(h,
b);else if(e&&!h[f])h[f]={};a=e?h[f]:h;if(d!==B)a[b]=d;return typeof b==="string"?a[b]:a}}},removeData:function(a,b){if(c.acceptData(a)){a=a==R?ta:a;var d=a.nodeType,e=d?a[c.expando]:a,f=c.cache,h=d?f[e]:e;if(b){if(h){delete h[b];d&&c.isEmptyObject(h)&&c.removeData(a)}}else if(d&&c.support.deleteExpando)delete a[c.expando];else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete f[e];else for(var m in a)delete a[m]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];
if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){var d=null;if(typeof a==="undefined"){if(this.length){var e=this[0].attributes,f;d=c.data(this[0]);for(var h=0,m=e.length;h<m;h++){f=e[h].name;if(f.indexOf("data-")===0){f=f.substr(5);Aa(this[0],f,d[f])}}}return d}else if(typeof a==="object")return this.each(function(){c.data(this,a)});var l=a.split(".");l[1]=l[1]?"."+l[1]:"";if(b===B){d=this.triggerHandler("getData"+l[1]+"!",[l[0]]);if(d===B&&this.length){d=
c.data(this[0],a);d=Aa(this[0],a,d)}return d===B&&l[1]?this.data(l[0]):d}else return this.each(function(){var p=c(this),A=[l[0],b];p.triggerHandler("setData"+l[1]+"!",A);c.data(this,a,b);p.triggerHandler("changeData"+l[1]+"!",A)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c.data(a,b);if(!d)return e||[];if(!e||c.isArray(d))e=c.data(a,b,c.makeArray(d));else e.push(d);return e}},dequeue:function(a,b){b=
b||"fx";var d=c.queue(a,b),e=d.shift();if(e==="inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");e.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===B)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,
function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var db=/[\n\t]/g,Ya=/\s+/,G=/\r/g,eb=/^(?:href|src|style)$/,ca=/^(?:button|input)$/i,Ka=/^(?:button|input|object|select|textarea)$/i,Ta=/^a(?:rea)?$/i,Ua=/^(?:radio|checkbox)$/i;c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};
c.fn.extend({attr:function(a,b){return c.access(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(A){var v=c(this);v.addClass(a.call(this,A,v.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(Ya),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1)if(f.className){for(var h=" "+f.className+" ",m=f.className,l=0,p=b.length;l<
p;l++)if(h.indexOf(" "+b[l]+" ")<0)m+=" "+b[l];f.className=c.trim(m)}else f.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(p){var A=c(this);A.removeClass(a.call(this,p,A.attr("class")))});if(a&&typeof a==="string"||a===B)for(var b=(a||"").split(Ya),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1&&f.className)if(a){for(var h=(" "+f.className+" ").replace(db," "),m=0,l=b.length;m<l;m++)h=h.replace(" "+b[m]+" "," ");f.className=c.trim(h)}else f.className=
""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(f){var h=c(this);h.toggleClass(a.call(this,f,h.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var f,h=0,m=c(this),l=b,p=a.split(Ya);f=p[h++];){l=e?l:!m.hasClass(f);m[l?"addClass":"removeClass"](f)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,
"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(db," ").indexOf(a)>-1)return true;return false},val:function(a){if(!arguments.length){var b=this[0];if(b){if(c.nodeName(b,"option")){var d=b.attributes.value;return!d||d.specified?b.value:b.text}if(c.nodeName(b,"select")){var e=b.selectedIndex;d=[];var f=b.options;b=b.type==="select-one";if(e<0)return null;var h=b?e:0;for(e=b?e+1:f.length;h<e;h++){var m=f[h];if(m.selected&&
(c.support.optDisabled?!m.disabled:m.getAttribute("disabled")===null)&&(!m.parentNode.disabled||!c.nodeName(m.parentNode,"optgroup"))){a=c(m).val();if(b)return a;d.push(a)}}return d}if(Ua.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(G,"")}return B}var l=c.isFunction(a);return this.each(function(p){var A=c(this),v=a;if(this.nodeType===1){if(l)v=a.call(this,p,A.val());if(v==null)v="";else if(typeof v==="number")v+="";else if(c.isArray(v))v=
c.map(v,function(Q){return Q==null?"":Q+""});if(c.isArray(v)&&Ua.test(this.type))this.checked=c.inArray(A.val(),v)>=0;else if(c.nodeName(this,"select")){var H=c.makeArray(v);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),H)>=0});if(!H.length)this.selectedIndex=-1}else this.value=v}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,e){if(!a||a.nodeType===3||a.nodeType===8)return B;if(e&&b in c.attrFn)return c(a)[b](d);
e=a.nodeType!==1||!c.isXMLDoc(a);var f=d!==B;b=e&&c.props[b]||b;var h=eb.test(b);if((b in a||a[b]!==B)&&e&&!h){if(f){b==="type"&&ca.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");if(d===null)a.nodeType===1&&a.removeAttribute(b);else a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:Ka.test(a.nodeName)||Ta.test(a.nodeName)&&a.href?0:B;return a[b]}if(!c.support.style&&
e&&b==="style"){if(f)a.style.cssText=""+d;return a.style.cssText}f&&a.setAttribute(b,""+d);if(!a.attributes[b]&&a.hasAttribute&&!a.hasAttribute(b))return B;a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b);return a===null?B:a}});var Fa=/\.(.*)$/,Va=/^(?:textarea|input|select)$/i,Da=/\./g,lb=/ /g,Wa=/[^\w\s.|`]/g,Ja=function(a){return a.replace(Wa,"\\$&")},Xa={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(c.isWindow(a)&&a!==R&&!a.frameElement)a=
R;if(d===false)d=$;else if(!d)return;var f,h;if(d.handler){f=d;d=f.handler}if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var m=a.nodeType?"events":"__events__",l=h[m],p=h.handle;if(typeof l==="function"){p=l.handle;l=l.events}else if(!l){a.nodeType||(h[m]=h=function(){});h.events=l={}}if(!p)h.handle=p=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(p.elem,arguments):B};p.elem=a;b=b.split(" ");for(var A=0,v;m=b[A++];){h=f?c.extend({},f):{handler:d,data:e};if(m.indexOf(".")>
-1){v=m.split(".");m=v.shift();h.namespace=v.slice(0).sort().join(".")}else{v=[];h.namespace=""}h.type=m;if(!h.guid)h.guid=d.guid;var H=l[m],Q=c.event.special[m]||{};if(!H){H=l[m]=[];if(!Q.setup||Q.setup.call(a,e,v,p)===false)if(a.addEventListener)a.addEventListener(m,p,false);else a.attachEvent&&a.attachEvent("on"+m,p)}if(Q.add){Q.add.call(a,h);if(!h.handler.guid)h.handler.guid=d.guid}H.push(h);c.event.global[m]=true}a=null}}},global:{},remove:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===
8)){if(d===false)d=$;var f,h,m=0,l,p,A,v,H,Q,fa=a.nodeType?"events":"__events__",C=c.data(a),da=C&&C[fa];if(C&&da){if(typeof da==="function"){C=da;da=da.events}if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(f in da)c.event.remove(a,f+b)}else{for(b=b.split(" ");f=b[m++];){v=f;l=f.indexOf(".")<0;p=[];if(!l){p=f.split(".");f=p.shift();A=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),Ja).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(H=da[f])if(d){v=c.event.special[f]||
{};for(h=e||0;h<H.length;h++){Q=H[h];if(d.guid===Q.guid){if(l||A.test(Q.namespace)){e==null&&H.splice(h--,1);v.remove&&v.remove.call(a,Q)}if(e!=null)break}}if(H.length===0||e!=null&&H.length===1){if(!v.teardown||v.teardown.call(a,p)===false)c.removeEvent(a,f,C.handle);delete da[f]}}else for(h=0;h<H.length;h++){Q=H[h];if(l||A.test(Q.namespace)){c.event.remove(a,v,Q.handler,h);H.splice(h--,1)}}}if(c.isEmptyObject(da)){if(b=C.handle)b.elem=null;delete C.events;delete C.handle;if(typeof C==="function")c.removeData(a,
fa);else c.isEmptyObject(C)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var f=a.type||a;if(!e){a=typeof a==="object"?a[c.expando]?a:c.extend(c.Event(f),a):c.Event(f);if(f.indexOf("!")>=0){a.type=f=f.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[f]&&c.each(c.cache,function(){this.events&&this.events[f]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return B;a.result=B;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(e=d.nodeType?
c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+f]&&d["on"+f].apply(d,b)===false){a.result=false;a.preventDefault()}}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,true);else if(!a.isDefaultPrevented()){var m;e=a.target;var l=f.replace(Fa,""),p=c.nodeName(e,"a")&&l==="click",A=c.event.special[l]||{};if((!A._default||A._default.call(d,a)===false)&&!p&&!(e&&e.nodeName&&
c.noData[e.nodeName.toLowerCase()])){try{if(e[l]){if(m=e["on"+l])e["on"+l]=null;c.event.triggered=true;e[l]()}}catch(v){}if(m)e["on"+l]=m;c.event.triggered=false}}},handle:function(a){var b,d,e,f;d=[];var h=c.makeArray(arguments);a=h[0]=c.event.fix(a||R.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){e=a.type.split(".");a.type=e.shift();d=e.slice(0).sort();e=new RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)")}a.namespace=a.namespace||d.join(".");f=c.data(this,this.nodeType?
"events":"__events__");if(typeof f==="function")f=f.events;d=(f||{})[a.type];if(f&&d){d=d.slice(0);f=0;for(var m=d.length;f<m;f++){var l=d[f];if(b||e.test(l.namespace)){a.handler=l.handler;a.data=l.data;a.handleObj=l;l=l.handler.apply(this,h);if(l!==B){a.result=l;if(l===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;var b=a;a=c.Event(b);for(var d=this.props.length,e;d;){e=this.props[--d];a[e]=b[e]}if(!a.target)a.target=a.srcElement||w;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=w.documentElement;d=w.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==B)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,U(a.origType,a.selector),c.extend({},a,{handler:O,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
U(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=w.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=a;this.timeStamp=
c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=J;var a=this.originalEvent;if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=J;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=J;this.stopPropagation()},isDefaultPrevented:$,isPropagationStopped:$,isImmediatePropagationStopped:$};
var fb=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Ga=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Ga:fb,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Ga:fb)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length){a.liveFired=B;return X("submit",this,arguments)}});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13){a.liveFired=B;return X("submit",this,arguments)}})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var y,
E=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(e){return e.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},L=function(a,b){var d=a.target,e,f;if(!(!Va.test(d.nodeName)||d.readOnly)){e=c.data(d,"_change_data");f=E(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",f);if(!(e===B||f===e))if(e!=null||f){a.type="change";a.liveFired=
B;return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:L,beforedeactivate:L,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return L.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return L.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",E(a))}},setup:function(){if(this.type===
"file")return false;for(var a in y)c.event.add(this,a+".specialChange",y[a]);return Va.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return Va.test(this.nodeName)}};y=c.event.special.change.filters;y.focus=y.beforeactivate}w.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.trigger(e,null,e.target)}c.event.special[b]={setup:function(){Xa[b]++===0&&w.addEventListener(a,d,true)},teardown:function(){--Xa[b]===
0&&w.removeEventListener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,e,f){if(typeof d==="object"){for(var h in d)this[b](h,e,d[h],f);return this}if(c.isFunction(e)||e===false){f=e;e=B}var m=b==="one"?c.proxy(f,function(p){c(this).unbind(p,m);return f.apply(this,arguments)}):f;if(d==="unload"&&b!=="one")this.one(d,e,f);else{h=0;for(var l=this.length;h<l;h++)c.event.add(this[h],d,m,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,
a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,e){return this.live(b,d,e,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<
b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var f=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,f+1);e.preventDefault();return b[f].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var M={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,e,f,h){var m,l=0,p,A,v=h||this.selector;h=h?this:c(this.context);if(typeof d==="object"&&
!d.preventDefault){for(m in d)h[b](m,e,d[m],v);return this}if(c.isFunction(e)){f=e;e=B}for(d=(d||"").split(" ");(m=d[l++])!=null;){p=Fa.exec(m);A="";if(p){A=p[0];m=m.replace(Fa,"")}if(m==="hover")d.push("mouseenter"+A,"mouseleave"+A);else{p=m;if(m==="focus"||m==="blur"){d.push(M[m]+A);m+=A}else m=(M[m]||m)+A;if(b==="live"){A=0;for(var H=h.length;A<H;A++)c.event.add(h[A],"live."+U(m,v),{data:e,selector:v,handler:f,origType:m,origHandler:f,preType:p})}else h.unbind("live."+U(m,v),f)}}return this}});
c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(d,e){if(e==null){e=d;d=null}return arguments.length>0?this.bind(b,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});R.attachEvent&&!R.addEventListener&&c(R).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});
(function(){function a(g,i,n,q,r,u){r=0;for(var D=q.length;r<D;r++){var I=q[r];if(I){var Y=false;for(I=I[g];I;){if(I.sizcache===n){Y=q[I.sizset];break}if(I.nodeType===1&&!u){I.sizcache=n;I.sizset=r}if(I.nodeName.toLowerCase()===i){Y=I;break}I=I[g]}q[r]=Y}}}function b(g,i,n,q,r,u){r=0;for(var D=q.length;r<D;r++){var I=q[r];if(I){var Y=false;for(I=I[g];I;){if(I.sizcache===n){Y=q[I.sizset];break}if(I.nodeType===1){if(!u){I.sizcache=n;I.sizset=r}if(typeof i!=="string"){if(I===i){Y=true;break}}else if(l.filter(i,
[I]).length>0){Y=I;break}}I=I[g]}q[r]=Y}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,f=Object.prototype.toString,h=false,m=true;[0,0].sort(function(){m=false;return 0});var l=function(g,i,n,q){n=n||[];var r=i=i||w;if(i.nodeType!==1&&i.nodeType!==9)return[];if(!g||typeof g!=="string")return n;var u,D,I,Y,ua,ya=true,za=l.isXML(i),V=[],Pa=g;do{d.exec("");if(u=d.exec(Pa)){Pa=u[3];V.push(u[1]);if(u[2]){Y=
u[3];break}}}while(u);if(V.length>1&&A.exec(g))if(V.length===2&&p.relative[V[0]])D=xa(V[0]+V[1],i);else for(D=p.relative[V[0]]?[i]:l(V.shift(),i);V.length;){g=V.shift();if(p.relative[g])g+=V.shift();D=xa(g,D)}else{if(!q&&V.length>1&&i.nodeType===9&&!za&&p.match.ID.test(V[0])&&!p.match.ID.test(V[V.length-1])){u=l.find(V.shift(),i,za);i=u.expr?l.filter(u.expr,u.set)[0]:u.set[0]}if(i){u=q?{expr:V.pop(),set:Q(q)}:l.find(V.pop(),V.length===1&&(V[0]==="~"||V[0]==="+")&&i.parentNode?i.parentNode:i,za);D=
u.expr?l.filter(u.expr,u.set):u.set;if(V.length>0)I=Q(D);else ya=false;for(;V.length;){u=ua=V.pop();if(p.relative[ua])u=V.pop();else ua="";if(u==null)u=i;p.relative[ua](I,u,za)}}else I=[]}I||(I=D);I||l.error(ua||g);if(f.call(I)==="[object Array]")if(ya)if(i&&i.nodeType===1)for(g=0;I[g]!=null;g++){if(I[g]&&(I[g]===true||I[g].nodeType===1&&l.contains(i,I[g])))n.push(D[g])}else for(g=0;I[g]!=null;g++)I[g]&&I[g].nodeType===1&&n.push(D[g]);else n.push.apply(n,I);else Q(I,n);if(Y){l(Y,r,n,q);l.uniqueSort(n)}return n};
l.uniqueSort=function(g){if(C){h=m;g.sort(C);if(h)for(var i=1;i<g.length;i++)g[i]===g[i-1]&&g.splice(i--,1)}return g};l.matches=function(g,i){return l(g,null,null,i)};l.matchesSelector=function(g,i){return l(i,null,null,[g]).length>0};l.find=function(g,i,n){var q;if(!g)return[];for(var r=0,u=p.order.length;r<u;r++){var D,I=p.order[r];if(D=p.leftMatch[I].exec(g)){var Y=D[1];D.splice(1,1);if(Y.substr(Y.length-1)!=="\\"){D[1]=(D[1]||"").replace(/\\/g,"");q=p.find[I](D,i,n);if(q!=null){g=g.replace(p.match[I],
"");break}}}}q||(q=i.getElementsByTagName("*"));return{set:q,expr:g}};l.filter=function(g,i,n,q){for(var r,u,D=g,I=[],Y=i,ua=i&&i[0]&&l.isXML(i[0]);g&&i.length;){for(var ya in p.filter)if((r=p.leftMatch[ya].exec(g))!=null&&r[2]){var za,V,Pa=p.filter[ya];V=r[1];u=false;r.splice(1,1);if(V.substr(V.length-1)!=="\\"){if(Y===I)I=[];if(p.preFilter[ya])if(r=p.preFilter[ya](r,Y,n,I,q,ua)){if(r===true)continue}else u=za=true;if(r)for(var j=0;(V=Y[j])!=null;j++)if(V){za=Pa(V,r,j,Y);var t=q^!!za;if(n&&za!=null)if(t)u=
true;else Y[j]=false;else if(t){I.push(V);u=true}}if(za!==B){n||(Y=I);g=g.replace(p.match[ya],"");if(!u)return[];break}}}if(g===D)if(u==null)l.error(g);else break;D=g}return Y};l.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var p=l.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,i){var n=typeof i==="string",q=n&&!/\W/.test(i);n=n&&!q;if(q)i=i.toLowerCase();q=0;for(var r=g.length,
u;q<r;q++)if(u=g[q]){for(;(u=u.previousSibling)&&u.nodeType!==1;);g[q]=n||u&&u.nodeName.toLowerCase()===i?u||false:u===i}n&&l.filter(i,g,true)},">":function(g,i){var n,q=typeof i==="string",r=0,u=g.length;if(q&&!/\W/.test(i))for(i=i.toLowerCase();r<u;r++){if(n=g[r]){n=n.parentNode;g[r]=n.nodeName.toLowerCase()===i?n:false}}else{for(;r<u;r++)if(n=g[r])g[r]=q?n.parentNode:n.parentNode===i;q&&l.filter(i,g,true)}},"":function(g,i,n){var q,r=e++,u=b;if(typeof i==="string"&&!/\W/.test(i)){q=i=i.toLowerCase();
u=a}u("parentNode",i,r,g,q,n)},"~":function(g,i,n){var q,r=e++,u=b;if(typeof i==="string"&&!/\W/.test(i)){q=i=i.toLowerCase();u=a}u("previousSibling",i,r,g,q,n)}},find:{ID:function(g,i,n){if(typeof i.getElementById!=="undefined"&&!n)return(g=i.getElementById(g[1]))&&g.parentNode?[g]:[]},NAME:function(g,i){if(typeof i.getElementsByName!=="undefined"){var n=[];i=i.getElementsByName(g[1]);for(var q=0,r=i.length;q<r;q++)i[q].getAttribute("name")===g[1]&&n.push(i[q]);return n.length===0?null:n}},TAG:function(g,
i){return i.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,i,n,q,r,u){g=" "+g[1].replace(/\\/g,"")+" ";if(u)return g;u=0;for(var D;(D=i[u])!=null;u++)if(D)if(r^(D.className&&(" "+D.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))n||q.push(D);else if(n)i[u]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var i=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&
"0n+"+g[2]||g[2]);g[2]=i[1]+(i[2]||1)-0;g[3]=i[3]-0}g[0]=e++;return g},ATTR:function(g,i,n,q,r,u){i=g[1].replace(/\\/g,"");if(!u&&p.attrMap[i])g[1]=p.attrMap[i];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,i,n,q,r){if(g[1]==="not")if((d.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=l(g[3],null,null,i);else{g=l.filter(g[3],i,n,true^r);n||q.push.apply(q,g);return false}else if(p.match.POS.test(g[0])||p.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},
filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},has:function(g,i,n){return!!l(n[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===
g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,i){return i===0},last:function(g,i,n,q){return i===q.length-1},even:function(g,i){return i%2===
0},odd:function(g,i){return i%2===1},lt:function(g,i,n){return i<n[3]-0},gt:function(g,i,n){return i>n[3]-0},nth:function(g,i,n){return n[3]-0===i},eq:function(g,i,n){return n[3]-0===i}},filter:{PSEUDO:function(g,i,n,q){var r=i[1],u=p.filters[r];if(u)return u(g,n,i,q);else if(r==="contains")return(g.textContent||g.innerText||l.getText([g])||"").indexOf(i[3])>=0;else if(r==="not"){i=i[3];n=0;for(q=i.length;n<q;n++)if(i[n]===g)return false;return true}else l.error("Syntax error, unrecognized expression: "+
r)},CHILD:function(g,i){var n=i[1],q=g;switch(n){case "only":case "first":for(;q=q.previousSibling;)if(q.nodeType===1)return false;if(n==="first")return true;q=g;case "last":for(;q=q.nextSibling;)if(q.nodeType===1)return false;return true;case "nth":n=i[2];var r=i[3];if(n===1&&r===0)return true;i=i[0];var u=g.parentNode;if(u&&(u.sizcache!==i||!g.nodeIndex)){var D=0;for(q=u.firstChild;q;q=q.nextSibling)if(q.nodeType===1)q.nodeIndex=++D;u.sizcache=i}g=g.nodeIndex-r;return n===0?g===0:g%n===0&&g/n>=
0}},ID:function(g,i){return g.nodeType===1&&g.getAttribute("id")===i},TAG:function(g,i){return i==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===i},CLASS:function(g,i){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(i)>-1},ATTR:function(g,i){var n=i[1];g=p.attrHandle[n]?p.attrHandle[n](g):g[n]!=null?g[n]:g.getAttribute(n);n=g+"";var q=i[2];i=i[4];return g==null?q==="!=":q==="="?n===i:q==="*="?n.indexOf(i)>=0:q==="~="?(" "+n+" ").indexOf(i)>=0:!i?n&&g!==false:q==="!="?n!==i:q==="^="?
n.indexOf(i)===0:q==="$="?n.substr(n.length-i.length)===i:q==="|="?n===i||n.substr(0,i.length+1)===i+"-":false},POS:function(g,i,n,q){var r=p.setFilters[i[2]];if(r)return r(g,n,i,q)}}},A=p.match.POS,v=function(g,i){return"\\"+(i-0+1)};for(var H in p.match){p.match[H]=new RegExp(p.match[H].source+/(?![^\[]*\])(?![^\(]*\))/.source);p.leftMatch[H]=new RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[H].source.replace(/\\(\d+)/g,v))}var Q=function(g,i){g=Array.prototype.slice.call(g,0);if(i){i.push.apply(i,g);
return i}return g};try{Array.prototype.slice.call(w.documentElement.childNodes,0)}catch(fa){Q=function(g,i){var n=0;i=i||[];if(f.call(g)==="[object Array]")Array.prototype.push.apply(i,g);else if(typeof g.length==="number")for(var q=g.length;n<q;n++)i.push(g[n]);else for(;g[n];n++)i.push(g[n]);return i}}var C,da;if(w.documentElement.compareDocumentPosition)C=function(g,i){if(g===i){h=true;return 0}if(!g.compareDocumentPosition||!i.compareDocumentPosition)return g.compareDocumentPosition?-1:1;return g.compareDocumentPosition(i)&
4?-1:1};else{C=function(g,i){var n,q,r=[],u=[];n=g.parentNode;q=i.parentNode;var D=n;if(g===i){h=true;return 0}else if(n===q)return da(g,i);else if(n){if(!q)return 1}else return-1;for(;D;){r.unshift(D);D=D.parentNode}for(D=q;D;){u.unshift(D);D=D.parentNode}n=r.length;q=u.length;for(D=0;D<n&&D<q;D++)if(r[D]!==u[D])return da(r[D],u[D]);return D===n?da(g,u[D],-1):da(r[D],i,1)};da=function(g,i,n){if(g===i)return n;for(g=g.nextSibling;g;){if(g===i)return-1;g=g.nextSibling}return 1}}l.getText=function(g){for(var i=
"",n,q=0;g[q];q++){n=g[q];if(n.nodeType===3||n.nodeType===4)i+=n.nodeValue;else if(n.nodeType!==8)i+=l.getText(n.childNodes)}return i};(function(){var g=w.createElement("div"),i="script"+(new Date).getTime(),n=w.documentElement;g.innerHTML="<a name='"+i+"'/>";n.insertBefore(g,n.firstChild);if(w.getElementById(i)){p.find.ID=function(q,r,u){if(typeof r.getElementById!=="undefined"&&!u)return(r=r.getElementById(q[1]))?r.id===q[1]||typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id").nodeValue===
q[1]?[r]:B:[]};p.filter.ID=function(q,r){var u=typeof q.getAttributeNode!=="undefined"&&q.getAttributeNode("id");return q.nodeType===1&&u&&u.nodeValue===r}}n.removeChild(g);n=g=null})();(function(){var g=w.createElement("div");g.appendChild(w.createComment(""));if(g.getElementsByTagName("*").length>0)p.find.TAG=function(i,n){n=n.getElementsByTagName(i[1]);if(i[1]==="*"){i=[];for(var q=0;n[q];q++)n[q].nodeType===1&&i.push(n[q]);n=i}return n};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!==
"undefined"&&g.firstChild.getAttribute("href")!=="#")p.attrHandle.href=function(i){return i.getAttribute("href",2)};g=null})();w.querySelectorAll&&function(){var g=l,i=w.createElement("div");i.innerHTML="<p class='TEST'></p>";if(!(i.querySelectorAll&&i.querySelectorAll(".TEST").length===0)){l=function(q,r,u,D){r=r||w;q=q.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!D&&!l.isXML(r))if(r.nodeType===9)try{return Q(r.querySelectorAll(q),u)}catch(I){}else if(r.nodeType===1&&r.nodeName.toLowerCase()!==
"object"){var Y=r.getAttribute("id"),ua=Y||"__sizzle__";Y||r.setAttribute("id",ua);try{return Q(r.querySelectorAll("#"+ua+" "+q),u)}catch(ya){}finally{Y||r.removeAttribute("id")}}return g(q,r,u,D)};for(var n in g)l[n]=g[n];i=null}}();(function(){var g=w.documentElement,i=g.matchesSelector||g.mozMatchesSelector||g.webkitMatchesSelector||g.msMatchesSelector,n=false;try{i.call(w.documentElement,"[test!='']:sizzle")}catch(q){n=true}if(i)l.matchesSelector=function(r,u){u=u.replace(/\=\s*([^'"\]]*)\s*\]/g,
"='$1']");if(!l.isXML(r))try{if(n||!p.match.PSEUDO.test(u)&&!/!=/.test(u))return i.call(r,u)}catch(D){}return l(u,null,null,[r]).length>0}})();(function(){var g=w.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){p.order.splice(1,0,"CLASS");p.find.CLASS=function(i,n,q){if(typeof n.getElementsByClassName!=="undefined"&&
!q)return n.getElementsByClassName(i[1])};g=null}}})();l.contains=w.documentElement.contains?function(g,i){return g!==i&&(g.contains?g.contains(i):true)}:w.documentElement.compareDocumentPosition?function(g,i){return!!(g.compareDocumentPosition(i)&16)}:function(){return false};l.isXML=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false};var xa=function(g,i){var n,q=[],r="";for(i=i.nodeType?[i]:i;n=p.match.PSEUDO.exec(g);){r+=n[0];g=g.replace(p.match.PSEUDO,"")}g=
p.relative[g]?g+"*":g;n=0;for(var u=i.length;n<u;n++)l(g,i[n],q);return l.filter(r,q)};c.find=l;c.expr=l.selectors;c.expr[":"]=c.expr.filters;c.unique=l.uniqueSort;c.text=l.getText;c.isXMLDoc=l.isXML;c.contains=l.contains})();var ha=/Until$/,S=/^(?:parents|prevUntil|prevAll)/,Qa=/,/,gb=/^.[^:#\[\.,]*$/,nb=Array.prototype.slice,hb=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=this.pushStack("","find",a),d=0,e=0,f=this.length;e<f;e++){d=b.length;c.find(a,this[e],b);if(e>0)for(var h=d;h<b.length;h++)for(var m=
0;m<d;m++)if(b[m]===b[h]){b.splice(h--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(ja(this,a,false),"not",a)},filter:function(a){return this.pushStack(ja(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,b){var d=[],e,f,h=this[0];if(c.isArray(a)){var m,l={},p=1;if(h&&a.length){e=0;for(f=a.length;e<f;e++){m=a[e];
l[m]||(l[m]=c.expr.match.POS.test(m)?c(m,b||this.context):m)}for(;h&&h.ownerDocument&&h!==b;){for(m in l){a=l[m];if(a.jquery?a.index(h)>-1:c(h).is(a))d.push({selector:m,elem:h,level:p})}h=h.parentNode;p++}}return d}m=hb.test(a)?c(a,b||this.context):null;e=0;for(f=this.length;e<f;e++)for(h=this[e];h;)if(m?m.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===b)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a||
typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(W(a[0])||W(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",
d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?
a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);ha.test(a)||(e=d);if(e&&typeof e==="string")f=c.filter(e,f);f=this.length>1?c.unique(f):f;if((this.length>1||Qa.test(e))&&S.test(a))f=f.reverse();return this.pushStack(f,a,nb.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=
a[b];a&&a.nodeType!==9&&(d===B||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Sa=/ jQuery\d+="(?:\d+|null)"/g,Na=/^\s+/,La=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,ab=/<([\w:]+)/,jb=/<tbody/i,bb=/<|&#?\w+;/,cb=/<(?:script|object|embed|option|style)/i,
kb=/checked\s*(?:[^=]|=\s*.checked.)/i,K=/\=([^="'>\s]+\/)>/g,la={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};la.optgroup=la.option;la.tbody=la.tfoot=la.colgroup=la.caption=la.thead;la.th=la.td;if(!c.support.htmlSerialize)la._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==B)return this.empty().append((this[0]&&this[0].ownerDocument||w).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===1){c.cleanData(e.getElementsByTagName("*"));c.cleanData([e])}e.parentNode&&e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,e=this.ownerDocument;if(!d){d=e.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Sa,"").replace(K,'="$1">').replace(Na,"")],e)[0]}else return this.cloneNode(true)});if(a===true){ka(this,b);ka(this.find("*"),b.find("*"))}return b},html:function(a){if(a===B)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Sa,""):null;
else if(typeof a==="string"&&!cb.test(a)&&(c.support.leadingWhitespace||!Na.test(a))&&!la[(ab.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(La,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(e){this.empty().append(a)}}else c.isFunction(a)?this.each(function(f){var h=c(this);h.html(a.call(this,f,h.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=
c(this),e=d.html();d.replaceWith(a.call(this,b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){var e,f,h,m=a[0],l=[];if(!c.support.checkClone&&arguments.length===3&&typeof m==="string"&&kb.test(m))return this.each(function(){c(this).domManip(a,
b,d,true)});if(c.isFunction(m))return this.each(function(v){var H=c(this);a[0]=m.call(this,v,b?H.html():B);H.domManip(a,b,d)});if(this[0]){e=m&&m.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,l);h=e.fragment;if(f=h.childNodes.length===1?(h=h.firstChild):h.firstChild){b=b&&c.nodeName(f,"tr");for(var p=0,A=this.length;p<A;p++)d.call(b?ba(this[p],f):this[p],p>0||e.cacheable||this.length>1?h.cloneNode(true):h)}l.length&&c.each(l,
oa)}return this}});c.buildFragment=function(a,b,d){var e,f,h;b=b&&b[0]?b[0].ownerDocument||b[0]:w;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===w&&!cb.test(a[0])&&(c.support.checkClone||!kb.test(a[0]))){f=true;if(h=c.fragments[a[0]])if(h!==1)e=h}if(!e){e=b.createDocumentFragment();c.clean(a,b,e,d)}if(f)c.fragments[a[0]]=h?e:1;return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},
function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{f=0;for(var h=d.length;f<h;f++){var m=(f>0?this.clone(true):this).get();c(d[f])[b](m);e=e.concat(m)}return this.pushStack(e,a,d.selector)}}});c.extend({clean:function(a,b,d,e){b=b||w;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||w;for(var f=[],h=0,m;(m=a[h])!=null;h++){if(typeof m===
"number")m+="";if(m){if(typeof m==="string"&&!bb.test(m))m=b.createTextNode(m);else if(typeof m==="string"){m=m.replace(La,"<$1></$2>");var l=(ab.exec(m)||["",""])[1].toLowerCase(),p=la[l]||la._default,A=p[0],v=b.createElement("div");for(v.innerHTML=p[1]+m+p[2];A--;)v=v.lastChild;if(!c.support.tbody){A=jb.test(m);l=l==="table"&&!A?v.firstChild&&v.firstChild.childNodes:p[1]==="<table>"&&!A?v.childNodes:[];for(p=l.length-1;p>=0;--p)c.nodeName(l[p],"tbody")&&!l[p].childNodes.length&&l[p].parentNode.removeChild(l[p])}!c.support.leadingWhitespace&&
Na.test(m)&&v.insertBefore(b.createTextNode(Na.exec(m)[0]),v.firstChild);m=v.childNodes}if(m.nodeType)f.push(m);else f=c.merge(f,m)}}if(d)for(h=0;f[h];h++)if(e&&c.nodeName(f[h],"script")&&(!f[h].type||f[h].type.toLowerCase()==="text/javascript"))e.push(f[h].parentNode?f[h].parentNode.removeChild(f[h]):f[h]);else{f[h].nodeType===1&&f.splice.apply(f,[h+1,0].concat(c.makeArray(f[h].getElementsByTagName("script"))));d.appendChild(f[h])}return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,
h=c.support.deleteExpando,m=0,l;(l=a[m])!=null;m++)if(!(l.nodeName&&c.noData[l.nodeName.toLowerCase()]))if(d=l[c.expando]){if((b=e[d])&&b.events)for(var p in b.events)f[p]?c.event.remove(l,p):c.removeEvent(l,p,b.handle);if(h)delete l[c.expando];else l.removeAttribute&&l.removeAttribute(c.expando);delete e[d]}}});var ma=/alpha\([^)]*\)/i,Oa=/opacity=([^)]*)/,Ma=/-([a-z])/ig,Za=/([A-Z])/g,ea=/^-?\d+(?:px)?$/i,va=/^-?\d/,Ia={position:"absolute",visibility:"hidden",display:"block"},$a=["Left","Right"],
ob=["Top","Bottom"],na,Ha,Ea,Ra=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===B)return this;return c.access(this,a,b,true,function(d,e,f){return f!==B?c.style(d,e,f):c.css(d,e)})};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){a=na(a,"opacity","opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,
b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var f,h=c.camelCase(b),m=a.style,l=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==B){if(!(typeof d==="number"&&isNaN(d)||d==null)){if(typeof d==="number"&&!c.cssNumber[h])d+="px";if(!l||!("set"in l)||(d=l.set(a,d))!==B)try{m[b]=d}catch(p){}}}else{if(l&&"get"in l&&(f=l.get(a,false,e))!==B)return f;return m[b]}}},css:function(a,b,d){var e,f=c.camelCase(b),h=c.cssHooks[f];b=c.cssProps[f]||f;if(h&&"get"in h&&(e=h.get(a,true,d))!==B)return e;else if(na)return na(a,
b,f)},swap:function(a,b,d){var e={};for(var f in b){e[f]=a.style[f];a.style[f]=b[f]}d.call(a);for(f in b)a.style[f]=e[f]},camelCase:function(a){return a.replace(Ma,Ra)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){var h;if(e){if(d.offsetWidth!==0)h=sa(d,b,f);else c.swap(d,Ia,function(){h=sa(d,b,f)});if(h<=0){h=na(d,b,b);if(h==="0px"&&Ea)h=Ea(d,b,b);if(h!=null)return h===""||h==="auto"?"0px":h}if(h<0||h==null){h=d.style[b];return h===""||h==="auto"?"0px":
h}return typeof h==="string"?h:h+"px"}},set:function(d,e){if(ea.test(e)){e=parseFloat(e);if(e>=0)return e+"px"}else return e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return Oa.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){a=a.style;a.zoom=1;b=c.isNaN(b)?"":"alpha(opacity="+b*100+")";var d=a.filter||"";a.filter=ma.test(d)?d.replace(ma,b):a.filter+" "+b}};if(w.defaultView&&w.defaultView.getComputedStyle)Ha=
function(a,b,d){var e;d=d.replace(Za,"-$1").toLowerCase();if(!(b=a.ownerDocument.defaultView))return B;if(b=b.getComputedStyle(a,null)){e=b.getPropertyValue(d);if(e===""&&!c.contains(a.ownerDocument.documentElement,a))e=c.style(a,d)}return e};if(w.documentElement.currentStyle)Ea=function(a,b){var d,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;if(!ea.test(f)&&va.test(f)){d=h.left;e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=b==="fontSize"?"1em":f||0;f=h.pixelLeft+"px";h.left=
d;a.runtimeStyle.left=e}return f===""?"auto":f};na=Ha||Ea;if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var k=c.now(),o=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,s=/^(?:select|textarea)/i,x=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
F=/^(?:GET|HEAD)$/,T=/\[\]$/,N=/\=\?(&|$)/,aa=/\?/,ia=/([?&])_=[^&]*/,ib=/^(\w+:)?\/\/([^\/?#]+)/,pb=/%20/g,wb=/#.*$/,ub=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&ub)return ub.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var f=a.slice(e,a.length);a=a.slice(0,e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",data:b,
complete:function(m,l){if(l==="success"||l==="notmodified")h.html(f?c("<div>").append(m.responseText.replace(o,"")).find(f):m.responseText);d&&h.each(d,[m.responseText,l,m])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||s.test(this.nodeName)||x.test(this.type))}).map(function(a,b){a=c(this).val();
return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,e){if(c.isFunction(b)){e=e||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,
b,d,e){if(c.isFunction(b)){e=e||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:function(){return new R.XMLHttpRequest},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},
ajax:function(a){var b=c.extend(true,{},c.ajaxSettings,a),d,e,f,h=b.type.toUpperCase(),m=F.test(h);b.url=b.url.replace(wb,"");b.context=a&&a.context!=null?a.context:b;if(b.data&&b.processData&&typeof b.data!=="string")b.data=c.param(b.data,b.traditional);if(b.dataType==="jsonp"){if(h==="GET")N.test(b.url)||(b.url+=(aa.test(b.url)?"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!N.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if(b.dataType==="json"&&
(b.data&&N.test(b.data)||N.test(b.url))){d=b.jsonpCallback||"jsonp"+k++;if(b.data)b.data=(b.data+"").replace(N,"="+d+"$1");b.url=b.url.replace(N,"="+d+"$1");b.dataType="script";var l=R[d];R[d]=function(q){if(c.isFunction(l))l(q);else{R[d]=B;try{delete R[d]}catch(r){}}f=q;c.handleSuccess(b,C,e,f);c.handleComplete(b,C,e,f);v&&v.removeChild(H)}}if(b.dataType==="script"&&b.cache===null)b.cache=false;if(b.cache===false&&m){var p=c.now(),A=b.url.replace(ia,"$1_="+p);b.url=A+(A===b.url?(aa.test(b.url)?"&":
"?")+"_="+p:"")}if(b.data&&m)b.url+=(aa.test(b.url)?"&":"?")+b.data;b.global&&c.active++===0&&c.event.trigger("ajaxStart");p=(p=ib.exec(b.url))&&(p[1]&&p[1].toLowerCase()!==location.protocol||p[2].toLowerCase()!==location.host);if(b.dataType==="script"&&h==="GET"&&p){var v=w.getElementsByTagName("head")[0]||w.documentElement,H=w.createElement("script");if(b.scriptCharset)H.charset=b.scriptCharset;H.src=b.url;if(!d){var Q=false;H.onload=H.onreadystatechange=function(){if(!Q&&(!this.readyState||this.readyState===
"loaded"||this.readyState==="complete")){Q=true;c.handleSuccess(b,C,e,f);c.handleComplete(b,C,e,f);H.onload=H.onreadystatechange=null;v&&H.parentNode&&v.removeChild(H)}}}v.insertBefore(H,v.firstChild);return B}var fa=false,C=b.xhr();if(C){b.username?C.open(h,b.url,b.async,b.username,b.password):C.open(h,b.url,b.async);try{if(b.data!=null&&!m||a&&a.contentType)C.setRequestHeader("Content-Type",b.contentType);if(b.ifModified){c.lastModified[b.url]&&C.setRequestHeader("If-Modified-Since",c.lastModified[b.url]);
c.etag[b.url]&&C.setRequestHeader("If-None-Match",c.etag[b.url])}p||C.setRequestHeader("X-Requested-With","XMLHttpRequest");C.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(da){}if(b.beforeSend&&b.beforeSend.call(b.context,C,b)===false){b.global&&c.active--===1&&c.event.trigger("ajaxStop");C.abort();return false}b.global&&c.triggerGlobal(b,"ajaxSend",[C,b]);var xa=C.onreadystatechange=function(q){if(!C||C.readyState===0||
q==="abort"){fa||c.handleComplete(b,C,e,f);fa=true;if(C)C.onreadystatechange=c.noop}else if(!fa&&C&&(C.readyState===4||q==="timeout")){fa=true;C.onreadystatechange=c.noop;e=q==="timeout"?"timeout":!c.httpSuccess(C)?"error":b.ifModified&&c.httpNotModified(C,b.url)?"notmodified":"success";var r;if(e==="success")try{f=c.httpData(C,b.dataType,b)}catch(u){e="parsererror";r=u}if(e==="success"||e==="notmodified")d||c.handleSuccess(b,C,e,f);else c.handleError(b,C,e,r);d||c.handleComplete(b,C,e,f);q==="timeout"&&
C.abort();if(b.async)C=null}};try{var g=C.abort;C.abort=function(){C&&Function.prototype.call.call(g,C);xa("abort")}}catch(i){}b.async&&b.timeout>0&&setTimeout(function(){C&&!fa&&xa("timeout")},b.timeout);try{C.send(m||b.data==null?null:b.data)}catch(n){c.handleError(b,C,null,n);c.handleComplete(b,C,e,f)}b.async||xa();return C}},param:function(a,b){var d=[],e=function(h,m){m=c.isFunction(m)?m():m;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(m)};if(b===B)b=c.ajaxSettings.traditional;if(c.isArray(a)||
a.jquery)c.each(a,function(){e(this.name,this.value)});else for(var f in a)wa(f,a[f],b,e);return d.join("&").replace(pb,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,b,d);a.global&&c.triggerGlobal(a,
"ajaxComplete",[b,a]);a.global&&c.active--===1&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&a.context.url==null?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(e)c.etag[b]=e;return a.status===304},
httpData:function(a,b,d){var e=a.getResponseHeader("content-type")||"",f=b==="xml"||!b&&e.indexOf("xml")>=0;a=f?a.responseXML:a.responseText;f&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&e.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&e.indexOf("javascript")>=0)c.globalEval(a);return a}});if(R.ActiveXObject)c.ajaxSettings.xhr=function(){if(R.location.protocol!=="file:")try{return new R.XMLHttpRequest}catch(a){}try{return new R.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};
c.support.ajax=!!c.ajaxSettings.xhr();var rb={},xb=/^(?:toggle|show|hide)$/,yb=/^([+\-]=)?([\d+.\-]+)(.*)$/,mb,tb=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(pa("show",3),a,b,d);else{d=0;for(var e=this.length;d<e;d++){a=this[d];b=a.style.display;if(!c.data(a,"olddisplay")&&b==="none")b=a.style.display="";b===""&&c.css(a,"display")===
"none"&&c.data(a,"olddisplay",Ca(a.nodeName))}for(d=0;d<e;d++){a=this[d];b=a.style.display;if(b===""||b==="none")a.style.display=c.data(a,"olddisplay")||""}return this}},hide:function(a,b,d){if(a||a===0)return this.animate(pa("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){d=c.css(this[a],"display");d!=="none"&&c.data(this[a],"olddisplay",d)}for(a=0;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,
arguments);else a==null||e?this.each(function(){var f=e?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(pa("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var f=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(f.complete);return this[f.queue===false?"each":"queue"](function(){var h=c.extend({},f),m,l=this.nodeType===1,p=l&&c(this).is(":hidden"),A=this;for(m in a){var v=
c.camelCase(m);if(m!==v){a[v]=a[m];delete a[m];m=v}if(a[m]==="hide"&&p||a[m]==="show"&&!p)return h.complete.call(this);if(l&&(m==="height"||m==="width")){h.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(c.support.inlineBlockNeedsLayout)if(Ca(this.nodeName)==="inline")this.style.display="inline-block";else{this.style.display="inline";this.style.zoom=1}else this.style.display="inline-block"}if(c.isArray(a[m])){(h.specialEasing=
h.specialEasing||{})[m]=a[m][1];a[m]=a[m][0]}}if(h.overflow!=null)this.style.overflow="hidden";h.curAnim=c.extend({},a);c.each(a,function(H,Q){var fa=new c.fx(A,h,H);if(xb.test(Q))fa[Q==="toggle"?p?"show":"hide":Q](a);else{var C=yb.exec(Q),da=fa.cur()||0;if(C){Q=parseFloat(C[2]);var xa=C[3]||"px";if(xa!=="px"){c.style(A,H,(Q||1)+xa);da=(Q||1)/fa.cur()*da;c.style(A,H,da+xa)}if(C[1])Q=(C[1]==="-="?-1:1)*Q+da;fa.custom(da,Q,xa)}else fa.custom(da,Q,"")}});return true})},stop:function(a,b){var d=c.timers;
a&&this.queue([]);this.each(function(){for(var e=d.length-1;e>=0;e--)if(d[e].elem===this){b&&d[e](true);d.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:pa("show",1),slideUp:pa("hide",1),slideToggle:pa("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(d,e,f){return this.animate(b,d,e,f)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,
easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){e.queue!==false&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,d,e){return d+e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype=
{update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&a>-10000?a:0},custom:function(a,b,d){function e(m){return f.step(m)}var f=this,h=c.fx;this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=
this.state=0;e.elem=this.elem;if(e()&&c.timers.push(e)&&!mb)mb=setInterval(h.tick,h.interval)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var e in this.options.curAnim)if(this.options.curAnim[e]!==true)d=false;if(d){if(this.options.overflow!=null&&!c.support.shrinkWrapBlocks){var f=this.elem,h=this.options;c.each(["","X","Y"],function(l,p){f.style["overflow"+p]=h.overflow[l]})}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var m in this.options.curAnim)c.style(this.elem,m,this.options.orig[m]);this.options.complete.call(this.elem)}return false}else{a=
b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(mb);mb=null},speeds:{slow:600,
fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var zb=/^t(?:able|d|h)$/i,vb=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in w.documentElement?function(a){var b=
this[0],d;if(a)return this.each(function(m){c.offset.setOffset(this,a,m)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,h=f.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=f.body;f=ra(f);return{top:d.top+(f.pageYOffset||c.support.boxModel&&h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(f.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-
(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(v){c.offset.setOffset(this,a,v)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d,e=b.offsetParent,f=b,h=b.ownerDocument,m=h.documentElement,l=h.body;d=(h=h.defaultView)?h.getComputedStyle(b,null):b.currentStyle;for(var p=b.offsetTop,A=b.offsetLeft;(b=b.parentNode)&&b!==l&&b!==m;){if(c.offset.supportsFixedPosition&&d.position==="fixed")break;
d=h?h.getComputedStyle(b,null):b.currentStyle;p-=b.scrollTop;A-=b.scrollLeft;if(b===e){p+=b.offsetTop;A+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&zb.test(b.nodeName))){p+=parseFloat(d.borderTopWidth)||0;A+=parseFloat(d.borderLeftWidth)||0}f=e;e=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&d.overflow!=="visible"){p+=parseFloat(d.borderTopWidth)||0;A+=parseFloat(d.borderLeftWidth)||0}d=d}if(d.position==="relative"||d.position==="static"){p+=
l.offsetTop;A+=l.offsetLeft}if(c.offset.supportsFixedPosition&&d.position==="fixed"){p+=Math.max(m.scrollTop,l.scrollTop);A+=Math.max(m.scrollLeft,l.scrollLeft)}return{top:p,left:A}};c.offset={initialize:function(){var a=w.body,b=w.createElement("div"),d,e,f,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;f=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==5;this.doesAddBorderForTableAndCells=f.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),h=f.offset(),m=c.css(a,"top"),l=c.css(a,"left"),p=e==="absolute"&&c.inArray("auto",[m,l])>-1;e={};var A={};if(p)A=f.position();m=p?A.top:parseInt(m,
10)||0;l=p?A.left:parseInt(l,10)||0;if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=null)e.top=b.top-h.top+m;if(b.left!=null)e.left=b.left-h.left+l;"using"in b?b.using.call(a,e):f.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=vb.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],
"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||w.body;a&&!vb.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var f=this[0],h;if(!f)return null;if(e!==B)return this.each(function(){if(h=ra(this))h.scrollTo(!a?e:c(h).scrollLeft(),a?e:c(h).scrollTop());else this[d]=e});else return(h=ra(f))?"pageXOffset"in
h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:f[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(e){return this[0]?parseFloat(c.css(this[0],d,e?"margin":"border")):null};c.fn[d]=function(e){var f=this[0];if(!f)return e==null?null:this;if(c.isFunction(e))return this.each(function(m){var l=c(this);l[d](e.call(this,
m,l[d]()))});if(c.isWindow(f))return f.document.compatMode==="CSS1Compat"&&f.document.documentElement["client"+b]||f.document.body["client"+b];else if(f.nodeType===9)return Math.max(f.documentElement["client"+b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]);else if(e===B){f=c.css(f,d);var h=parseFloat(f);return c.isNaN(h)?f:h}else return this.css(d,typeof e==="string"?e:e+"px")}});typeof define!=="undefined"&&define("jquery",[],function(){return c})})(window);
