/*!
 * Copyright 2015 Apereo Foundation (AF) Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 *     http://opensource.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/**
 * Module that will export all known english country names with their ISO-3166-1
 * code. The list of countries exported by this module were derived from the
 * list of countries in the iso-3166-2 module:
 *
 *  https://github.com/olahol/iso-3166-2.js
 *
 * @param  {Object}     exports   Properties that are added on this object are exported
 */
define(['exports'], function(exports) {
    exports.countries = [
        {'name': 'Afghanistan', 'code': 'AF', 'icon': '/shared/vendor/img/flags/AF.png'},
        {'name': 'Albania', 'code': 'AL', 'icon': '/shared/vendor/img/flags/AL.png'},
        {'name': 'Algeria', 'code': 'DZ', 'icon': '/shared/vendor/img/flags/DZ.png'},
        {'name': 'Andorra', 'code': 'AD', 'icon': '/shared/vendor/img/flags/AD.png'},
        {'name': 'Angola', 'code': 'AO', 'icon': '/shared/vendor/img/flags/AO.png'},
        {'name': 'Antigua and Barbuda', 'code': 'AG', 'icon': '/shared/vendor/img/flags/AG.png'},
        {'name': 'Argentina', 'code': 'AR', 'icon': '/shared/vendor/img/flags/AR.png'},
        {'name': 'Armenia', 'code': 'AM', 'icon': '/shared/vendor/img/flags/AM.png'},
        {'name': 'Australia', 'code': 'AU', 'icon': '/shared/vendor/img/flags/AU.png'},
        {'name': 'Austria', 'code': 'AT', 'icon': '/shared/vendor/img/flags/AT.png'},
        {'name': 'Azerbaijan', 'code': 'AZ', 'icon': '/shared/vendor/img/flags/AZ.png'},
        {'name': 'Bahamas', 'code': 'BS', 'icon': '/shared/vendor/img/flags/BS.png'},
        {'name': 'Bahrain', 'code': 'BH', 'icon': '/shared/vendor/img/flags/BH.png'},
        {'name': 'Bangladesh', 'code': 'BD', 'icon': '/shared/vendor/img/flags/BD.png'},
        {'name': 'Barbados', 'code': 'BB', 'icon': '/shared/vendor/img/flags/BB.png'},
        {'name': 'Belarus', 'code': 'BY', 'icon': '/shared/vendor/img/flags/BY.png'},
        {'name': 'Belgium', 'code': 'BE', 'icon': '/shared/vendor/img/flags/BE.png'},
        {'name': 'Belize', 'code': 'BZ', 'icon': '/shared/vendor/img/flags/BZ.png'},
        {'name': 'Benin', 'code': 'BJ', 'icon': '/shared/vendor/img/flags/BJ.png'},
        {'name': 'Bermuda', 'code': 'BM', 'icon': '/shared/vendor/img/flags/BM.png'},
        {'name': 'Bhutan', 'code': 'BT', 'icon': '/shared/vendor/img/flags/BT.png'},
        {'name': 'Bolivia', 'code': 'BO', 'icon': '/shared/vendor/img/flags/BO.png'},
        {'name': 'Bonaire, Sint Eustatius and Saba', 'code': 'BQ', 'icon': '/shared/vendor/img/flags/BQ.png'},
        {'name': 'Bosnia and Herzegovina', 'code': 'BA', 'icon': '/shared/vendor/img/flags/BA.png'},
        {'name': 'Botswana', 'code': 'BW', 'icon': '/shared/vendor/img/flags/BW.png'},
        {'name': 'Brazil', 'code': 'BR', 'icon': '/shared/vendor/img/flags/BR.png'},
        {'name': 'Brunei Darussalam', 'code': 'BN', 'icon': '/shared/vendor/img/flags/BN.png'},
        {'name': 'Bulgaria', 'code': 'BG', 'icon': '/shared/vendor/img/flags/BG.png'},
        {'name': 'Burkina Faso', 'code': 'BF', 'icon': '/shared/vendor/img/flags/BF.png'},
        {'name': 'Burundi', 'code': 'BI', 'icon': '/shared/vendor/img/flags/BI.png'},
        {'name': 'Cambodia', 'code': 'KH', 'icon': '/shared/vendor/img/flags/KH.png'},
        {'name': 'Cameroon', 'code': 'CM', 'icon': '/shared/vendor/img/flags/CM.png'},
        {'name': 'Canada', 'code': 'CA', 'icon': '/shared/vendor/img/flags/CA.png'},
        {'name': 'Cape Verde', 'code': 'CV', 'icon': '/shared/vendor/img/flags/CV.png'},
        {'name': 'Cayman Islands', 'code': 'KY', 'icon': '/shared/vendor/img/flags/KY.png'},
        {'name': 'Central African Republic', 'code': 'CF', 'icon': '/shared/vendor/img/flags/CF.png'},
        {'name': 'Chad', 'code': 'TD', 'icon': '/shared/vendor/img/flags/TD.png'},
        {'name': 'Chile', 'code': 'CL', 'icon': '/shared/vendor/img/flags/CL.png'},
        {'name': 'China', 'code': 'CN', 'icon': '/shared/vendor/img/flags/CN.png'},
        {'name': 'Colombia', 'code': 'CO', 'icon': '/shared/vendor/img/flags/CO.png'},
        {'name': 'Comoros', 'code': 'KM', 'icon': '/shared/vendor/img/flags/KM.png'},
        {'name': 'Congo', 'code': 'CG', 'icon': '/shared/vendor/img/flags/CG.png'},
        {'name': 'Congo, The Democratic Republic Of The', 'code': 'CD', 'icon': '/shared/vendor/img/flags/CD.png'},
        {'name': 'Costa Rica', 'code': 'CR', 'icon': '/shared/vendor/img/flags/CR.png'},
        {'name': 'Croatia', 'code': 'HR', 'icon': '/shared/vendor/img/flags/HR.png'},
        {'name': 'Cuba', 'code': 'CU', 'icon': '/shared/vendor/img/flags/CU.png'},
        {'name': 'Cyprus', 'code': 'CY', 'icon': '/shared/vendor/img/flags/CY.png'},
        {'name': 'Czech Republic', 'code': 'CZ', 'icon': '/shared/vendor/img/flags/CZ.png'},
        {'name': 'Côte D\'Ivoire', 'code': 'CI', 'icon': '/shared/vendor/img/flags/CI.png'},
        {'name': 'Denmark', 'code': 'DK', 'icon': '/shared/vendor/img/flags/DK.png'},
        {'name': 'Djibouti', 'code': 'DJ', 'icon': '/shared/vendor/img/flags/DJ.png'},
        {'name': 'Dominica', 'code': 'DM', 'icon': '/shared/vendor/img/flags/DM.png'},
        {'name': 'Dominican Republic', 'code': 'DO', 'icon': '/shared/vendor/img/flags/DO.png'},
        {'name': 'Ecuador', 'code': 'EC', 'icon': '/shared/vendor/img/flags/EC.png'},
        {'name': 'Egypt', 'code': 'EG', 'icon': '/shared/vendor/img/flags/EG.png'},
        {'name': 'El Salvador', 'code': 'SV', 'icon': '/shared/vendor/img/flags/SV.png'},
        {'name': 'Equatorial Guinea', 'code': 'GQ', 'icon': '/shared/vendor/img/flags/GQ.png'},
        {'name': 'Eritrea', 'code': 'ER', 'icon': '/shared/vendor/img/flags/ER.png'},
        {'name': 'Estonia', 'code': 'EE', 'icon': '/shared/vendor/img/flags/EE.png'},
        {'name': 'Ethiopia', 'code': 'ET', 'icon': '/shared/vendor/img/flags/ET.png'},
        {'name': 'Fiji', 'code': 'FJ', 'icon': '/shared/vendor/img/flags/FJ.png'},
        {'name': 'Finland', 'code': 'FI', 'icon': '/shared/vendor/img/flags/FI.png'},
        {'name': 'France', 'code': 'FR', 'icon': '/shared/vendor/img/flags/FR.png'},
        {'name': 'French Southern Territories', 'code': 'TF', 'icon': '/shared/vendor/img/flags/TF.png'},
        {'name': 'Gabon', 'code': 'GA', 'icon': '/shared/vendor/img/flags/GA.png'},
        {'name': 'Gambia', 'code': 'GM', 'icon': '/shared/vendor/img/flags/GM.png'},
        {'name': 'Georgia', 'code': 'GE', 'icon': '/shared/vendor/img/flags/GE.png'},
        {'name': 'Germany', 'code': 'DE', 'icon': '/shared/vendor/img/flags/DE.png'},
        {'name': 'Ghana', 'code': 'GH', 'icon': '/shared/vendor/img/flags/GH.png'},
        {'name': 'Greece', 'code': 'GR', 'icon': '/shared/vendor/img/flags/GR.png'},
        {'name': 'Greenland', 'code': 'GL', 'icon': '/shared/vendor/img/flags/GL.png'},
        {'name': 'Grenada', 'code': 'GD', 'icon': '/shared/vendor/img/flags/GD.png'},
        {'name': 'Guatemala', 'code': 'GT', 'icon': '/shared/vendor/img/flags/GT.png'},
        {'name': 'Guinea', 'code': 'GN', 'icon': '/shared/vendor/img/flags/GN.png'},
        {'name': 'Guinea-Bissau', 'code': 'GW', 'icon': '/shared/vendor/img/flags/GW.png'},
        {'name': 'Guyana', 'code': 'GY', 'icon': '/shared/vendor/img/flags/GY.png'},
        {'name': 'Haiti', 'code': 'HT', 'icon': '/shared/vendor/img/flags/HT.png'},
        {'name': 'Honduras', 'code': 'HN', 'icon': '/shared/vendor/img/flags/HN.png'},
        {'name': 'Hungary', 'code': 'HU', 'icon': '/shared/vendor/img/flags/HU.png'},
        {'name': 'Iceland', 'code': 'IS', 'icon': '/shared/vendor/img/flags/IS.png'},
        {'name': 'India', 'code': 'IN', 'icon': '/shared/vendor/img/flags/IN.png'},
        {'name': 'Indonesia', 'code': 'ID', 'icon': '/shared/vendor/img/flags/ID.png'},
        {'name': 'Iran', 'code': 'IR', 'icon': '/shared/vendor/img/flags/IR.png'},
        {'name': 'Iraq', 'code': 'IQ', 'icon': '/shared/vendor/img/flags/IQ.png'},
        {'name': 'Ireland', 'code': 'IE', 'icon': '/shared/vendor/img/flags/IE.png'},
        {'name': 'Israel', 'code': 'IL', 'icon': '/shared/vendor/img/flags/IL.png'},
        {'name': 'Italy', 'code': 'IT', 'icon': '/shared/vendor/img/flags/IT.png'},
        {'name': 'Jamaica', 'code': 'JM', 'icon': '/shared/vendor/img/flags/JM.png'},
        {'name': 'Japan', 'code': 'JP', 'icon': '/shared/vendor/img/flags/JP.png'},
        {'name': 'Jordan', 'code': 'JO', 'icon': '/shared/vendor/img/flags/JO.png'},
        {'name': 'Kazakhstan', 'code': 'KZ', 'icon': '/shared/vendor/img/flags/KZ.png'},
        {'name': 'Kenya', 'code': 'KE', 'icon': '/shared/vendor/img/flags/KE.png'},
        {'name': 'Kiribati', 'code': 'KI', 'icon': '/shared/vendor/img/flags/KI.png'},
        {'name': 'Korea, Democratic People\'s Republic Of', 'code': 'KP', 'icon': '/shared/vendor/img/flags/KP.png'},
        {'name': 'Korea, Republic of', 'code': 'KR', 'icon': '/shared/vendor/img/flags/KR.png'},
        {'name': 'Kuwait', 'code': 'KW', 'icon': '/shared/vendor/img/flags/KW.png'},
        {'name': 'Kyrgyzstan', 'code': 'KG', 'icon': '/shared/vendor/img/flags/KG.png'},
        {'name': 'Laos', 'code': 'LA', 'icon': '/shared/vendor/img/flags/LA.png'},
        {'name': 'Latvia', 'code': 'LV', 'icon': '/shared/vendor/img/flags/LV.png'},
        {'name': 'Lebanon', 'code': 'LB', 'icon': '/shared/vendor/img/flags/LB.png'},
        {'name': 'Lesotho', 'code': 'LS', 'icon': '/shared/vendor/img/flags/LS.png'},
        {'name': 'Liberia', 'code': 'LR', 'icon': '/shared/vendor/img/flags/LR.png'},
        {'name': 'Libya', 'code': 'LY', 'icon': '/shared/vendor/img/flags/LY.png'},
        {'name': 'Liechtenstein', 'code': 'LI', 'icon': '/shared/vendor/img/flags/LI.png'},
        {'name': 'Lithuania', 'code': 'LT', 'icon': '/shared/vendor/img/flags/LT.png'},
        {'name': 'Luxembourg', 'code': 'LU', 'icon': '/shared/vendor/img/flags/LU.png'},
        {'name': 'Macao', 'code': 'MO', 'icon': '/shared/vendor/img/flags/MO.png'},
        {'name': 'Macedonia, the Former Yugoslav Republic Of', 'code': 'MK', 'icon': '/shared/vendor/img/flags/MK.png'},
        {'name': 'Madagascar', 'code': 'MG', 'icon': '/shared/vendor/img/flags/MG.png'},
        {'name': 'Malawi', 'code': 'MW', 'icon': '/shared/vendor/img/flags/MW.png'},
        {'name': 'Malaysia', 'code': 'MY', 'icon': '/shared/vendor/img/flags/MY.png'},
        {'name': 'Maldives', 'code': 'MV', 'icon': '/shared/vendor/img/flags/MV.png'},
        {'name': 'Mali', 'code': 'ML', 'icon': '/shared/vendor/img/flags/ML.png'},
        {'name': 'Malta', 'code': 'MT', 'icon': '/shared/vendor/img/flags/MT.png'},
        {'name': 'Marshall Islands', 'code': 'MH', 'icon': '/shared/vendor/img/flags/MH.png'},
        {'name': 'Mauritania', 'code': 'MR', 'icon': '/shared/vendor/img/flags/MR.png'},
        {'name': 'Mauritius', 'code': 'MU', 'icon': '/shared/vendor/img/flags/MU.png'},
        {'name': 'Mexico', 'code': 'MX', 'icon': '/shared/vendor/img/flags/MX.png'},
        {'name': 'Micronesia, Federated States Of', 'code': 'FM', 'icon': '/shared/vendor/img/flags/FM.png'},
        {'name': 'Moldova', 'code': 'MD', 'icon': '/shared/vendor/img/flags/MD.png'},
        {'name': 'Monaco', 'code': 'MC', 'icon': '/shared/vendor/img/flags/MC.png'},
        {'name': 'Mongolia', 'code': 'MN', 'icon': '/shared/vendor/img/flags/MN.png'},
        {'name': 'Montenegro', 'code': 'ME', 'icon': '/shared/vendor/img/flags/ME.png'},
        {'name': 'Morocco', 'code': 'MA', 'icon': '/shared/vendor/img/flags/MA.png'},
        {'name': 'Mozambique', 'code': 'MZ', 'icon': '/shared/vendor/img/flags/MZ.png'},
        {'name': 'Myanmar', 'code': 'MM', 'icon': '/shared/vendor/img/flags/MM.png'},
        {'name': 'Namibia', 'code': 'NA', 'icon': '/shared/vendor/img/flags/NA.png'},
        {'name': 'Nauru', 'code': 'NR', 'icon': '/shared/vendor/img/flags/NR.png'},
        {'name': 'Nepal', 'code': 'NP', 'icon': '/shared/vendor/img/flags/NP.png'},
        {'name': 'Netherlands', 'code': 'NL', 'icon': '/shared/vendor/img/flags/NL.png'},
        {'name': 'New Zealand', 'code': 'NZ', 'icon': '/shared/vendor/img/flags/NZ.png'},
        {'name': 'Nicaragua', 'code': 'NI', 'icon': '/shared/vendor/img/flags/NI.png'},
        {'name': 'Niger', 'code': 'NE', 'icon': '/shared/vendor/img/flags/NE.png'},
        {'name': 'Nigeria', 'code': 'NG', 'icon': '/shared/vendor/img/flags/NG.png'},
        {'name': 'Norway', 'code': 'NO', 'icon': '/shared/vendor/img/flags/NO.png'},
        {'name': 'Oman', 'code': 'OM', 'icon': '/shared/vendor/img/flags/OM.png'},
        {'name': 'Pakistan', 'code': 'PK', 'icon': '/shared/vendor/img/flags/PK.png'},
        {'name': 'Palau', 'code': 'PW', 'icon': '/shared/vendor/img/flags/PW.png'},
        {'name': 'Palestine', 'code': 'PS', 'icon': '/shared/vendor/img/flags/PS.png'},
        {'name': 'Panama', 'code': 'PA', 'icon': '/shared/vendor/img/flags/PA.png'},
        {'name': 'Papua New Guinea', 'code': 'PG', 'icon': '/shared/vendor/img/flags/PG.png'},
        {'name': 'Paraguay', 'code': 'PY', 'icon': '/shared/vendor/img/flags/PY.png'},
        {'name': 'Peru', 'code': 'PE', 'icon': '/shared/vendor/img/flags/PE.png'},
        {'name': 'Philippines', 'code': 'PH', 'icon': '/shared/vendor/img/flags/PH.png'},
        {'name': 'Poland', 'code': 'PL', 'icon': '/shared/vendor/img/flags/PL.png'},
        {'name': 'Portugal', 'code': 'PT', 'icon': '/shared/vendor/img/flags/PT.png'},
        {'name': 'Qatar', 'code': 'QA', 'icon': '/shared/vendor/img/flags/QA.png'},
        {'name': 'Romania', 'code': 'RO', 'icon': '/shared/vendor/img/flags/RO.png'},
        {'name': 'Russia', 'code': 'RU', 'icon': '/shared/vendor/img/flags/RU.png'},
        {'name': 'Rwanda', 'code': 'RW', 'icon': '/shared/vendor/img/flags/RW.png'},
        {'name': 'Saint Helena, Ascension and Tristan Da Cunha', 'code': 'SH', 'icon': '/shared/vendor/img/flags/SH.png'},
        {'name': 'Saint Kitts And Nevis', 'code': 'KN', 'icon': '/shared/vendor/img/flags/KN.png'},
        {'name': 'Saint Lucia', 'code': 'LC', 'icon': '/shared/vendor/img/flags/LC.png'},
        {'name': 'Saint Vincent And The Grenadines', 'code': 'VC', 'icon': '/shared/vendor/img/flags/VC.png'},
        {'name': 'Samoa', 'code': 'WS', 'icon': '/shared/vendor/img/flags/WS.png'},
        {'name': 'San Marino', 'code': 'SM', 'icon': '/shared/vendor/img/flags/SM.png'},
        {'name': 'Sao Tome and Principe', 'code': 'ST', 'icon': '/shared/vendor/img/flags/ST.png'},
        {'name': 'Saudi Arabia', 'code': 'SA', 'icon': '/shared/vendor/img/flags/SA.png'},
        {'name': 'Senegal', 'code': 'SN', 'icon': '/shared/vendor/img/flags/SN.png'},
        {'name': 'Serbia', 'code': 'RS', 'icon': '/shared/vendor/img/flags/RS.png'},
        {'name': 'Seychelles', 'code': 'SC', 'icon': '/shared/vendor/img/flags/SC.png'},
        {'name': 'Sierra Leone', 'code': 'SL', 'icon': '/shared/vendor/img/flags/SL.png'},
        {'name': 'Singapore', 'code': 'SG', 'icon': '/shared/vendor/img/flags/SG.png'},
        {'name': 'Slovakia', 'code': 'SK', 'icon': '/shared/vendor/img/flags/SK.png'},
        {'name': 'Slovenia', 'code': 'SI', 'icon': '/shared/vendor/img/flags/SI.png'},
        {'name': 'Solomon Islands', 'code': 'SB', 'icon': '/shared/vendor/img/flags/SB.png'},
        {'name': 'Somalia', 'code': 'SO', 'icon': '/shared/vendor/img/flags/SO.png'},
        {'name': 'South Africa', 'code': 'ZA', 'icon': '/shared/vendor/img/flags/ZA.png'},
        {'name': 'South Sudan', 'code': 'SS', 'icon': '/shared/vendor/img/flags/SS.png'},
        {'name': 'Spain', 'code': 'ES', 'icon': '/shared/vendor/img/flags/ES.png'},
        {'name': 'Sri Lanka', 'code': 'LK', 'icon': '/shared/vendor/img/flags/LK.png'},
        {'name': 'Sudan', 'code': 'SD', 'icon': '/shared/vendor/img/flags/SD.png'},
        {'name': 'Suriname', 'code': 'SR', 'icon': '/shared/vendor/img/flags/SR.png'},
        {'name': 'Swaziland', 'code': 'SZ', 'icon': '/shared/vendor/img/flags/SZ.png'},
        {'name': 'Sweden', 'code': 'SE', 'icon': '/shared/vendor/img/flags/SE.png'},
        {'name': 'Switzerland', 'code': 'CH', 'icon': '/shared/vendor/img/flags/CH.png'},
        {'name': 'Syria', 'code': 'SY', 'icon': '/shared/vendor/img/flags/SY.png'},
        {'name': 'Taiwan', 'code': 'TW', 'icon': '/shared/vendor/img/flags/TW.png'},
        {'name': 'Tajikistan', 'code': 'TJ', 'icon': '/shared/vendor/img/flags/TJ.png'},
        {'name': 'Tanzania', 'code': 'TZ', 'icon': '/shared/vendor/img/flags/TZ.png'},
        {'name': 'Thailand', 'code': 'TH', 'icon': '/shared/vendor/img/flags/TH.png'},
        {'name': 'Timor-Leste', 'code': 'TL', 'icon': '/shared/vendor/img/flags/TL.png'},
        {'name': 'Togo', 'code': 'TG', 'icon': '/shared/vendor/img/flags/TG.png'},
        {'name': 'Tonga', 'code': 'TO', 'icon': '/shared/vendor/img/flags/TO.png'},
        {'name': 'Trinidad and Tobago', 'code': 'TT', 'icon': '/shared/vendor/img/flags/TT.png'},
        {'name': 'Tunisia', 'code': 'TN', 'icon': '/shared/vendor/img/flags/TN.png'},
        {'name': 'Turkey', 'code': 'TR', 'icon': '/shared/vendor/img/flags/TR.png'},
        {'name': 'Turkmenistan', 'code': 'TM', 'icon': '/shared/vendor/img/flags/TM.png'},
        {'name': 'Tuvalu', 'code': 'TV', 'icon': '/shared/vendor/img/flags/TV.png'},
        {'name': 'Uganda', 'code': 'UG', 'icon': '/shared/vendor/img/flags/UG.png'},
        {'name': 'Ukraine', 'code': 'UA', 'icon': '/shared/vendor/img/flags/UA.png'},
        {'name': 'United Arab Emirates', 'code': 'AE', 'icon': '/shared/vendor/img/flags/AE.png'},
        {'name': 'United Kingdom', 'code': 'GB', 'icon': '/shared/vendor/img/flags/GB.png'},
        {'name': 'United States', 'code': 'US', 'icon': '/shared/vendor/img/flags/US.png'},
        {'name': 'United States Minor Outlying Islands', 'code': 'UM', 'icon': '/shared/vendor/img/flags/UM.png'},
        {'name': 'Uruguay', 'code': 'UY', 'icon': '/shared/vendor/img/flags/UY.png'},
        {'name': 'Uzbekistan', 'code': 'UZ', 'icon': '/shared/vendor/img/flags/UZ.png'},
        {'name': 'Vanuatu', 'code': 'VU', 'icon': '/shared/vendor/img/flags/VU.png'},
        {'name': 'Venezuela', 'code': 'VE', 'icon': '/shared/vendor/img/flags/VE.png'},
        {'name': 'Viet Nam', 'code': 'VN', 'icon': '/shared/vendor/img/flags/VN.png'},
        {'name': 'Western Sahara', 'code': 'EH', 'icon': '/shared/vendor/img/flags/EH.png'},
        {'name': 'Yemen', 'code': 'YE', 'icon': '/shared/vendor/img/flags/YE.png'},
        {'name': 'Zambia', 'code': 'ZM', 'icon': '/shared/vendor/img/flags/ZM.png'},
        {'name': 'Zimbabwe', 'code': 'ZW', 'icon': '/shared/vendor/img/flags/ZW.png'}
    ];
});
