/*!
 * Copyright 2015 Apereo Foundation (AF) Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 *     http://opensource.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/**
 * Module that will export all known english country names with their ISO-3166-1
 * code. The list of countries exported by this module were derived from the
 * list of countries in the iso-3166-2 module:
 *
 *  https://github.com/olahol/iso-3166-2.js
 *
 * @param  {Object}     exports   Properties that are added on this object are exported
 */
define(['exports'], function(exports) {
    exports.countries = [
        {'name': 'Afghanistan', 'code': 'AF'},
        {'name': 'Albania', 'code': 'AL'},
        {'name': 'Algeria', 'code': 'DZ'},
        {'name': 'Andorra', 'code': 'AD'},
        {'name': 'Angola', 'code': 'AO'},
        {'name': 'Antigua and Barbuda', 'code': 'AG'},
        {'name': 'Argentina', 'code': 'AR'},
        {'name': 'Armenia', 'code': 'AM'},
        {'name': 'Australia', 'code': 'AU'},
        {'name': 'Austria', 'code': 'AT'},
        {'name': 'Azerbaijan', 'code': 'AZ'},
        {'name': 'Bahamas', 'code': 'BS'},
        {'name': 'Bahrain', 'code': 'BH'},
        {'name': 'Bangladesh', 'code': 'BD'},
        {'name': 'Barbados', 'code': 'BB'},
        {'name': 'Belarus', 'code': 'BY'},
        {'name': 'Belgium', 'code': 'BE'},
        {'name': 'Belize', 'code': 'BZ'},
        {'name': 'Benin', 'code': 'BJ'},
        {'name': 'Bermuda', 'code': 'BM'},
        {'name': 'Bhutan', 'code': 'BT'},
        {'name': 'Bolivia', 'code': 'BO'},
        {'name': 'Bonaire, Sint Eustatius and Saba', 'code': 'BQ'},
        {'name': 'Bosnia and Herzegovina', 'code': 'BA'},
        {'name': 'Botswana', 'code': 'BW'},
        {'name': 'Brazil', 'code': 'BR'},
        {'name': 'Brunei Darussalam', 'code': 'BN'},
        {'name': 'Bulgaria', 'code': 'BG'},
        {'name': 'Burkina Faso', 'code': 'BF'},
        {'name': 'Burundi', 'code': 'BI'},
        {'name': 'Cambodia', 'code': 'KH'},
        {'name': 'Cameroon', 'code': 'CM'},
        {'name': 'Canada', 'code': 'CA'},
        {'name': 'Cape Verde', 'code': 'CV'},
        {'name': 'Cayman Islands', 'code': 'KY'},
        {'name': 'Central African Republic', 'code': 'CF'},
        {'name': 'Chad', 'code': 'TD'},
        {'name': 'Chile', 'code': 'CL'},
        {'name': 'China', 'code': 'CN'},
        {'name': 'Colombia', 'code': 'CO'},
        {'name': 'Comoros', 'code': 'KM'},
        {'name': 'Congo', 'code': 'CG'},
        {'name': 'Congo, The Democratic Republic Of The', 'code': 'CD'},
        {'name': 'Costa Rica', 'code': 'CR'},
        {'name': 'Croatia', 'code': 'HR'},
        {'name': 'Cuba', 'code': 'CU'},
        {'name': 'Cyprus', 'code': 'CY'},
        {'name': 'Czech Republic', 'code': 'CZ'},
        {'name': 'Côte D\'Ivoire', 'code': 'CI'},
        {'name': 'Denmark', 'code': 'DK'},
        {'name': 'Djibouti', 'code': 'DJ'},
        {'name': 'Dominica', 'code': 'DM'},
        {'name': 'Dominican Republic', 'code': 'DO'},
        {'name': 'Ecuador', 'code': 'EC'},
        {'name': 'Egypt', 'code': 'EG'},
        {'name': 'El Salvador', 'code': 'SV'},
        {'name': 'Equatorial Guinea', 'code': 'GQ'},
        {'name': 'Eritrea', 'code': 'ER'},
        {'name': 'Estonia', 'code': 'EE'},
        {'name': 'Ethiopia', 'code': 'ET'},
        {'name': 'Fiji', 'code': 'FJ'},
        {'name': 'Finland', 'code': 'FI'},
        {'name': 'France', 'code': 'FR'},
        {'name': 'French Southern Territories', 'code': 'TF'},
        {'name': 'Gabon', 'code': 'GA'},
        {'name': 'Gambia', 'code': 'GM'},
        {'name': 'Georgia', 'code': 'GE'},
        {'name': 'Germany', 'code': 'DE'},
        {'name': 'Ghana', 'code': 'GH'},
        {'name': 'Greece', 'code': 'GR'},
        {'name': 'Greenland', 'code': 'GL'},
        {'name': 'Grenada', 'code': 'GD'},
        {'name': 'Guatemala', 'code': 'GT'},
        {'name': 'Guinea', 'code': 'GN'},
        {'name': 'Guinea-Bissau', 'code': 'GW'},
        {'name': 'Guyana', 'code': 'GY'},
        {'name': 'Haiti', 'code': 'HT'},
        {'name': 'Honduras', 'code': 'HN'},
        {'name': 'Hungary', 'code': 'HU'},
        {'name': 'Iceland', 'code': 'IS'},
        {'name': 'India', 'code': 'IN'},
        {'name': 'Indonesia', 'code': 'ID'},
        {'name': 'Iran', 'code': 'IR'},
        {'name': 'Iraq', 'code': 'IQ'},
        {'name': 'Ireland', 'code': 'IE'},
        {'name': 'Israel', 'code': 'IL'},
        {'name': 'Italy', 'code': 'IT'},
        {'name': 'Jamaica', 'code': 'JM'},
        {'name': 'Japan', 'code': 'JP'},
        {'name': 'Jordan', 'code': 'JO'},
        {'name': 'Kazakhstan', 'code': 'KZ'},
        {'name': 'Kenya', 'code': 'KE'},
        {'name': 'Kiribati', 'code': 'KI'},
        {'name': 'Korea, Democratic People\'s Republic Of', 'code': 'KP'},
        {'name': 'Korea, Republic of', 'code': 'KR'},
        {'name': 'Kuwait', 'code': 'KW'},
        {'name': 'Kyrgyzstan', 'code': 'KG'},
        {'name': 'Laos', 'code': 'LA'},
        {'name': 'Latvia', 'code': 'LV'},
        {'name': 'Lebanon', 'code': 'LB'},
        {'name': 'Lesotho', 'code': 'LS'},
        {'name': 'Liberia', 'code': 'LR'},
        {'name': 'Libya', 'code': 'LY'},
        {'name': 'Liechtenstein', 'code': 'LI'},
        {'name': 'Lithuania', 'code': 'LT'},
        {'name': 'Luxembourg', 'code': 'LU'},
        {'name': 'Macao', 'code': 'MO'},
        {'name': 'Macedonia, the Former Yugoslav Republic Of', 'code': 'MK'},
        {'name': 'Madagascar', 'code': 'MG'},
        {'name': 'Malawi', 'code': 'MW'},
        {'name': 'Malaysia', 'code': 'MY'},
        {'name': 'Maldives', 'code': 'MV'},
        {'name': 'Mali', 'code': 'ML'},
        {'name': 'Malta', 'code': 'MT'},
        {'name': 'Marshall Islands', 'code': 'MH'},
        {'name': 'Mauritania', 'code': 'MR'},
        {'name': 'Mauritius', 'code': 'MU'},
        {'name': 'Mexico', 'code': 'MX'},
        {'name': 'Micronesia, Federated States Of', 'code': 'FM'},
        {'name': 'Moldova', 'code': 'MD'},
        {'name': 'Monaco', 'code': 'MC'},
        {'name': 'Mongolia', 'code': 'MN'},
        {'name': 'Montenegro', 'code': 'ME'},
        {'name': 'Morocco', 'code': 'MA'},
        {'name': 'Mozambique', 'code': 'MZ'},
        {'name': 'Myanmar', 'code': 'MM'},
        {'name': 'Namibia', 'code': 'NA'},
        {'name': 'Nauru', 'code': 'NR'},
        {'name': 'Nepal', 'code': 'NP'},
        {'name': 'Netherlands', 'code': 'NL'},
        {'name': 'New Zealand', 'code': 'NZ'},
        {'name': 'Nicaragua', 'code': 'NI'},
        {'name': 'Niger', 'code': 'NE'},
        {'name': 'Nigeria', 'code': 'NG'},
        {'name': 'Norway', 'code': 'NO'},
        {'name': 'Oman', 'code': 'OM'},
        {'name': 'Pakistan', 'code': 'PK'},
        {'name': 'Palau', 'code': 'PW'},
        {'name': 'Palestine', 'code': 'PS'},
        {'name': 'Panama', 'code': 'PA'},
        {'name': 'Papua New Guinea', 'code': 'PG'},
        {'name': 'Paraguay', 'code': 'PY'},
        {'name': 'Peru', 'code': 'PE'},
        {'name': 'Philippines', 'code': 'PH'},
        {'name': 'Poland', 'code': 'PL'},
        {'name': 'Portugal', 'code': 'PT'},
        {'name': 'Qatar', 'code': 'QA'},
        {'name': 'Romania', 'code': 'RO'},
        {'name': 'Russia', 'code': 'RU'},
        {'name': 'Rwanda', 'code': 'RW'},
        {'name': 'Saint Helena, Ascension and Tristan Da Cunha', 'code': 'SH'},
        {'name': 'Saint Kitts And Nevis', 'code': 'KN'},
        {'name': 'Saint Lucia', 'code': 'LC'},
        {'name': 'Saint Vincent And The Grenadines', 'code': 'VC'},
        {'name': 'Samoa', 'code': 'WS'},
        {'name': 'San Marino', 'code': 'SM'},
        {'name': 'Sao Tome and Principe', 'code': 'ST'},
        {'name': 'Saudi Arabia', 'code': 'SA'},
        {'name': 'Senegal', 'code': 'SN'},
        {'name': 'Serbia', 'code': 'RS'},
        {'name': 'Seychelles', 'code': 'SC'},
        {'name': 'Sierra Leone', 'code': 'SL'},
        {'name': 'Singapore', 'code': 'SG'},
        {'name': 'Slovakia', 'code': 'SK'},
        {'name': 'Slovenia', 'code': 'SI'},
        {'name': 'Solomon Islands', 'code': 'SB'},
        {'name': 'Somalia', 'code': 'SO'},
        {'name': 'South Africa', 'code': 'ZA'},
        {'name': 'South Sudan', 'code': 'SS'},
        {'name': 'Spain', 'code': 'ES'},
        {'name': 'Sri Lanka', 'code': 'LK'},
        {'name': 'Sudan', 'code': 'SD'},
        {'name': 'Suriname', 'code': 'SR'},
        {'name': 'Swaziland', 'code': 'SZ'},
        {'name': 'Sweden', 'code': 'SE'},
        {'name': 'Switzerland', 'code': 'CH'},
        {'name': 'Syria', 'code': 'SY'},
        {'name': 'Taiwan', 'code': 'TW'},
        {'name': 'Tajikistan', 'code': 'TJ'},
        {'name': 'Tanzania', 'code': 'TZ'},
        {'name': 'Thailand', 'code': 'TH'},
        {'name': 'Timor-Leste', 'code': 'TL'},
        {'name': 'Togo', 'code': 'TG'},
        {'name': 'Tonga', 'code': 'TO'},
        {'name': 'Trinidad and Tobago', 'code': 'TT'},
        {'name': 'Tunisia', 'code': 'TN'},
        {'name': 'Turkey', 'code': 'TR'},
        {'name': 'Turkmenistan', 'code': 'TM'},
        {'name': 'Tuvalu', 'code': 'TV'},
        {'name': 'Uganda', 'code': 'UG'},
        {'name': 'Ukraine', 'code': 'UA'},
        {'name': 'United Arab Emirates', 'code': 'AE'},
        {'name': 'United Kingdom', 'code': 'GB'},
        {'name': 'United States', 'code': 'US'},
        {'name': 'United States Minor Outlying Islands', 'code': 'UM'},
        {'name': 'Uruguay', 'code': 'UY'},
        {'name': 'Uzbekistan', 'code': 'UZ'},
        {'name': 'Vanuatu', 'code': 'VU'},
        {'name': 'Venezuela', 'code': 'VE'},
        {'name': 'Viet Nam', 'code': 'VN'},
        {'name': 'Western Sahara', 'code': 'EH'},
        {'name': 'Yemen', 'code': 'YE'},
        {'name': 'Zambia', 'code': 'ZM'},
        {'name': 'Zimbabwe', 'code': 'ZW'}
    ];
});
