/*
 * Licensed to the Sakai Foundation (SF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The SF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
/*global $, sdata, QueryString */

var sakai = sakai || {};

sakai.profilewow = function(){


    /////////////////////////////
    // CONFIGURATION VARIABLES //
    /////////////////////////////

    /*
     * This is a structure which UI would expect to get through /system/me
     * A subset of these would be stored in JCR the rest would be calculated on the fly
     * "value" and keys would be stored in JCR
     * "access": Would not be stored in JCR, but calculated and dumped on the fly according to the ACLs on the node
     * "source": Would not be stored in JCR, but calculated and dumped on the fly. This would tell wether the the source of data is external (LDAP for example) or internal (JCR)
     * "editable": Would not be stored in JCR, but calculated and dumped on the fly. Tells whether an element is editable or not in an external data source
     * some keys would be entirely generated on the fly, taking into account locale settings: "displayname" for example, where a full name could be generated by concatenation of first and last name but according to locale settings
     */
    var profile_data = {

        "basic": {
            "access": "public",
            "elements": {
                "firstname": {
                    "value": "Christian",
                    "source": "external",
                    "editable": false,
                    "access": "public"
                },
                "lastname": {
                    "value": "Vuerings",
                    "source": "external",
                    "editable": false,
                    "changeurl": "http://university.org/raven",
                    "access": "public"
                },
                "displayname": {
                    "value": "Christian Vuerings",
                    "source": "external",
                    "editable": false,
                    "access": "public"
                },
                "preferredname": {
                    "value": "denbuzze",
                    "source": "local",
                    "editable": true,
                    "access": "contacts"
                },
                "role": {
                    "value": "Student",
                    "source": "local",
                    "editable": true,
                    "access": "public"
                }
            }
        },
        "aboutme": {
            "access": "institution",
            "elements": {
                "aboutme": {
                    "value": "",
                    "source": "local",
                    "editable": true,
                    "access": "institution"
                },
                "academicinterests": {
                    "value": "",
                    "source": "local",
                    "editable": true,
                    "access": "institution"
                },
                "personalinterests": {
                    "value": "",
                    "source": "local",
                    "editable": true,
                    "access": "institution"
                },
                "hobbies": {
                    "value": "",
                    "source": "local",
                    "editable": true,
                    "access": "institution"
                }
            }
        },
        "publications": {
            "access": "public",
            "elements": [{
                "title": "Measuring quantum gravity on two legged mice",
                "authors": ["Jack Moorhen", "Nancy Fruit", "Ivan Behmetov"],
                "year": 1968,
                "url": "www.publications.org/pub_209438029384.pdf",
                "source": "local",
                "editable": true,
                "access": "contacts"
            }, {
                "title": "Measuring quantum gravity on 3 legged feral pigeons",
                "authors": ["Jack Moorhen", "Nancy Fruit"],
                "year": 1972,
                "url": "www.publications.org/pub_2983479283749.pdf",
                "source": "local",
                "editable": true,
                "access": "public"
            }]
        }
    };

    /*
     * This is a collection of profile config functions and settings
     * The structure of the config object is identical to the storage object
     * When system/me returns profile data for the logged in user the profile_config and profile_data objects could be merged
     * "label": the internationalisable message for the entry label in HTML
     * "required": Whether the entry is compulsory or not
     */
    var profile_config = {

        "basic": {
            "label": "__MSG__PROFILE_BASIC_LABEL__",
            "required": true,
            "display": true,
            "elements": {
                "firstname": {
                    "label": "__MSG__PROFILE_BASIC_FIRSTNAME_LABEL__",
                    "required": true,
                    "display": true,
                    "validation": function(input_value){
                        // Custom validation code here
                        if (typeof input_value === "string") {
                            return true;
                        }
                        else {
                            return "__MSG___PROFILE_BASIC_FIRSTNAME_ERROR_STRING__";
                        }
                    }
                },
                "lastname": {
                    "label": "__MSG__PROFILE_BASIC_LASTNAME_LABEL__",
                    "required": true,
                    "display": true
                },
                "displayname": {
                    "label": "__MSG__PROFILE_BASIC_DISPLAYNAME_LABEL__",
                    "required": true,
                    "display": true
                },
                "preferredname": {
                    "label": "__MSG__PROFILE_BASIC_PREFERREDNAME_LABEL__",
                    "required": false,
                    "display": true
                },
                "role": {
                    "label": "__MSG__PROFILE_BASIC_ROLE_LABEL__",
                    "required": true,
                    "display": true
                }
            }
        },
        "aboutme": {
            "label": "__MSG__PROFILE_ABOUTME_LABEL__",
            "required": true,
            "display": true,
            "elements": {
                "aboutme": {
                    "label": "__MSG__PROFILE_ABOUTME_LABEL__",
                    "required": false,
                    "display": true,
                    "example": "__MSG__PROFILE_ABOUTME_ABOUTME_EXAMPLE__",
                    "template": "profilewow_field_textarea_template"
                },
                "academicinterests": {
                    "label": "__MSG__PROFILE_ABOUTME_ACADEMICINTERESTS_LABEL__",
                    "required": false,
                    "display": true,
                    "example": "__MSG__PROFILE_ABOUTME_ACADEMICINTERESTS_EXAMPLE__"
                },
                "personalinterests": {
                    "label": "__MSG__PROFILE_ABOUTME_PERSONALINTERESTS_LABEL__",
                    "required": false,
                    "display": true,
                    "example": "__MSG__PROFILE_ABOUTME_PERSONALINTERESTS_EXAMPLE__"
                },
                "hobbies": {
                    "label": "__MSG__PROFILE_ABOUTME_HOBBIES_LABEL__",
                    "required": false,
                    "display": true,
                    "example": "__MSG__PROFILE_ABOUTME_HOBBIES_EXAMPLE__"
                }
            }
        },
        "publications": {
            "label": "__MSG__PROFILE_PUBLICATIONS_LABEL__",
            "required": false,
            "display": true,
            //"template": "profilewow_section_publications_template",
            "elements": {
                "title": {
                    "label": "__MSG__PROFILE_PUBLICATIONS_TITLE__",
                    "required": false,
                    "display": true,
                    "example": "__MSG__PROFILE_PUBLICATIONS_TITLE_EXAMPLE__"
                },
                "authors": {
                    "label": "__MSG__PROFILE_PUBLICATIONS_AUTHORS__",
                    "required": false,
                    "display": true,
                    "example": "__MSG__PROFILE_PUBLICATIONS_AUTHORS_EXAMPLE__"
                }
            }
        }
    };

    sakai.profilewow.profile = {
        chatstatus: "",
        config: profile_config,
        data: profile_data,
        isme: false,
        mode: {
            options: ["viewmy", "view", "edit"],
            value: "viewmy"
        },
        acls: {
            options: ["public", "institution", "contacts", "noone"],
            value: "public"
        },
        picture: "",
        status: ""
    };

    var userprofile;
    var querystring; // Variable that will contain the querystring object of the page


    ///////////////////
    // CSS SELECTORS //
    ///////////////////

    var profilewow_class = ".profilewow";
    var $profilewow_actions = $("#profilewow_actions", profilewow_class);
    var $profilewow_actions_template = $("#profilewow_actions_template", profilewow_class);
    var $profilewow_field_default_template = $("#profilewow_field_default_template", profilewow_class);
    var $profilewow_footer = $("#profilewow_footer", profilewow_class);
    var $profilewow_footer_button_dontupdate = $("#profilewow_footer_button_dontupdate", profilewow_class);
    var $profilewow_footer_button_edit = $("#profilewow_footer_button_edit", profilewow_class);
    var $profilewow_footer_template = $("#profilewow_footer_template", profilewow_class);
    var $profilewow_heading = $("#profilewow_heading", profilewow_class);
    var $profilewow_heading_template = $("#profilewow_heading_template", profilewow_class);
    var $profilewow_sectionwidgets_container = $("#profilewow_sectionwidgets_container", profilewow_class);
    var $profilewow_sectionwidgets_container_template = $("#profilewow_sectionwidgets_container_template", profilewow_class);


    ////////////////////
    // UTIL FUNCTIONS //
    ////////////////////

    /**
     * Change the mode of the current profile
     * @param {String} mode The mode for the profile (view | viewmy | edit)
     */
    var setProfileMode = function(mode){

        // Check the mode parameter
        if ($.inArray(mode, sakai.profilewow.profile.mode.options) !== -1) {

            // Set the correct profile mode
            sakai.profilewow.profile.mode.value = mode;

        }
        else {

            // Use the standard profile mode
            sakai.profilewow.profile.mode.value = sakai.profilewow.profile.mode.options[0];

            // Print a log message that the supplied mode isn't valid
            fluid.log("Profilewow - changeProfileMode - the supplied mode '" + mode + "' is not a valid profile mode. Using the default mode instead");

        }

    };

    /**
     * Get the profile mode from the querystring
     */
    var getProfileMode = function(){

        if (querystring.contains("mode")) {
            return querystring.get("mode");
        }
        return false;

    };

    /**
     * Change the profile mode
     * This will fire a redirect
     * @param {String} mode The mode you want to change to
     */
    var changeProfileMode = function(mode){

         // Check the mode parameter
        if ($.inArray(mode, sakai.profilewow.profile.mode.options) !== -1) {

            // Perform the redirect
            window.location = window.location.pathname + "?mode=" + mode;

        }

    };


    /**
     * Check whether the user is editing/looking at it's own profile or not
     * We do this because if it is the current user, we don't need to perform an extra search
     */
    var setIsMe = function(){

        // Check whether there is a user parameter in the querystring,
        // if so, check whether the userid is not the same as the user parameter
        if (querystring.contains("user") && querystring.get("user") !== sakai.data.me.user.userid) {
            sakai.profilewow.profile.isme = false;
        }
        else {
            sakai.profilewow.profile.isme = true;
        }

    };

    /**
     * Check whether there is a valid picture for the user
     * @param {Object} profile The profile object that could contain the profile picture
     * @return {String}
     * The complete URL of the profile picture
     * Will be an empty string if there is no picture
     */
    var constructProfilePicture = function(profile){

        if (profile.picture && profile["rep:userId"]) {
            return "/~" + profile["rep:userId"] + "/public/profile/" + $.parseJSON(profile.picture).name;
        }
        else {
            return "";
        }

    };

    /**
     * Set the profile data for the user such as the status and profile picture
     */
    var setProfileData = function(callback){

        // Check whether the user is looking/editing it's own profile
        if (sakai.profilewow.profile.isme) {

            // Set the profile picture for the user you are looking at
            // The actual location of the picture could be something like this: /~admin/public/profile/256x256_profilepicture
            sakai.profilewow.profile.picture = constructProfilePicture(sakai.data.me.profile);

            // Set the status for the user you want the information from
            if(sakai.data.me.profile.basic){
                sakai.profilewow.profile.status = $.parseJSON(sakai.data.me.profile.basic).status;
            }

            // Execute the callback function
            if (callback && typeof callback === "function") {
                callback();
            }

        }
        else {

            // We need to fire an Ajax GET request to get the profile data for the user
            $.ajax({
                data: {
                    "q": querystring.get("user")
                },
                url: sakai.config.URL.SEARCH_USERS,
                success: function(data){

                    // Check whether there are any results
                    if(data.results[0]){

                        // Set the correct userprofile data
                        userprofile = data.results[0];

                        // Set the profile picture
                        sakai.profilewow.profile.picture = constructProfilePicture(data.results[0]);

                        // Set the status for the user you want the information from
                        if(sakai.data.me.profile.basic){
                            sakai.profilewow.profile.status = $.parseJSON(sakai.data.me.profile.basic).status;
                        }
                    }

                },
                error: function(){
                    fluid.log("setProfilePicture: Could not find the user");
                },
                complete: function(data){

                    // Execute the callback function
                    if (callback && typeof callback === "function") {
                        callback();
                    }

                }
            });

        }

    };


    ///////////////////////
    // BINDING FUNCTIONS //
    ///////////////////////

    /**
     * Add binding to the footer elements
     */
    var addBindingFooter = function(){

        // Reinitialise jQuery objects
        $profilewow_footer_button_dontupdate = $($profilewow_footer_button_edit.selector);

        // Bind the don't update
        $profilewow_footer_button_dontupdate.bind("click", function(){

            // Change the profile mode
            changeProfileMode("viewmy");

        });

    };

    /**
     * Add binding to the action elements
     */
    var addBindingActions = function(){

        // Reinitialise jQuery objects
        $profilewow_footer_button_edit = $($profilewow_footer_button_edit.selector);

        // Bind the edit button
        $profilewow_footer_button_edit.bind("click", function(){

            // Change the profile mode
            changeProfileMode("edit");

        });

    };

    /**
     * Add binding to all the elements on the page
     */
    var addBinding = function(){

        // Add binding to the actions elements
        addBindingActions();

        // Add binding to footer elements
        addBindingFooter();

    };


    ////////////////////////
    // TEMPLATE FUNCTIONS //
    ////////////////////////

    /**
     * Render the profilewow site heading
     */
    var renderTemplateSiteHeading = function(){

        // Render the profilewow site heading
        $.TemplateRenderer($profilewow_heading_template, sakai.profilewow.profile, $profilewow_heading);

    };

    var renderTemplateActions = function(){

        // Render the actions for the profile
        $.TemplateRenderer($profilewow_actions_template, sakai.profilewow.profile, $profilewow_actions);

    };

    /**
     * Insert a profile section widget
     * @param {String} sectionname The name of the section e.g. basic/talks/aboutme
     */
    var insertProfileSectionWidget = function(sectionname) {

        // Create a JSON object to pass the sectionname along
        // Trimpath needs an object to be passed (not only a variable)
        var sectionobject = {
            "sectionname": "profilesection-" + sectionname
        };

        // Construct the html for the widget
        $profilewow_sectionwidgets_container.append($.TemplateRenderer($profilewow_sectionwidgets_container_template, sectionobject));

        // Bind a global event that can be triggered by the profilesection widgets
        $(window).bind("sakai-" + sectionobject.sectionname, function(eventtype, callback){

            if(callback && typeof callback === "function"){
                callback(sectionname);
            }

        });

    };

    /**
     * Insert the profile section widgets
     */
    var insertProfileSectionWidgets = function(){

        for(var i in sakai.profilewow.profile.config){
            if(sakai.profilewow.profile.config.hasOwnProperty(i)){

                // Insert a separate widget for each profile section widget
                insertProfileSectionWidget(i);

            }
        }

    };

    /**
     * Render the footer for profilewow
     */
    var renderTemplateFooter = function(){

        // Render the profilewow footer
        $profilewow_footer.html($.TemplateRenderer($profilewow_footer_template, sakai.profilewow.profile));

    };

    /**
     * Parse and render all the templates on the page
     */
    var renderTemplates = function(){

        // Render the site heading
        renderTemplateSiteHeading();

        // Render the profile actions
        renderTemplateActions();

        // Render the footer buttons
        renderTemplateFooter();

    };


    ////////////////////
    // INITIALISATION //
    ////////////////////

    var doInit = function(){

        // Set the querystring object variable
        // We use the following parameters:
        //    mode -> mode of the profile
        //    user -> the id of the user for which you want to see the profile
        querystring = new Querystring();

        // Get and set the profile mode
        var profilemode = getProfileMode();
        if (profilemode) {
            setProfileMode(profilemode);
        }

        // Check if you are looking at the logged-in user
        setIsMe();

        // Set the profile data
        setProfileData(function(){

            // Initialise the entity widget
            $(window).bind("sakai.api.UI.entity.ready", function(e){

                // Check whether we need to load the myprofile or the profile mode
                var whichprofile = sakai.profilewow.profile.isme ? "myprofile" : "profile";

                // Check which data we need to send
                var data = sakai.profilewow.profile.isme ? false : userprofile;

                // Render the entity widget
                sakai.api.UI.entity.render(whichprofile, data);

            });

            // Render all the templates
            renderTemplates();

            // Insert the profile section widgets
            insertProfileSectionWidgets();

            // Add binding to all the elements
            addBinding();

        });

    };

    doInit();
};

sakai.api.Widgets.Container.registerForLoad("sakai.profilewow");