/*
 * Licensed to the Sakai Foundation (SF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The SF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
/*global $, sdata, QueryString */

var sakai = sakai || {};

sakai.profilewow = function(){


    /////////////////////////////
    // CONFIGURATION VARIABLES //
    /////////////////////////////

    /*
     * This is a structure which UI would expect to get through /system/me
     * A subset of these would be stored in JCR the rest would be calculated on the fly
     * "value" and keys would be stored in JCR
     * "access": Would not be stored in JCR, but calculated and dumped on the fly according to the ACLs on the node
     * "source": Would not be stored in JCR, but calculated and dumped on the fly. This would tell wether the the source of data is external (LDAP for example) or internal (JCR)
     * "editable": Would not be stored in JCR, but calculated and dumped on the fly. Tells whether an element is editable or not in an external data source
     * some keys would be entirely generated on the fly, taking into account locale settings: "displayname" for example, where a full name could be generated by concatenation of first and last name but according to locale settings
     */
    var profile_data = {
        "basic": {
            "access": "public",
            "elements": {
                "firstname": {
                    "value": "Oszkar",
                    "source": "external",
                    "editable": false
                },
                "lastname": {
                    "value": "Nagy",
                    "source": "external",
                    "editable": true,
                    "changeurl": "http://university.org/raven"
                },
                "displayname": {
                    "value": "Nagy Oszkar",
                    "source": "external",
                    "editable": false
                },
                "role": {
                    "value": "Student",
                    "source": "local",
                    "editable": true
                }
            }
        },
        "aboutme": {
            "access": "institution",
            "elements": {
                "aboutme": {
                    "value": "",
                    "source": "local",
                    "editable": true
                },
                "academicinterests": {
                    "value": "",
                    "source": "local",
                    "editable": true
                }
            }
        },
        "publications": {
            "access": "contacts",
            "elements": [{
                "title": "Measuring quantum gravity on two legged mice",
                "authors": ["Jack Moorhen", "Nancy Fruit", "Ivan Behmetov"],
                "year": 1968,
                "url": "www.publications.org/pub_209438029384.pdf",
                "source": "local",
                "editable": true
            }, {
                "title": "Measuring quantum gravity on 3 legged feral pigeons",
                "authors": ["Jack Moorhen", "Nancy Fruit"],
                "year": 1972,
                "url": "www.publications.org/pub_2983479283749.pdf",
                "source": "local",
                "editable": true
            }]
        }
    };

    /*
     * This is a collection of profile config functions and settings
     * The structure of the config object is identical to the storage object
     * When system/me returns profile data for the logged in user the profile_config and profile_data objects could be merged
     * "label": the internationalisable message for the entry label in HTML
     * "required": Whether the entry is compulsory or not
     */
    var profile_config = {

        "basic": {
            "label": "__MSG_PROFILE_BASIC_LABEL",
            "required": true,
            "elements": {
                "firstname": {
                    "label": "__MSG_PROFILE_BASIC_FIRSTNAME_LABEL",
                    "required": true,
                    "validation": function(input_value){
                        // Custom validation code here
                        if (typeof input_value === "string") {
                            return true;
                        }
                        else {
                            return "__MSG__PROFILE_BASIC_FIRSTNAME_ERROR_STRING";
                        }
                    }
                }
            }
        },
        "aboutme": {
            "label": "__MSG_PROFILE_ABOUTME_LABEL",
            "required": true,
            "elements": {
                "aboutme": {
                    "label": "__MSG_PROFILE_ABOUTME_ABOUTME_LABEL",
                    "required": false,
                    "example": "__MSG_PROFILE_ABOUTME_ABOUTME_EXAMPLE"
                }
            }
        },
        "publications": {
            "label": "__MSG_PROFILE_ABOUTME_LABEL",
            "required": false,
            "elements": {
                "title": {
                    "label": "__MSG_PROFILE_PUBLICATIONS_TITLE",
                    "required": false,
                    "example": "__MSG_PROFILE_PUBLICATIONS_TITLE_EXAMPLE"
                },
                "authors": {
                    "label": "__MSG_PROFILE_PUBLICATIONS_AUTHORS",
                    "required": false,
                    "example": "__MSG_PROFILE_PUBLICATIONS_AUTHORS_EXAMPLE"
                }
            }
        }
    };

    var profile = {
        config: profile_config,
        data: profile_data,
        isme: false,
        mode: {
            options: ["viewmy", "view", "viewas", "edit"],
            value: "viewmy"
        },
        acls: {
            options: ["public", "institution", "contacts", "noone"],
            value: "public"
        },
        picture: ""
    };

    var querystring; // Variable that will contain the querystring object of the page


    ///////////////////
    // CSS SELECTORS //
    ///////////////////

    var profilewow_class = ".profilewow";
    var $profilewow_heading = $("#profilewow_heading", profilewow_class);
    var $profilewow_heading_template = $("#profilewow_heading_template", profilewow_class);
    var $profilewow_userinfo = $("#profilewow_userinfo", profilewow_class);
    var $profilewow_userinfo_template = $("#profilewow_userinfo_template", profilewow_class);


    ////////////////////
    // UTIL FUNCTIONS //
    ////////////////////

    /**
     * Change the mode of the current profile
     * @param {String} mode The mode for the profile (view | viewas | viewmy | edit)
     */
    var setProfileMode = function(mode){

        // Check the mode parameter
        if ($.inArray(mode, profile.mode.options) !== -1) {

            // Set the correct profile mode
            profile.mode.value = mode;

        }
        else {

            // Use the standard profile mode
            profile.mode.value = profile.mode.options[0];

            // Print a log message that the supplied mode isn't valid
            fluid.log("Profilewow - changeProfileMode - the supplied mode '" + mode + "' is not a valid profile mode. Using the default mode instead");

        }

    };

    /**
     * Get the profile mode from the querystring
     */
    var getProfileMode = function(){

        if (querystring.contains("mode")) {
            return querystring.get("mode");
        }
        return false;

    };

    /**
     * Check whether the user is editing/looking at it's own profile or not
     * We do this because if it is the current user, we don't need to perform an extra search
     */
    var setIsMe = function(){

        // Check whether there is a user parameter in the querystring,
        // if so, check whether the userid is not the same as the user parameter
        if (querystring.contains("user") && querystring.get("user") !== sakai.data.me.user.userid) {
            profile.isme = false;
        }
        else {
            profile.isme = true;
        }

    };

    /**
     * Check whether there is a valid picture for the user
     * @param {Object} profile The profile object that could contain the profile picture
     * @return {String}
     * The complete URL of the profile picture
     * Will be an empty string if there is no picture
     */
    var constructProfilePicture = function(profile){

        if (profile.picture && profile.path) {
            return "/_user" + profile.path + "/public/profile/" + $.evalJSON(profile.picture).name;
        }
        else {
            return "";
        }

    };

    /**
     * Set the profile picture for the user you are looking at
     * /_user/a/ad/admin/public/profile/256x256_profilepicture
     */
    var setProfilePicture = function(callback){

        // Check whether the user is looking/editing it's own profile
        if (profile.isme) {

            // Set the profile picture
            profile.picture = constructProfilePicture(sakai.data.me.profile);

            // Execute the callback function
            if (callback && typeof callback === "function") {
                callback();
            }

        }
        else {

            // We need to fire an Ajax GET request to get the picture for the user
            $.ajax({
                data: {
                    "username": querystring.get("user")
                },
                url: sakai.config.URL.SEARCH_USERS,
                error: function(){
                    fluid.log("setProfilePicture: Could not find the user");
                },
                success: function(data){

                    // Set the JSON response
                    var jsonResponse = $.evalJSON(data);

                    // Set the profile picture
                    profile.picture = constructProfilePicture(jsonResponse.results[0]);

                },
                complete: function(data){

                    // Execute the callback function
                    if (callback && typeof callback === "function") {
                        callback();
                    }

                }
            });

        }

    };


    ////////////////////////
    // TEMPLATE FUNCTIONS //
    ////////////////////////

    /**
     * Render the profilewow site heading
     */
    var renderTemplateSiteHeading = function(){

        // Render the profilewow site heading
        $.TemplateRenderer($profilewow_heading_template, profile, $profilewow_heading);

    };
    
    /**
     * Render the user information (such as picture / name / chat status)
     */
    var renderTemplateUserInfo = function(){

        // Render the user info
        $.TemplateRenderer($profilewow_userinfo_template, profile, $profilewow_userinfo);

    };

    /**
     * Parse and render all the templates on the page
     */
    var renderTemplates = function(){

        // Render the site heading
        renderTemplateSiteHeading();

        // Render the user info
        renderTemplateUserInfo();

    };


    ////////////////////
    // INITIALISATION //
    ////////////////////

    var doInit = function(){

        // Set the querystring object variable
        // We use the following parameters:
        //    mode -> mode of the profile
        //    user -> the id of the user for which you want to see the profile
        querystring = new Querystring();

        // Get and set the profile mode
        var profilemode = getProfileMode();
        if (profilemode) {
            setProfileMode(profilemode);
        }

        // Check if you are looking at the logged-in user
        setIsMe();

        // Set the profile picture (if there is any)
        setProfilePicture(function(){

            // Render all the templates
            renderTemplates();
        });

    };

    doInit();
};

sdata.container.registerForLoad("sakai.profilewow");